/* GENERATED by deck-build/build-sites.js — do not edit by hand. */
window.LK = {
 "generated": "2026-08-11",
 "scenario": "surgical",
 "assumptions": {
  "redeemsPerMonth": {
   "resident": 270,
   "longevity": 875
  },
  "blendedMemberDiscount": 0.08,
  "circuitVisitsPerMonth": {
   "resident": 5,
   "longevity": 8,
   "dayPass": 1
  },
  "circuitCostPerVisit": 8,
  "clubHoursPerDay": 14,
  "daysPerMonth": 30.4,
  "clinicalHoursPerDay": 10,
  "clinicalDaysPerMonth": 26,
  "circuitPracticalUtilization": 0.5,
  "treatmentRoomUtilization": 0.65,
  "plungeThroughputPerHour": 7.5,
  "procedureHoursEach": 1,
  "orBlockDaysPerMonth": 9,
  "orHoursPerDay": 10,
  "orUtilization": 0.7,
  "orHoursPerCase": 1.75,
  "primeRate": 0.0675,
  "sbaMaxSpread": 0.0275,
  "loanTermMonths": 120,
  "interestOnlyMonths": 18,
  "constructionMonths": 6,
  "avgConstructionDraw": 0.5,
  "equityInjectionFloor": 0.1,
  "equityInjectionPlanning": 0.2,
  "dscrThreshold": 1.25,
  "foundingPrepay": 3600,
  "foundingListPrice": 5400,
  "sbaRate": 0.095
 },
 "services": [
  {
   "id": "aescape",
   "name": "Aescape Robotic Massage",
   "cat": "Recovery",
   "margin": 0.85,
   "lo": 60,
   "hi": 80,
   "room": "aescape",
   "sessions": {
    "lean": 110,
    "ample": 200,
    "surgical": 200
   }
  },
  {
   "id": "ammortal",
   "name": "Ammortal Chamber",
   "cat": "Recovery",
   "margin": 0.82,
   "lo": 90,
   "hi": 150,
   "room": "ammortal",
   "sessions": {
    "lean": 70,
    "ample": 120,
    "surgical": 120
   }
  },
  {
   "id": "redlight",
   "name": "Red Light Therapy",
   "cat": "Recovery",
   "margin": 0.82,
   "lo": 50,
   "hi": 100,
   "room": "recovery",
   "sessions": {
    "lean": 50,
    "ample": 80,
    "surgical": 80
   }
  },
  {
   "id": "hbot",
   "name": "Hyperbaric Oxygen",
   "cat": "Recovery",
   "margin": 0.8,
   "lo": 150,
   "hi": 250,
   "room": "hbot",
   "sessions": {
    "lean": 55,
    "ample": 100,
    "surgical": 100
   }
  },
  {
   "id": "prp",
   "name": "PRP Injections",
   "cat": "Regenerative",
   "margin": 0.78,
   "lo": 800,
   "hi": 1500,
   "room": "treatment",
   "sessions": {
    "lean": 36,
    "ample": 50,
    "surgical": 50
   }
  },
  {
   "id": "compress",
   "name": "Compression / NeuFit",
   "cat": "Recovery",
   "margin": 0.78,
   "lo": 75,
   "hi": 150,
   "room": "recovery",
   "sessions": {
    "lean": 50,
    "ample": 80,
    "surgical": 80
   }
  },
  {
   "id": "hormone",
   "name": "Hormone / Peptide / GLP",
   "cat": "Regenerative",
   "margin": 0.75,
   "lo": 400,
   "hi": 800,
   "room": "treatment",
   "sessions": {
    "lean": 30,
    "ample": 40,
    "surgical": 40
   }
  },
  {
   "id": "iv",
   "name": "IV Therapy (NAD+ / Drips)",
   "cat": "Regenerative",
   "margin": 0.72,
   "lo": 350,
   "hi": 1000,
   "room": "ivchair",
   "sessions": {
    "lean": 85,
    "ample": 120,
    "surgical": 120
   }
  },
  {
   "id": "botox",
   "name": "Botox & Fillers",
   "cat": "Aesthetics",
   "margin": 0.7,
   "lo": 500,
   "hi": 950,
   "room": "treatment",
   "sessions": {
    "lean": 58,
    "ample": 80,
    "surgical": 80
   }
  },
  {
   "id": "laser",
   "name": "Laser Platform",
   "cat": "Aesthetics",
   "margin": 0.7,
   "lo": 500,
   "hi": 1200,
   "room": "treatment",
   "sessions": {
    "lean": 20,
    "ample": 30,
    "surgical": 30
   }
  },
  {
   "id": "biometric",
   "name": "Advanced Biometrics",
   "cat": "Diagnostics",
   "margin": 0.7,
   "lo": 150,
   "hi": 300,
   "room": "diagnostic",
   "sessions": {
    "lean": 14,
    "ample": 20,
    "surgical": 20
   }
  },
  {
   "id": "morpheus",
   "name": "Morpheus8 RF Microneedling",
   "cat": "Aesthetics",
   "margin": 0.68,
   "lo": 835,
   "hi": 1500,
   "room": "treatment",
   "sessions": {
    "lean": 20,
    "ample": 30,
    "surgical": 30
   }
  },
  {
   "id": "dna",
   "name": "DNA Analysis",
   "cat": "Diagnostics",
   "margin": 0.67,
   "lo": 300,
   "hi": 500,
   "room": "diagnostic",
   "sessions": {
    "lean": 11,
    "ample": 15,
    "surgical": 15
   }
  },
  {
   "id": "emsculpt",
   "name": "Emsculpt",
   "cat": "Aesthetics",
   "margin": 0.67,
   "lo": 750,
   "hi": 1200,
   "room": "treatment",
   "sessions": {
    "lean": 20,
    "ample": 30,
    "surgical": 30
   }
  },
  {
   "id": "dutch",
   "name": "DUTCH Testing",
   "cat": "Diagnostics",
   "margin": 0.65,
   "lo": 400,
   "hi": 650,
   "room": "diagnostic",
   "sessions": {
    "lean": 14,
    "ample": 20,
    "surgical": 20
   }
  },
  {
   "id": "coolsculpt",
   "name": "CoolSculpting",
   "cat": "Aesthetics",
   "margin": 0.65,
   "lo": 700,
   "hi": 1200,
   "room": "treatment",
   "sessions": {
    "lean": 14,
    "ample": 20,
    "surgical": 20
   }
  },
  {
   "id": "dexa",
   "name": "DEXA Scan",
   "cat": "Diagnostics",
   "margin": 0.62,
   "lo": 200,
   "hi": 350,
   "room": "diagnostic",
   "sessions": {
    "lean": 14,
    "ample": 20,
    "surgical": 20
   }
  },
  {
   "id": "bleph",
   "name": "Blepharoplasty",
   "cat": "Surgery",
   "margin": 0.72,
   "lo": 4500,
   "hi": 8000,
   "room": "or",
   "sessions": {
    "lean": 0,
    "ample": 0,
    "surgical": 7
   }
  },
  {
   "id": "facialcon",
   "name": "Facial Contouring Surgery",
   "cat": "Surgery",
   "margin": 0.72,
   "lo": 3500,
   "hi": 9000,
   "room": "or",
   "sessions": {
    "lean": 0,
    "ample": 0,
    "surgical": 5
   }
  },
  {
   "id": "awakelipo",
   "name": "Awake Liposuction & Body Contouring",
   "cat": "Surgery",
   "margin": 0.7,
   "lo": 4500,
   "hi": 9000,
   "room": "or",
   "sessions": {
    "lean": 0,
    "ample": 0,
    "surgical": 6
   }
  },
  {
   "id": "fatgraft",
   "name": "Fat Grafting & Transfer",
   "cat": "Surgery",
   "margin": 0.72,
   "lo": 3500,
   "hi": 7000,
   "room": "or",
   "sessions": {
    "lean": 0,
    "ample": 0,
    "surgical": 4
   }
  },
  {
   "id": "hairrest",
   "name": "Hair Restoration Surgery",
   "cat": "Surgery",
   "margin": 0.74,
   "lo": 6000,
   "hi": 14000,
   "room": "treatment",
   "sessions": {
    "lean": 0,
    "ample": 0,
    "surgical": 3
   }
  },
  {
   "id": "officesurg",
   "name": "Office Surgical Procedures",
   "cat": "Surgery",
   "margin": 0.76,
   "lo": 900,
   "hi": 3500,
   "room": "treatment",
   "sessions": {
    "lean": 0,
    "ample": 0,
    "surgical": 12
   }
  },
  {
   "id": "ablative",
   "name": "Ablative Laser & Skin Tightening",
   "cat": "Surgery",
   "margin": 0.73,
   "lo": 2500,
   "hi": 6000,
   "room": "treatment",
   "sessions": {
    "lean": 0,
    "ample": 0,
    "surgical": 5
   }
  }
 ],
 "tiers": [
  {
   "id": "daypass",
   "name": "Day Pass",
   "cadence": "per visit",
   "price": 75,
   "blurb": "One visit to the recovery circuit. Book any procedure at rack rate.",
   "includes": [
    "Single circuit visit",
    "Procedures at rack rate",
    "No events or lounge privileges"
   ],
   "counts": {
    "lean": 190,
    "ample": 275,
    "surgical": 275
   },
   "isMembership": false
  },
  {
   "id": "friends",
   "name": "Friends of L&K",
   "cadence": "per year",
   "price": 300,
   "blurb": "The on-ramp. Member pricing without club access.",
   "includes": [
    "Member pricing on all procedures",
    "Priority booking window",
    "Invitations to open events",
    "No club or circuit access"
   ],
   "counts": {
    "lean": 750,
    "ample": 900,
    "surgical": 900
   },
   "isMembership": true,
   "monthly": 25,
   "usesCircuit": false
  },
  {
   "id": "resident",
   "name": "Resident",
   "cadence": "per month",
   "price": 450,
   "blurb": "The core membership. Where the club actually lives.",
   "includes": [
    "Rolling monthly credit bank",
    "Unlimited recovery circuit",
    "Member pricing on all procedures",
    "1 guest pass per month",
    "Member events"
   ],
   "counts": {
    "lean": 300,
    "ample": 350,
    "surgical": 350
   },
   "isMembership": true,
   "monthly": 450,
   "usesCircuit": true,
   "capped": true
  },
  {
   "id": "longevity",
   "name": "Longevity",
   "cadence": "per month",
   "price": 1250,
   "blurb": "Physician-led. Hard capped.",
   "includes": [
    "Everything in Resident",
    "Quarterly physician consult",
    "Annual biomarker panel, DEXA and DUTCH",
    "Hormone and peptide program included",
    "4 guest passes per month",
    "Private buyout privileges"
   ],
   "counts": {
    "lean": 32,
    "ample": 40,
    "surgical": 40
   },
   "isMembership": true,
   "monthly": 1250,
   "usesCircuit": true,
   "capped": true
  }
 ],
 "surgicalMenu": {
  "or": [
   "Blepharoplasty, upper, lower and combined",
   "Brow lift",
   "Otoplasty",
   "Chin augmentation and implant",
   "Buccal fat removal",
   "Facial fat grafting and transfer",
   "Liposuction, single or limited area, awake tumescent",
   "Submental neck contouring",
   "Limited body-contouring revision",
   "Scar revision, facial and body",
   "Nasal valve procedures sold as elective self-pay"
  ],
  "treatment": [
   "Lipoma removal",
   "Cyst removal",
   "Benign lesion removal",
   "Ablative laser resurfacing",
   "Skin tightening",
   "Hair restoration surgery and transplant"
  ],
  "excluded": [
   [
    "Breast augmentation, lift, implant exchange or removal",
    "General anesthesia in standard practice"
   ],
   [
    "Facelift and neck lift",
    "General anesthesia; recovery well beyond two hours"
   ],
   [
    "Cosmetic and revision rhinoplasty",
    "Airway risk from pharyngeal blood; general anesthesia standard"
   ],
   [
    "Mini and full abdominoplasty",
    "General anesthesia; extended recovery and caregiver discharge"
   ]
  ]
 },
 "market": [
  {
   "id": "wellness-economy",
   "value": "$6.8T",
   "label": "Global wellness economy, 2024",
   "note": "Grew 7.9% from 2023 to 2024 and has doubled in size since 2013.",
   "source": "Global Wellness Institute",
   "url": "https://globalwellnessinstitute.org/press-room/statistics-and-facts/"
  },
  {
   "id": "medspa-global",
   "value": "$27.8B",
   "label": "Global medical spa market, 2026",
   "note": "Up from $24.2B in 2025, projected to $78.2B by 2033 at a 15.9% CAGR. North America holds 41.2% of it, roughly $10B.",
   "source": "Grand View Research",
   "url": "https://www.grandviewresearch.com/industry-analysis/medical-spa-market"
  },
  {
   "id": "medspa-count",
   "value": "10,488",
   "label": "US medical spas, 2023",
   "note": "Up from 8,899 in 2022. The category is being built out right now, which is both the opportunity and the reason to differentiate.",
   "source": "Grand View Research",
   "url": "https://www.grandviewresearch.com/industry-analysis/medical-spa-market"
  },
  {
   "id": "consumer-priority",
   "value": "82%",
   "label": "US consumers calling wellness a top or important priority",
   "note": "The US consumer wellness market runs near $480B and is growing up to 10% a year.",
   "source": "McKinsey",
   "url": "https://patientfy.ai/blog/longevity-medicine-market-2026"
  },
  {
   "id": "concierge",
   "value": "$19.4B",
   "label": "US concierge medicine market by 2034",
   "note": "From about $8B in 2025. Longevity services are overwhelmingly elective, cash-pay, and increasingly sold through membership and concierge structures.",
   "source": "Cited in Patientfy longevity market map",
   "url": "https://patientfy.ai/blog/longevity-medicine-market-2026"
  },
  {
   "id": "glp1",
   "value": "1 in 8",
   "label": "US adults currently taking a GLP-1",
   "note": "For a hormone and longevity practice this is a front door, not a fad line item.",
   "source": "KFF",
   "url": "https://patientfy.ai/blog/longevity-medicine-market-2026"
  },
  {
   "id": "longevity-retreats",
   "value": "$11.1B",
   "label": "Longevity retreats market, 2026",
   "note": "From $9.82B in 2025, projected to $17.8B at a 12.6% CAGR.",
   "source": "Research and Markets",
   "url": "https://www.researchandmarkets.com/reports/6226679/longevity-retreats-market-report"
  }
 ],
 "catchment": [
  {
   "id": "income",
   "value": "$129,942",
   "label": "Playa Vista median household income",
   "note": "Against a Los Angeles County median well below it. This is a cash-pay catchment.",
   "source": "US Census Bureau, via Point2Homes",
   "url": "https://www.point2homes.com/US/Neighborhood/CA/Los-Angeles/Playa-Vista-Demographics.html"
  },
  {
   "id": "tech-companies",
   "value": "500+",
   "label": "Technology companies in Silicon Beach",
   "note": "The Westside tech corridor that Playa Vista sits at the center of.",
   "source": "Wikipedia, Silicon Beach",
   "url": "https://en.wikipedia.org/wiki/Silicon_Beach"
  },
  {
   "id": "campus-jobs",
   "value": "~5,100",
   "label": "Employed at The Campus at Playa Vista",
   "note": "Up from roughly 2,000 in 2015, a 150% increase. A dense, high-income daytime population inside walking distance.",
   "source": "Los Angeles Business Journal",
   "url": "https://labusinessjournal.com/real-estate/workers-silicon-beach-find-coast-costly/"
  }
 ],
 "geography": [
  "Playa Vista",
  "Marina del Rey",
  "Culver City",
  "Venice",
  "Santa Monica",
  "Playa del Rey",
  "El Segundo",
  "Westchester",
  "Mar Vista",
  "Manhattan Beach"
 ],
 "scenarios": {
  "lean": {
   "key": "lean",
   "label": "Lean",
   "projectCost": 3500000,
   "sqft": 4500,
   "tagline": "Leased equipment, tighter footprint, fastest path to positive cash flow.",
   "equipmentStrategy": "Leased",
   "stations": {
    "treatment": 2,
    "ivchair": 6,
    "sauna": 1,
    "plunge": 2,
    "aescape": 1,
    "ammortal": 1,
    "hbot": 1,
    "diagnostic": 1,
    "recovery": 3
   },
   "foundingMembers": 100,
   "space": [
    [
     "Arrival, concierge, retail",
     300
    ],
    [
     "The Lounge",
     600
    ],
    [
     "Contrast suite (1 sauna, 2 plunges)",
     420
    ],
    [
     "Recovery floor",
     700
    ],
    [
     "IV and regenerative lounge (6 chairs)",
     560
    ],
    [
     "Treatment rooms (2)",
     400
    ],
    [
     "Diagnostics and consult",
     350
    ],
    [
     "Locker, shower, changing",
     330
    ],
    [
     "Staff, MEP, storage, circulation",
     840
    ]
   ],
   "opex": {
    "Rent (4,500 SF NNN)": 24750,
    "Clinical and club staff": 88000,
    "Admin and management": 22000,
    "Marketing and member acquisition": 20000,
    "Malpractice and liability": 10000,
    "Equipment leases": 34000,
    "Utilities, software, member platform": 13000,
    "Licensing and compliance": 5000
   },
   "useOfFunds": [
    [
     "Buildout and tenant improvements (4,500 SF @ ~$210/SF)",
     945000
    ],
    [
     "Wet areas: sauna, plunges, drainage, ventilation",
     285000
    ],
    [
     "Equipment lease deposits and financed upfront",
     420000
    ],
    [
     "FF&E, lounge, millwork, retail",
     395000
    ],
    [
     "Pre-opening: licensing, legal, insurance, hiring",
     265000
    ],
    [
     "Brand, launch, founding member campaign",
     190000
    ],
    [
     "Working capital and debt service reserve",
     1000000
    ]
   ],
   "lines": [
    {
     "id": "aescape",
     "name": "Aescape Robotic Massage",
     "cat": "Recovery",
     "margin": 0.85,
     "lo": 60,
     "hi": 80,
     "room": "aescape",
     "sessions": 110,
     "price": 70,
     "gross": 7700,
     "cogs": 1155.0000000000002,
     "net": 6545
    },
    {
     "id": "ammortal",
     "name": "Ammortal Chamber",
     "cat": "Recovery",
     "margin": 0.82,
     "lo": 90,
     "hi": 150,
     "room": "ammortal",
     "sessions": 70,
     "price": 120,
     "gross": 8400,
     "cogs": 1512.0000000000005,
     "net": 6888
    },
    {
     "id": "redlight",
     "name": "Red Light Therapy",
     "cat": "Recovery",
     "margin": 0.82,
     "lo": 50,
     "hi": 100,
     "room": "recovery",
     "sessions": 50,
     "price": 75,
     "gross": 3750,
     "cogs": 675.0000000000002,
     "net": 3075
    },
    {
     "id": "hbot",
     "name": "Hyperbaric Oxygen",
     "cat": "Recovery",
     "margin": 0.8,
     "lo": 150,
     "hi": 250,
     "room": "hbot",
     "sessions": 55,
     "price": 200,
     "gross": 11000,
     "cogs": 2199.9999999999995,
     "net": 8800
    },
    {
     "id": "prp",
     "name": "PRP Injections",
     "cat": "Regenerative",
     "margin": 0.78,
     "lo": 800,
     "hi": 1500,
     "room": "treatment",
     "sessions": 36,
     "price": 1150,
     "gross": 41400,
     "cogs": 9107.999999999998,
     "net": 32292
    },
    {
     "id": "compress",
     "name": "Compression / NeuFit",
     "cat": "Recovery",
     "margin": 0.78,
     "lo": 75,
     "hi": 150,
     "room": "recovery",
     "sessions": 50,
     "price": 113,
     "gross": 5650,
     "cogs": 1242.9999999999998,
     "net": 4407
    },
    {
     "id": "hormone",
     "name": "Hormone / Peptide / GLP",
     "cat": "Regenerative",
     "margin": 0.75,
     "lo": 400,
     "hi": 800,
     "room": "treatment",
     "sessions": 30,
     "price": 600,
     "gross": 18000,
     "cogs": 4500,
     "net": 13500
    },
    {
     "id": "iv",
     "name": "IV Therapy (NAD+ / Drips)",
     "cat": "Regenerative",
     "margin": 0.72,
     "lo": 350,
     "hi": 1000,
     "room": "ivchair",
     "sessions": 85,
     "price": 675,
     "gross": 57375,
     "cogs": 16065.000000000002,
     "net": 41310
    },
    {
     "id": "botox",
     "name": "Botox & Fillers",
     "cat": "Aesthetics",
     "margin": 0.7,
     "lo": 500,
     "hi": 950,
     "room": "treatment",
     "sessions": 58,
     "price": 725,
     "gross": 42050,
     "cogs": 12615.000000000002,
     "net": 29434.999999999996
    },
    {
     "id": "laser",
     "name": "Laser Platform",
     "cat": "Aesthetics",
     "margin": 0.7,
     "lo": 500,
     "hi": 1200,
     "room": "treatment",
     "sessions": 20,
     "price": 850,
     "gross": 17000,
     "cogs": 5100.000000000001,
     "net": 11900
    },
    {
     "id": "biometric",
     "name": "Advanced Biometrics",
     "cat": "Diagnostics",
     "margin": 0.7,
     "lo": 150,
     "hi": 300,
     "room": "diagnostic",
     "sessions": 14,
     "price": 225,
     "gross": 3150,
     "cogs": 945.0000000000001,
     "net": 2205
    },
    {
     "id": "morpheus",
     "name": "Morpheus8 RF Microneedling",
     "cat": "Aesthetics",
     "margin": 0.68,
     "lo": 835,
     "hi": 1500,
     "room": "treatment",
     "sessions": 20,
     "price": 1168,
     "gross": 23360,
     "cogs": 7475.199999999999,
     "net": 15884.800000000001
    },
    {
     "id": "dna",
     "name": "DNA Analysis",
     "cat": "Diagnostics",
     "margin": 0.67,
     "lo": 300,
     "hi": 500,
     "room": "diagnostic",
     "sessions": 11,
     "price": 400,
     "gross": 4400,
     "cogs": 1451.9999999999998,
     "net": 2948
    },
    {
     "id": "emsculpt",
     "name": "Emsculpt",
     "cat": "Aesthetics",
     "margin": 0.67,
     "lo": 750,
     "hi": 1200,
     "room": "treatment",
     "sessions": 20,
     "price": 975,
     "gross": 19500,
     "cogs": 6434.999999999999,
     "net": 13065
    },
    {
     "id": "dutch",
     "name": "DUTCH Testing",
     "cat": "Diagnostics",
     "margin": 0.65,
     "lo": 400,
     "hi": 650,
     "room": "diagnostic",
     "sessions": 14,
     "price": 525,
     "gross": 7350,
     "cogs": 2572.5,
     "net": 4777.5
    },
    {
     "id": "coolsculpt",
     "name": "CoolSculpting",
     "cat": "Aesthetics",
     "margin": 0.65,
     "lo": 700,
     "hi": 1200,
     "room": "treatment",
     "sessions": 14,
     "price": 950,
     "gross": 13300,
     "cogs": 4655,
     "net": 8645
    },
    {
     "id": "dexa",
     "name": "DEXA Scan",
     "cat": "Diagnostics",
     "margin": 0.62,
     "lo": 200,
     "hi": 350,
     "room": "diagnostic",
     "sessions": 14,
     "price": 275,
     "gross": 3850,
     "cogs": 1463,
     "net": 2387
    },
    {
     "id": "bleph",
     "name": "Blepharoplasty",
     "cat": "Surgery",
     "margin": 0.72,
     "lo": 4500,
     "hi": 8000,
     "room": "or",
     "sessions": 0,
     "price": 6250,
     "gross": 0,
     "cogs": 0,
     "net": 0
    },
    {
     "id": "facialcon",
     "name": "Facial Contouring Surgery",
     "cat": "Surgery",
     "margin": 0.72,
     "lo": 3500,
     "hi": 9000,
     "room": "or",
     "sessions": 0,
     "price": 6250,
     "gross": 0,
     "cogs": 0,
     "net": 0
    },
    {
     "id": "awakelipo",
     "name": "Awake Liposuction & Body Contouring",
     "cat": "Surgery",
     "margin": 0.7,
     "lo": 4500,
     "hi": 9000,
     "room": "or",
     "sessions": 0,
     "price": 6750,
     "gross": 0,
     "cogs": 0,
     "net": 0
    },
    {
     "id": "fatgraft",
     "name": "Fat Grafting & Transfer",
     "cat": "Surgery",
     "margin": 0.72,
     "lo": 3500,
     "hi": 7000,
     "room": "or",
     "sessions": 0,
     "price": 5250,
     "gross": 0,
     "cogs": 0,
     "net": 0
    },
    {
     "id": "hairrest",
     "name": "Hair Restoration Surgery",
     "cat": "Surgery",
     "margin": 0.74,
     "lo": 6000,
     "hi": 14000,
     "room": "treatment",
     "sessions": 0,
     "price": 10000,
     "gross": 0,
     "cogs": 0,
     "net": 0
    },
    {
     "id": "officesurg",
     "name": "Office Surgical Procedures",
     "cat": "Surgery",
     "margin": 0.76,
     "lo": 900,
     "hi": 3500,
     "room": "treatment",
     "sessions": 0,
     "price": 2200,
     "gross": 0,
     "cogs": 0,
     "net": 0
    },
    {
     "id": "ablative",
     "name": "Ablative Laser & Skin Tightening",
     "cat": "Surgery",
     "margin": 0.73,
     "lo": 2500,
     "hi": 6000,
     "room": "treatment",
     "sessions": 0,
     "price": 4250,
     "gross": 0,
     "cogs": 0,
     "net": 0
    }
   ],
   "rackValue": 287235,
   "serviceCogs": 79170.7,
   "redeemed": 109000,
   "alaCarteGross": 178235,
   "memberDiscount": 14258.800000000001,
   "alaCarteNet": 163976.2,
   "membershipLines": [
    {
     "id": "friends",
     "name": "Friends of L&K",
     "count": 750,
     "monthly": 18750
    },
    {
     "id": "resident",
     "name": "Resident",
     "count": 300,
     "monthly": 135000
    },
    {
     "id": "longevity",
     "name": "Longevity",
     "count": 32,
     "monthly": 40000
    }
   ],
   "membershipRevenue": 193750,
   "accessRevenue": 14250,
   "totalRevenue": 371976.2,
   "circuitCogs": 15568,
   "totalCogs": 94738.7,
   "netAfterCogs": 277237.5,
   "blendedMargin": 0.7453097805719828,
   "serviceMargin": 0.7243695928420979,
   "redemptionRatio": 0.6228571428571429,
   "opexTotal": 216750,
   "operatingIncome": 60487.5,
   "operatingIncomeAnnual": 725850,
   "operatingMargin": 0.16261121007204224,
   "revenueAnnual": 4463714.4,
   "injectionFloor": 350000,
   "injectionPlanning": 700000,
   "loanFloor": 3150000,
   "loanPlanning": 2800000,
   "monthlyDebt": 45127,
   "annualDebt": 541523,
   "interestOnlyPayment": 24938,
   "dscr": 1.340386351782544,
   "rateBand": [
    {
     "rate": 0.095,
     "monthly": 45127,
     "annual": 541523,
     "dscr": 1.340386351782544
    },
    {
     "rate": 0.105,
     "monthly": 46813,
     "annual": 561758,
     "dscr": 1.2921036452471104
    },
    {
     "rate": 0.115,
     "monthly": 48533,
     "annual": 582401,
     "dscr": 1.2463064797626198
    }
   ],
   "founding": {
    "count": 100,
    "prepay": 3600,
    "discount": 0.33333333333333337,
    "proceeds": 360000
   },
   "capacity": {
    "operatingRoom": null,
    "circuit": {
     "theoretical": 6384,
     "practical": 3192,
     "demand": 1946,
     "utilization": 0.6096491228070177,
     "headroom": 1246
    },
    "treatmentRooms": {
     "theoretical": 520,
     "practical": 338,
     "demand": 198,
     "utilization": 0.5857988165680473,
     "headroom": 140
    }
   },
   "ramp": [
    {
     "month": 1,
     "maturity": 0,
     "open": false,
     "revenue": 0,
     "cogs": 0,
     "opex": 75863,
     "operating": -75862,
     "debtService": 12469,
     "foundingProceeds": 60000,
     "netCash": -28331,
     "cumulativeCash": -28331
    },
    {
     "month": 2,
     "maturity": 0,
     "open": false,
     "revenue": 0,
     "cogs": 0,
     "opex": 75863,
     "operating": -75862,
     "debtService": 12469,
     "foundingProceeds": 60000,
     "netCash": -28331,
     "cumulativeCash": -56662
    },
    {
     "month": 3,
     "maturity": 0,
     "open": false,
     "revenue": 0,
     "cogs": 0,
     "opex": 75863,
     "operating": -75862,
     "debtService": 12469,
     "foundingProceeds": 60000,
     "netCash": -28331,
     "cumulativeCash": -84994
    },
    {
     "month": 4,
     "maturity": 0,
     "open": false,
     "revenue": 0,
     "cogs": 0,
     "opex": 75863,
     "operating": -75862,
     "debtService": 12469,
     "foundingProceeds": 60000,
     "netCash": -28331,
     "cumulativeCash": -113325
    },
    {
     "month": 5,
     "maturity": 0,
     "open": false,
     "revenue": 0,
     "cogs": 0,
     "opex": 75863,
     "operating": -75862,
     "debtService": 12469,
     "foundingProceeds": 60000,
     "netCash": -28331,
     "cumulativeCash": -141656
    },
    {
     "month": 6,
     "maturity": 0,
     "open": false,
     "revenue": 0,
     "cogs": 0,
     "opex": 75863,
     "operating": -75862,
     "debtService": 12469,
     "foundingProceeds": 60000,
     "netCash": -28331,
     "cumulativeCash": -169987
    },
    {
     "month": 7,
     "maturity": 0.15,
     "open": true,
     "revenue": 55796,
     "cogs": 14211,
     "opex": 151725,
     "operating": -110139,
     "debtService": 24938,
     "foundingProceeds": 0,
     "netCash": -135077,
     "cumulativeCash": -305064
    },
    {
     "month": 8,
     "maturity": 0.22,
     "open": true,
     "revenue": 81835,
     "cogs": 20843,
     "opex": 151725,
     "operating": -90733,
     "debtService": 24938,
     "foundingProceeds": 0,
     "netCash": -115670,
     "cumulativeCash": -420735
    },
    {
     "month": 9,
     "maturity": 0.3,
     "open": true,
     "revenue": 111593,
     "cogs": 28422,
     "opex": 151725,
     "operating": -68554,
     "debtService": 24938,
     "foundingProceeds": 0,
     "netCash": -93491,
     "cumulativeCash": -514226
    },
    {
     "month": 10,
     "maturity": 0.36,
     "open": true,
     "revenue": 133911,
     "cogs": 34106,
     "opex": 151725,
     "operating": -51919,
     "debtService": 24938,
     "foundingProceeds": 0,
     "netCash": -76857,
     "cumulativeCash": -591083
    },
    {
     "month": 11,
     "maturity": 0.42,
     "open": true,
     "revenue": 156230,
     "cogs": 39790,
     "opex": 151725,
     "operating": -35285,
     "debtService": 24938,
     "foundingProceeds": 0,
     "netCash": -60223,
     "cumulativeCash": -651306
    },
    {
     "month": 12,
     "maturity": 0.48,
     "open": true,
     "revenue": 178549,
     "cogs": 45475,
     "opex": 151725,
     "operating": -18651,
     "debtService": 24938,
     "foundingProceeds": 0,
     "netCash": -43588,
     "cumulativeCash": -694894
    },
    {
     "month": 13,
     "maturity": 0.54,
     "open": true,
     "revenue": 200867,
     "cogs": 51159,
     "opex": 151725,
     "operating": -2017,
     "debtService": 24938,
     "foundingProceeds": 0,
     "netCash": -26954,
     "cumulativeCash": -721848
    },
    {
     "month": 14,
     "maturity": 0.58,
     "open": true,
     "revenue": 215746,
     "cogs": 54948,
     "opex": 151725,
     "operating": 9073,
     "debtService": 24938,
     "foundingProceeds": 0,
     "netCash": -15865,
     "cumulativeCash": -737713
    },
    {
     "month": 15,
     "maturity": 0.62,
     "open": true,
     "revenue": 230625,
     "cogs": 58738,
     "opex": 151725,
     "operating": 20162,
     "debtService": 24938,
     "foundingProceeds": 0,
     "netCash": -4775,
     "cumulativeCash": -742488
    },
    {
     "month": 16,
     "maturity": 0.66,
     "open": true,
     "revenue": 245504,
     "cogs": 62528,
     "opex": 151725,
     "operating": 31252,
     "debtService": 24938,
     "foundingProceeds": 0,
     "netCash": 6314,
     "cumulativeCash": -736174
    },
    {
     "month": 17,
     "maturity": 0.7,
     "open": true,
     "revenue": 260383,
     "cogs": 66317,
     "opex": 151725,
     "operating": 42341,
     "debtService": 24938,
     "foundingProceeds": 0,
     "netCash": 17404,
     "cumulativeCash": -718770
    },
    {
     "month": 18,
     "maturity": 0.73,
     "open": true,
     "revenue": 271543,
     "cogs": 69159,
     "opex": 158228,
     "operating": 44156,
     "debtService": 24938,
     "foundingProceeds": 0,
     "netCash": 19218,
     "cumulativeCash": -699552
    },
    {
     "month": 19,
     "maturity": 0.76,
     "open": true,
     "revenue": 282702,
     "cogs": 72001,
     "opex": 164730,
     "operating": 45971,
     "debtService": 45127,
     "foundingProceeds": 0,
     "netCash": 844,
     "cumulativeCash": -698708
    },
    {
     "month": 20,
     "maturity": 0.79,
     "open": true,
     "revenue": 293861,
     "cogs": 74844,
     "opex": 171233,
     "operating": 47785,
     "debtService": 45127,
     "foundingProceeds": 0,
     "netCash": 2658,
     "cumulativeCash": -696050
    },
    {
     "month": 21,
     "maturity": 0.82,
     "open": true,
     "revenue": 305020,
     "cogs": 77686,
     "opex": 177735,
     "operating": 49600,
     "debtService": 45127,
     "foundingProceeds": 0,
     "netCash": 4473,
     "cumulativeCash": -691577
    },
    {
     "month": 22,
     "maturity": 0.85,
     "open": true,
     "revenue": 316180,
     "cogs": 80528,
     "opex": 184238,
     "operating": 51414,
     "debtService": 45127,
     "foundingProceeds": 0,
     "netCash": 6287,
     "cumulativeCash": -685290
    },
    {
     "month": 23,
     "maturity": 0.87,
     "open": true,
     "revenue": 323619,
     "cogs": 82423,
     "opex": 188573,
     "operating": 52624,
     "debtService": 45127,
     "foundingProceeds": 0,
     "netCash": 7497,
     "cumulativeCash": -677793
    },
    {
     "month": 24,
     "maturity": 0.89,
     "open": true,
     "revenue": 331059,
     "cogs": 84317,
     "opex": 192908,
     "operating": 53834,
     "debtService": 45127,
     "foundingProceeds": 0,
     "netCash": 8707,
     "cumulativeCash": -669086
    },
    {
     "month": 25,
     "maturity": 0.91,
     "open": true,
     "revenue": 338498,
     "cogs": 86212,
     "opex": 197243,
     "operating": 55044,
     "debtService": 45127,
     "foundingProceeds": 0,
     "netCash": 9917,
     "cumulativeCash": -659169
    },
    {
     "month": 26,
     "maturity": 0.93,
     "open": true,
     "revenue": 345938,
     "cogs": 88107,
     "opex": 201578,
     "operating": 56253,
     "debtService": 45127,
     "foundingProceeds": 0,
     "netCash": 11126,
     "cumulativeCash": -648043
    },
    {
     "month": 27,
     "maturity": 0.94,
     "open": true,
     "revenue": 349658,
     "cogs": 89054,
     "opex": 203745,
     "operating": 56858,
     "debtService": 45127,
     "foundingProceeds": 0,
     "netCash": 11731,
     "cumulativeCash": -636311
    },
    {
     "month": 28,
     "maturity": 0.96,
     "open": true,
     "revenue": 357097,
     "cogs": 90949,
     "opex": 208080,
     "operating": 58068,
     "debtService": 45127,
     "foundingProceeds": 0,
     "netCash": 12941,
     "cumulativeCash": -623370
    },
    {
     "month": 29,
     "maturity": 0.97,
     "open": true,
     "revenue": 360817,
     "cogs": 91897,
     "opex": 210248,
     "operating": 58673,
     "debtService": 45127,
     "foundingProceeds": 0,
     "netCash": 13546,
     "cumulativeCash": -609824
    },
    {
     "month": 30,
     "maturity": 0.98,
     "open": true,
     "revenue": 364537,
     "cogs": 92844,
     "opex": 212415,
     "operating": 59278,
     "debtService": 45127,
     "foundingProceeds": 0,
     "netCash": 14151,
     "cumulativeCash": -595673
    },
    {
     "month": 31,
     "maturity": 0.99,
     "open": true,
     "revenue": 368256,
     "cogs": 93791,
     "opex": 214583,
     "operating": 59883,
     "debtService": 45127,
     "foundingProceeds": 0,
     "netCash": 14756,
     "cumulativeCash": -580918
    },
    {
     "month": 32,
     "maturity": 1,
     "open": true,
     "revenue": 371976,
     "cogs": 94739,
     "opex": 216750,
     "operating": 60488,
     "debtService": 45127,
     "foundingProceeds": 0,
     "netCash": 15361,
     "cumulativeCash": -565557
    },
    {
     "month": 33,
     "maturity": 1,
     "open": true,
     "revenue": 371976,
     "cogs": 94739,
     "opex": 216750,
     "operating": 60488,
     "debtService": 45127,
     "foundingProceeds": 0,
     "netCash": 15361,
     "cumulativeCash": -550196
    },
    {
     "month": 34,
     "maturity": 1,
     "open": true,
     "revenue": 371976,
     "cogs": 94739,
     "opex": 216750,
     "operating": 60488,
     "debtService": 45127,
     "foundingProceeds": 0,
     "netCash": 15361,
     "cumulativeCash": -534836
    },
    {
     "month": 35,
     "maturity": 1,
     "open": true,
     "revenue": 371976,
     "cogs": 94739,
     "opex": 216750,
     "operating": 60488,
     "debtService": 45127,
     "foundingProceeds": 0,
     "netCash": 15361,
     "cumulativeCash": -519475
    },
    {
     "month": 36,
     "maturity": 1,
     "open": true,
     "revenue": 371976,
     "cogs": 94739,
     "opex": 216750,
     "operating": 60488,
     "debtService": 45127,
     "foundingProceeds": 0,
     "netCash": 15361,
     "cumulativeCash": -504115
    }
   ],
   "breakeven": 14,
   "dscrByYear": [
    {
     "year": 1,
     "operating": -830453,
     "debt": 224442,
     "dscr": -3.7000784166956273,
     "passes": false
    },
    {
     "year": 2,
     "operating": 446195,
     "debt": 420390,
     "dscr": 1.061383477247318,
     "passes": false
    },
    {
     "year": 3,
     "operating": 706497,
     "debt": 541524,
     "dscr": 1.3046457774724667,
     "passes": true
    }
   ],
   "band": [
    {
     "label": "Low",
     "tag": "Slow member ramp, 72% of base volume",
     "revenue": 267823,
     "netAfterCogs": 199611,
     "operating": -17139,
     "annual": -205668,
     "dscr": -0.3797955026840965
    },
    {
     "label": "Base",
     "tag": "Stated assumptions at stabilization",
     "revenue": 371976,
     "netAfterCogs": 277238,
     "operating": 60488,
     "annual": 725850,
     "dscr": 1.3403862809151228
    },
    {
     "label": "Upside",
     "tag": "Waitlist demand, 128% of base volume",
     "revenue": 476130,
     "netAfterCogs": 354864,
     "operating": 138114,
     "annual": 1657368,
     "dscr": 3.060568064514342
    }
   ],
   "trough": {
    "month": 15,
    "amount": -742488
   },
   "reserve": 1000000,
   "rateStressPasses": false,
   "rateStress": {
    "rate": 0.115,
    "monthly": 48533,
    "annual": 582401,
    "dscr": 1.2463064797626198
   }
  },
  "ample": {
   "key": "ample",
   "label": "Ample",
   "projectCost": 5000000,
   "sqft": 5800,
   "tagline": "Full contrast suite, owned equipment, the facility the brand deserves.",
   "equipmentStrategy": "Purchased where payback justifies it",
   "stations": {
    "treatment": 3,
    "ivchair": 8,
    "sauna": 2,
    "plunge": 2,
    "aescape": 2,
    "ammortal": 2,
    "hbot": 1,
    "diagnostic": 2,
    "recovery": 4
   },
   "foundingMembers": 150,
   "space": [
    [
     "Arrival, concierge, retail",
     350
    ],
    [
     "The Lounge",
     700
    ],
    [
     "Contrast suite (2 saunas, 2 plunges)",
     550
    ],
    [
     "Recovery floor",
     900
    ],
    [
     "IV and regenerative lounge (8 chairs)",
     700
    ],
    [
     "Treatment rooms (3)",
     600
    ],
    [
     "Diagnostics and consult",
     450
    ],
    [
     "Locker, shower, changing",
     400
    ],
    [
     "Staff, MEP, storage, circulation",
     1150
    ]
   ],
   "opex": {
    "Rent (5,800 SF NNN)": 31900,
    "Clinical and club staff": 135000,
    "Admin and management": 28000,
    "Marketing and member acquisition": 30000,
    "Malpractice and liability": 12000,
    "Equipment leases": 24000,
    "Utilities, software, member platform": 16000,
    "Licensing and compliance": 6000
   },
   "useOfFunds": [
    [
     "Buildout and tenant improvements (5,800 SF @ $250/SF)",
     1450000
    ],
    [
     "Wet areas: 2 saunas, 2 plunges, steam, drainage, ventilation",
     465000
    ],
    [
     "Medical and aesthetic equipment (purchased)",
     780000
    ],
    [
     "Recovery technology: HBOT, Ammortal, Aescape",
     370000
    ],
    [
     "FF&E, lounge, millwork, retail",
     430000
    ],
    [
     "Pre-opening: licensing, legal, insurance, hiring",
     310000
    ],
    [
     "Brand, launch, founding member campaign",
     237000
    ],
    [
     "Working capital and debt service reserve",
     958000
    ]
   ],
   "lines": [
    {
     "id": "aescape",
     "name": "Aescape Robotic Massage",
     "cat": "Recovery",
     "margin": 0.85,
     "lo": 60,
     "hi": 80,
     "room": "aescape",
     "sessions": 200,
     "price": 70,
     "gross": 14000,
     "cogs": 2100.0000000000005,
     "net": 11900
    },
    {
     "id": "ammortal",
     "name": "Ammortal Chamber",
     "cat": "Recovery",
     "margin": 0.82,
     "lo": 90,
     "hi": 150,
     "room": "ammortal",
     "sessions": 120,
     "price": 120,
     "gross": 14400,
     "cogs": 2592.000000000001,
     "net": 11808
    },
    {
     "id": "redlight",
     "name": "Red Light Therapy",
     "cat": "Recovery",
     "margin": 0.82,
     "lo": 50,
     "hi": 100,
     "room": "recovery",
     "sessions": 80,
     "price": 75,
     "gross": 6000,
     "cogs": 1080.0000000000002,
     "net": 4920
    },
    {
     "id": "hbot",
     "name": "Hyperbaric Oxygen",
     "cat": "Recovery",
     "margin": 0.8,
     "lo": 150,
     "hi": 250,
     "room": "hbot",
     "sessions": 100,
     "price": 200,
     "gross": 20000,
     "cogs": 3999.999999999999,
     "net": 16000
    },
    {
     "id": "prp",
     "name": "PRP Injections",
     "cat": "Regenerative",
     "margin": 0.78,
     "lo": 800,
     "hi": 1500,
     "room": "treatment",
     "sessions": 50,
     "price": 1150,
     "gross": 57500,
     "cogs": 12649.999999999998,
     "net": 44850
    },
    {
     "id": "compress",
     "name": "Compression / NeuFit",
     "cat": "Recovery",
     "margin": 0.78,
     "lo": 75,
     "hi": 150,
     "room": "recovery",
     "sessions": 80,
     "price": 113,
     "gross": 9040,
     "cogs": 1988.7999999999997,
     "net": 7051.2
    },
    {
     "id": "hormone",
     "name": "Hormone / Peptide / GLP",
     "cat": "Regenerative",
     "margin": 0.75,
     "lo": 400,
     "hi": 800,
     "room": "treatment",
     "sessions": 40,
     "price": 600,
     "gross": 24000,
     "cogs": 6000,
     "net": 18000
    },
    {
     "id": "iv",
     "name": "IV Therapy (NAD+ / Drips)",
     "cat": "Regenerative",
     "margin": 0.72,
     "lo": 350,
     "hi": 1000,
     "room": "ivchair",
     "sessions": 120,
     "price": 675,
     "gross": 81000,
     "cogs": 22680.000000000004,
     "net": 58320
    },
    {
     "id": "botox",
     "name": "Botox & Fillers",
     "cat": "Aesthetics",
     "margin": 0.7,
     "lo": 500,
     "hi": 950,
     "room": "treatment",
     "sessions": 80,
     "price": 725,
     "gross": 58000,
     "cogs": 17400.000000000004,
     "net": 40600
    },
    {
     "id": "laser",
     "name": "Laser Platform",
     "cat": "Aesthetics",
     "margin": 0.7,
     "lo": 500,
     "hi": 1200,
     "room": "treatment",
     "sessions": 30,
     "price": 850,
     "gross": 25500,
     "cogs": 7650.000000000001,
     "net": 17850
    },
    {
     "id": "biometric",
     "name": "Advanced Biometrics",
     "cat": "Diagnostics",
     "margin": 0.7,
     "lo": 150,
     "hi": 300,
     "room": "diagnostic",
     "sessions": 20,
     "price": 225,
     "gross": 4500,
     "cogs": 1350.0000000000002,
     "net": 3150
    },
    {
     "id": "morpheus",
     "name": "Morpheus8 RF Microneedling",
     "cat": "Aesthetics",
     "margin": 0.68,
     "lo": 835,
     "hi": 1500,
     "room": "treatment",
     "sessions": 30,
     "price": 1168,
     "gross": 35040,
     "cogs": 11212.799999999997,
     "net": 23827.2
    },
    {
     "id": "dna",
     "name": "DNA Analysis",
     "cat": "Diagnostics",
     "margin": 0.67,
     "lo": 300,
     "hi": 500,
     "room": "diagnostic",
     "sessions": 15,
     "price": 400,
     "gross": 6000,
     "cogs": 1979.9999999999998,
     "net": 4020.0000000000005
    },
    {
     "id": "emsculpt",
     "name": "Emsculpt",
     "cat": "Aesthetics",
     "margin": 0.67,
     "lo": 750,
     "hi": 1200,
     "room": "treatment",
     "sessions": 30,
     "price": 975,
     "gross": 29250,
     "cogs": 9652.499999999998,
     "net": 19597.5
    },
    {
     "id": "dutch",
     "name": "DUTCH Testing",
     "cat": "Diagnostics",
     "margin": 0.65,
     "lo": 400,
     "hi": 650,
     "room": "diagnostic",
     "sessions": 20,
     "price": 525,
     "gross": 10500,
     "cogs": 3674.9999999999995,
     "net": 6825
    },
    {
     "id": "coolsculpt",
     "name": "CoolSculpting",
     "cat": "Aesthetics",
     "margin": 0.65,
     "lo": 700,
     "hi": 1200,
     "room": "treatment",
     "sessions": 20,
     "price": 950,
     "gross": 19000,
     "cogs": 6650,
     "net": 12350
    },
    {
     "id": "dexa",
     "name": "DEXA Scan",
     "cat": "Diagnostics",
     "margin": 0.62,
     "lo": 200,
     "hi": 350,
     "room": "diagnostic",
     "sessions": 20,
     "price": 275,
     "gross": 5500,
     "cogs": 2090,
     "net": 3410
    },
    {
     "id": "bleph",
     "name": "Blepharoplasty",
     "cat": "Surgery",
     "margin": 0.72,
     "lo": 4500,
     "hi": 8000,
     "room": "or",
     "sessions": 0,
     "price": 6250,
     "gross": 0,
     "cogs": 0,
     "net": 0
    },
    {
     "id": "facialcon",
     "name": "Facial Contouring Surgery",
     "cat": "Surgery",
     "margin": 0.72,
     "lo": 3500,
     "hi": 9000,
     "room": "or",
     "sessions": 0,
     "price": 6250,
     "gross": 0,
     "cogs": 0,
     "net": 0
    },
    {
     "id": "awakelipo",
     "name": "Awake Liposuction & Body Contouring",
     "cat": "Surgery",
     "margin": 0.7,
     "lo": 4500,
     "hi": 9000,
     "room": "or",
     "sessions": 0,
     "price": 6750,
     "gross": 0,
     "cogs": 0,
     "net": 0
    },
    {
     "id": "fatgraft",
     "name": "Fat Grafting & Transfer",
     "cat": "Surgery",
     "margin": 0.72,
     "lo": 3500,
     "hi": 7000,
     "room": "or",
     "sessions": 0,
     "price": 5250,
     "gross": 0,
     "cogs": 0,
     "net": 0
    },
    {
     "id": "hairrest",
     "name": "Hair Restoration Surgery",
     "cat": "Surgery",
     "margin": 0.74,
     "lo": 6000,
     "hi": 14000,
     "room": "treatment",
     "sessions": 0,
     "price": 10000,
     "gross": 0,
     "cogs": 0,
     "net": 0
    },
    {
     "id": "officesurg",
     "name": "Office Surgical Procedures",
     "cat": "Surgery",
     "margin": 0.76,
     "lo": 900,
     "hi": 3500,
     "room": "treatment",
     "sessions": 0,
     "price": 2200,
     "gross": 0,
     "cogs": 0,
     "net": 0
    },
    {
     "id": "ablative",
     "name": "Ablative Laser & Skin Tightening",
     "cat": "Surgery",
     "margin": 0.73,
     "lo": 2500,
     "hi": 6000,
     "room": "treatment",
     "sessions": 0,
     "price": 4250,
     "gross": 0,
     "cogs": 0,
     "net": 0
    }
   ],
   "rackValue": 419230,
   "serviceCogs": 114751.1,
   "redeemed": 129500,
   "alaCarteGross": 289730,
   "memberDiscount": 23178.4,
   "alaCarteNet": 266551.6,
   "membershipLines": [
    {
     "id": "friends",
     "name": "Friends of L&K",
     "count": 900,
     "monthly": 22500
    },
    {
     "id": "resident",
     "name": "Resident",
     "count": 350,
     "monthly": 157500
    },
    {
     "id": "longevity",
     "name": "Longevity",
     "count": 40,
     "monthly": 50000
    }
   ],
   "membershipRevenue": 230000,
   "accessRevenue": 20625,
   "totalRevenue": 517176.6,
   "circuitCogs": 18760,
   "totalCogs": 133511.1,
   "netAfterCogs": 383665.5,
   "blendedMargin": 0.7418462088191925,
   "serviceMargin": 0.7262812775803259,
   "redemptionRatio": 0.6240963855421687,
   "opexTotal": 282900,
   "operatingIncome": 100765.5,
   "operatingIncomeAnnual": 1209186,
   "operatingMargin": 0.19483770147373258,
   "revenueAnnual": 6206119.199999999,
   "injectionFloor": 500000,
   "injectionPlanning": 1000000,
   "loanFloor": 4500000,
   "loanPlanning": 4000000,
   "monthlyDebt": 64467,
   "annualDebt": 773604,
   "interestOnlyPayment": 35625,
   "dscr": 1.5630550221348338,
   "rateBand": [
    {
     "rate": 0.095,
     "monthly": 64467,
     "annual": 773604,
     "dscr": 1.5630550221348338
    },
    {
     "rate": 0.105,
     "monthly": 66876,
     "annual": 802512,
     "dscr": 1.506751459485074
    },
    {
     "rate": 0.115,
     "monthly": 69333,
     "annual": 832001,
     "dscr": 1.4533463428074258
    }
   ],
   "founding": {
    "count": 150,
    "prepay": 3600,
    "discount": 0.33333333333333337,
    "proceeds": 540000
   },
   "capacity": {
    "operatingRoom": null,
    "circuit": {
     "theoretical": 6384,
     "practical": 3192,
     "demand": 2345,
     "utilization": 0.7346491228070177,
     "headroom": 847
    },
    "treatmentRooms": {
     "theoretical": 780,
     "practical": 507,
     "demand": 280,
     "utilization": 0.5522682445759369,
     "headroom": 227
    }
   },
   "ramp": [
    {
     "month": 1,
     "maturity": 0,
     "open": false,
     "revenue": 0,
     "cogs": 0,
     "opex": 99015,
     "operating": -99015,
     "debtService": 17813,
     "foundingProceeds": 90000,
     "netCash": -26827,
     "cumulativeCash": -26827
    },
    {
     "month": 2,
     "maturity": 0,
     "open": false,
     "revenue": 0,
     "cogs": 0,
     "opex": 99015,
     "operating": -99015,
     "debtService": 17813,
     "foundingProceeds": 90000,
     "netCash": -26827,
     "cumulativeCash": -53655
    },
    {
     "month": 3,
     "maturity": 0,
     "open": false,
     "revenue": 0,
     "cogs": 0,
     "opex": 99015,
     "operating": -99015,
     "debtService": 17813,
     "foundingProceeds": 90000,
     "netCash": -26827,
     "cumulativeCash": -80482
    },
    {
     "month": 4,
     "maturity": 0,
     "open": false,
     "revenue": 0,
     "cogs": 0,
     "opex": 99015,
     "operating": -99015,
     "debtService": 17813,
     "foundingProceeds": 90000,
     "netCash": -26827,
     "cumulativeCash": -107310
    },
    {
     "month": 5,
     "maturity": 0,
     "open": false,
     "revenue": 0,
     "cogs": 0,
     "opex": 99015,
     "operating": -99015,
     "debtService": 17813,
     "foundingProceeds": 90000,
     "netCash": -26827,
     "cumulativeCash": -134137
    },
    {
     "month": 6,
     "maturity": 0,
     "open": false,
     "revenue": 0,
     "cogs": 0,
     "opex": 99015,
     "operating": -99015,
     "debtService": 17813,
     "foundingProceeds": 90000,
     "netCash": -26827,
     "cumulativeCash": -160965
    },
    {
     "month": 7,
     "maturity": 0.15,
     "open": true,
     "revenue": 77576,
     "cogs": 20027,
     "opex": 198030,
     "operating": -140480,
     "debtService": 35625,
     "foundingProceeds": 0,
     "netCash": -176105,
     "cumulativeCash": -337070
    },
    {
     "month": 8,
     "maturity": 0.22,
     "open": true,
     "revenue": 113779,
     "cogs": 29372,
     "opex": 198030,
     "operating": -113624,
     "debtService": 35625,
     "foundingProceeds": 0,
     "netCash": -149249,
     "cumulativeCash": -486319
    },
    {
     "month": 9,
     "maturity": 0.3,
     "open": true,
     "revenue": 155153,
     "cogs": 40053,
     "opex": 198030,
     "operating": -82930,
     "debtService": 35625,
     "foundingProceeds": 0,
     "netCash": -118555,
     "cumulativeCash": -604874
    },
    {
     "month": 10,
     "maturity": 0.36,
     "open": true,
     "revenue": 186184,
     "cogs": 48064,
     "opex": 198030,
     "operating": -59910,
     "debtService": 35625,
     "foundingProceeds": 0,
     "netCash": -95535,
     "cumulativeCash": -700410
    },
    {
     "month": 11,
     "maturity": 0.42,
     "open": true,
     "revenue": 217214,
     "cogs": 56075,
     "opex": 198030,
     "operating": -36890,
     "debtService": 35625,
     "foundingProceeds": 0,
     "netCash": -72515,
     "cumulativeCash": -772925
    },
    {
     "month": 12,
     "maturity": 0.48,
     "open": true,
     "revenue": 248245,
     "cogs": 64085,
     "opex": 198030,
     "operating": -13871,
     "debtService": 35625,
     "foundingProceeds": 0,
     "netCash": -49496,
     "cumulativeCash": -822421
    },
    {
     "month": 13,
     "maturity": 0.54,
     "open": true,
     "revenue": 279275,
     "cogs": 72096,
     "opex": 198030,
     "operating": 9149,
     "debtService": 35625,
     "foundingProceeds": 0,
     "netCash": -26476,
     "cumulativeCash": -848896
    },
    {
     "month": 14,
     "maturity": 0.58,
     "open": true,
     "revenue": 299962,
     "cogs": 77436,
     "opex": 198030,
     "operating": 24496,
     "debtService": 35625,
     "foundingProceeds": 0,
     "netCash": -11129,
     "cumulativeCash": -860025
    },
    {
     "month": 15,
     "maturity": 0.62,
     "open": true,
     "revenue": 320649,
     "cogs": 82777,
     "opex": 198030,
     "operating": 39843,
     "debtService": 35625,
     "foundingProceeds": 0,
     "netCash": 4218,
     "cumulativeCash": -855808
    },
    {
     "month": 16,
     "maturity": 0.66,
     "open": true,
     "revenue": 341337,
     "cogs": 88117,
     "opex": 198030,
     "operating": 55189,
     "debtService": 35625,
     "foundingProceeds": 0,
     "netCash": 19564,
     "cumulativeCash": -836243
    },
    {
     "month": 17,
     "maturity": 0.7,
     "open": true,
     "revenue": 362024,
     "cogs": 93458,
     "opex": 198030,
     "operating": 70536,
     "debtService": 35625,
     "foundingProceeds": 0,
     "netCash": 34911,
     "cumulativeCash": -801333
    },
    {
     "month": 18,
     "maturity": 0.73,
     "open": true,
     "revenue": 377539,
     "cogs": 97463,
     "opex": 206517,
     "operating": 73559,
     "debtService": 35625,
     "foundingProceeds": 0,
     "netCash": 37934,
     "cumulativeCash": -763399
    },
    {
     "month": 19,
     "maturity": 0.76,
     "open": true,
     "revenue": 393054,
     "cogs": 101468,
     "opex": 215004,
     "operating": 76582,
     "debtService": 64467,
     "foundingProceeds": 0,
     "netCash": 12115,
     "cumulativeCash": -751284
    },
    {
     "month": 20,
     "maturity": 0.79,
     "open": true,
     "revenue": 408570,
     "cogs": 105474,
     "opex": 223491,
     "operating": 79605,
     "debtService": 64467,
     "foundingProceeds": 0,
     "netCash": 15138,
     "cumulativeCash": -736146
    },
    {
     "month": 21,
     "maturity": 0.82,
     "open": true,
     "revenue": 424085,
     "cogs": 109479,
     "opex": 231978,
     "operating": 82628,
     "debtService": 64467,
     "foundingProceeds": 0,
     "netCash": 18161,
     "cumulativeCash": -717986
    },
    {
     "month": 22,
     "maturity": 0.85,
     "open": true,
     "revenue": 439600,
     "cogs": 113484,
     "opex": 240465,
     "operating": 85651,
     "debtService": 64467,
     "foundingProceeds": 0,
     "netCash": 21184,
     "cumulativeCash": -696802
    },
    {
     "month": 23,
     "maturity": 0.87,
     "open": true,
     "revenue": 449944,
     "cogs": 116155,
     "opex": 246123,
     "operating": 87666,
     "debtService": 64467,
     "foundingProceeds": 0,
     "netCash": 23199,
     "cumulativeCash": -673603
    },
    {
     "month": 24,
     "maturity": 0.89,
     "open": true,
     "revenue": 460287,
     "cogs": 118825,
     "opex": 251781,
     "operating": 89681,
     "debtService": 64467,
     "foundingProceeds": 0,
     "netCash": 25214,
     "cumulativeCash": -648389
    },
    {
     "month": 25,
     "maturity": 0.91,
     "open": true,
     "revenue": 470631,
     "cogs": 121495,
     "opex": 257439,
     "operating": 91697,
     "debtService": 64467,
     "foundingProceeds": 0,
     "netCash": 27230,
     "cumulativeCash": -621159
    },
    {
     "month": 26,
     "maturity": 0.93,
     "open": true,
     "revenue": 480974,
     "cogs": 124165,
     "opex": 263097,
     "operating": 93712,
     "debtService": 64467,
     "foundingProceeds": 0,
     "netCash": 29245,
     "cumulativeCash": -591914
    },
    {
     "month": 27,
     "maturity": 0.94,
     "open": true,
     "revenue": 486146,
     "cogs": 125500,
     "opex": 265926,
     "operating": 94720,
     "debtService": 64467,
     "foundingProceeds": 0,
     "netCash": 30253,
     "cumulativeCash": -561662
    },
    {
     "month": 28,
     "maturity": 0.96,
     "open": true,
     "revenue": 496490,
     "cogs": 128171,
     "opex": 271584,
     "operating": 96735,
     "debtService": 64467,
     "foundingProceeds": 0,
     "netCash": 32268,
     "cumulativeCash": -529394
    },
    {
     "month": 29,
     "maturity": 0.97,
     "open": true,
     "revenue": 501661,
     "cogs": 129506,
     "opex": 274413,
     "operating": 97743,
     "debtService": 64467,
     "foundingProceeds": 0,
     "netCash": 33276,
     "cumulativeCash": -496118
    },
    {
     "month": 30,
     "maturity": 0.98,
     "open": true,
     "revenue": 506833,
     "cogs": 130841,
     "opex": 277242,
     "operating": 98750,
     "debtService": 64467,
     "foundingProceeds": 0,
     "netCash": 34283,
     "cumulativeCash": -461835
    },
    {
     "month": 31,
     "maturity": 0.99,
     "open": true,
     "revenue": 512005,
     "cogs": 132176,
     "opex": 280071,
     "operating": 99758,
     "debtService": 64467,
     "foundingProceeds": 0,
     "netCash": 35291,
     "cumulativeCash": -426544
    },
    {
     "month": 32,
     "maturity": 1,
     "open": true,
     "revenue": 517177,
     "cogs": 133511,
     "opex": 282900,
     "operating": 100766,
     "debtService": 64467,
     "foundingProceeds": 0,
     "netCash": 36298,
     "cumulativeCash": -390246
    },
    {
     "month": 33,
     "maturity": 1,
     "open": true,
     "revenue": 517177,
     "cogs": 133511,
     "opex": 282900,
     "operating": 100766,
     "debtService": 64467,
     "foundingProceeds": 0,
     "netCash": 36298,
     "cumulativeCash": -353947
    },
    {
     "month": 34,
     "maturity": 1,
     "open": true,
     "revenue": 517177,
     "cogs": 133511,
     "opex": 282900,
     "operating": 100766,
     "debtService": 64467,
     "foundingProceeds": 0,
     "netCash": 36298,
     "cumulativeCash": -317649
    },
    {
     "month": 35,
     "maturity": 1,
     "open": true,
     "revenue": 517177,
     "cogs": 133511,
     "opex": 282900,
     "operating": 100766,
     "debtService": 64467,
     "foundingProceeds": 0,
     "netCash": 36298,
     "cumulativeCash": -281350
    },
    {
     "month": 36,
     "maturity": 1,
     "open": true,
     "revenue": 517177,
     "cogs": 133511,
     "opex": 282900,
     "operating": 100766,
     "debtService": 64467,
     "foundingProceeds": 0,
     "netCash": 36298,
     "cumulativeCash": -245052
    }
   ],
   "breakeven": 13,
   "dscrByYear": [
    {
     "year": 1,
     "operating": -1041795,
     "debt": 320628,
     "dscr": -3.2492327557169056,
     "passes": false
    },
    {
     "year": 2,
     "operating": 774585,
     "debt": 600552,
     "dscr": 1.2897883946768973,
     "passes": true
    },
    {
     "year": 3,
     "operating": 1176945,
     "debt": 773604,
     "dscr": 1.521379155226705,
     "passes": true
    }
   ],
   "band": [
    {
     "label": "Low",
     "tag": "Slow member ramp, 72% of base volume",
     "revenue": 372367,
     "netAfterCogs": 276239,
     "operating": -6661,
     "annual": -79930,
     "dscr": -0.10332169947415086
    },
    {
     "label": "Base",
     "tag": "Stated assumptions at stabilization",
     "revenue": 517177,
     "netAfterCogs": 383666,
     "operating": 100766,
     "annual": 1209186,
     "dscr": 1.563055516776025
    },
    {
     "label": "Upside",
     "tag": "Waitlist demand, 128% of base volume",
     "revenue": 661986,
     "netAfterCogs": 491092,
     "operating": 208192,
     "annual": 2498302,
     "dscr": 3.229432733026199
    }
   ],
   "trough": {
    "month": 14,
    "amount": -860025
   },
   "reserve": 958000,
   "rateStressPasses": true,
   "rateStress": {
    "rate": 0.115,
    "monthly": 69333,
    "annual": 832001,
    "dscr": 1.4533463428074258
   }
  },
  "surgical": {
   "key": "surgical",
   "label": "Surgical",
   "projectCost": 5550000,
   "sqft": 6700,
   "tagline": "Everything in the ample case, plus one accredited office-based surgery suite.",
   "equipmentStrategy": "Purchased where payback justifies it, surgical equipment part leased",
   "stations": {
    "treatment": 3,
    "ivchair": 8,
    "sauna": 2,
    "plunge": 2,
    "aescape": 2,
    "ammortal": 2,
    "hbot": 1,
    "diagnostic": 2,
    "recovery": 4,
    "or": 1
   },
   "foundingMembers": 150,
   "space": [
    [
     "Arrival, concierge, retail",
     350
    ],
    [
     "The Lounge",
     700
    ],
    [
     "Contrast suite (2 saunas, 2 plunges)",
     550
    ],
    [
     "Recovery floor",
     900
    ],
    [
     "IV and regenerative lounge (8 chairs)",
     700
    ],
    [
     "Treatment rooms (3)",
     600
    ],
    [
     "Diagnostics and consult",
     450
    ],
    [
     "Operating room",
     350
    ],
    [
     "Pre-op and PACU (3 monitored bays)",
     220
    ],
    [
     "Sterile processing",
     110
    ],
    [
     "Sterile supply",
     90
    ],
    [
     "Soiled utility",
     50
    ],
    [
     "Surgical suite circulation",
     80
    ],
    [
     "Locker, shower, changing",
     400
    ],
    [
     "Staff, MEP, storage, circulation",
     1150
    ]
   ],
   "opex": {
    "Rent (6,700 SF NNN)": 36850,
    "Clinical and club staff": 173000,
    "Admin and management": 30000,
    "Marketing and member acquisition": 32000,
    "Malpractice and liability": 26000,
    "Equipment leases": 37300,
    "Utilities, software, member platform": 18500,
    "Licensing, compliance and accreditation": 10000
   },
   "useOfFunds": [
    [
     "Buildout and tenant improvements (5,800 SF clinic and club @ $250/SF)",
     1450000
    ],
    [
     "Surgical suite buildout (900 SF @ $320/SF, OR-grade HVAC and finishes)",
     288000
    ],
    [
     "Medical gas, emergency power, life-safety branch for the suite",
     100000
    ],
    [
     "Wet areas: 2 saunas, 2 plunges, steam, drainage, ventilation",
     465000
    ],
    [
     "Medical and aesthetic equipment (purchased)",
     450000
    ],
    [
     "Surgical capital equipment (balance leased)",
     200000
    ],
    [
     "Recovery technology: HBOT, Ammortal, Aescape",
     370000
    ],
    [
     "FF&E, lounge, millwork, retail",
     400000
    ],
    [
     "Pre-opening: licensing, legal, insurance, hiring, transfer agreement",
     310000
    ],
    [
     "Accreditation: Quad A survey, policies, QA/PI program, staff training",
     110000
    ],
    [
     "Brand, launch, founding member campaign",
     200000
    ],
    [
     "Working capital and debt service reserve",
     1207000
    ]
   ],
   "lines": [
    {
     "id": "aescape",
     "name": "Aescape Robotic Massage",
     "cat": "Recovery",
     "margin": 0.85,
     "lo": 60,
     "hi": 80,
     "room": "aescape",
     "sessions": 200,
     "price": 70,
     "gross": 14000,
     "cogs": 2100.0000000000005,
     "net": 11900
    },
    {
     "id": "ammortal",
     "name": "Ammortal Chamber",
     "cat": "Recovery",
     "margin": 0.82,
     "lo": 90,
     "hi": 150,
     "room": "ammortal",
     "sessions": 120,
     "price": 120,
     "gross": 14400,
     "cogs": 2592.000000000001,
     "net": 11808
    },
    {
     "id": "redlight",
     "name": "Red Light Therapy",
     "cat": "Recovery",
     "margin": 0.82,
     "lo": 50,
     "hi": 100,
     "room": "recovery",
     "sessions": 80,
     "price": 75,
     "gross": 6000,
     "cogs": 1080.0000000000002,
     "net": 4920
    },
    {
     "id": "hbot",
     "name": "Hyperbaric Oxygen",
     "cat": "Recovery",
     "margin": 0.8,
     "lo": 150,
     "hi": 250,
     "room": "hbot",
     "sessions": 100,
     "price": 200,
     "gross": 20000,
     "cogs": 3999.999999999999,
     "net": 16000
    },
    {
     "id": "prp",
     "name": "PRP Injections",
     "cat": "Regenerative",
     "margin": 0.78,
     "lo": 800,
     "hi": 1500,
     "room": "treatment",
     "sessions": 50,
     "price": 1150,
     "gross": 57500,
     "cogs": 12649.999999999998,
     "net": 44850
    },
    {
     "id": "compress",
     "name": "Compression / NeuFit",
     "cat": "Recovery",
     "margin": 0.78,
     "lo": 75,
     "hi": 150,
     "room": "recovery",
     "sessions": 80,
     "price": 113,
     "gross": 9040,
     "cogs": 1988.7999999999997,
     "net": 7051.2
    },
    {
     "id": "hormone",
     "name": "Hormone / Peptide / GLP",
     "cat": "Regenerative",
     "margin": 0.75,
     "lo": 400,
     "hi": 800,
     "room": "treatment",
     "sessions": 40,
     "price": 600,
     "gross": 24000,
     "cogs": 6000,
     "net": 18000
    },
    {
     "id": "iv",
     "name": "IV Therapy (NAD+ / Drips)",
     "cat": "Regenerative",
     "margin": 0.72,
     "lo": 350,
     "hi": 1000,
     "room": "ivchair",
     "sessions": 120,
     "price": 675,
     "gross": 81000,
     "cogs": 22680.000000000004,
     "net": 58320
    },
    {
     "id": "botox",
     "name": "Botox & Fillers",
     "cat": "Aesthetics",
     "margin": 0.7,
     "lo": 500,
     "hi": 950,
     "room": "treatment",
     "sessions": 80,
     "price": 725,
     "gross": 58000,
     "cogs": 17400.000000000004,
     "net": 40600
    },
    {
     "id": "laser",
     "name": "Laser Platform",
     "cat": "Aesthetics",
     "margin": 0.7,
     "lo": 500,
     "hi": 1200,
     "room": "treatment",
     "sessions": 30,
     "price": 850,
     "gross": 25500,
     "cogs": 7650.000000000001,
     "net": 17850
    },
    {
     "id": "biometric",
     "name": "Advanced Biometrics",
     "cat": "Diagnostics",
     "margin": 0.7,
     "lo": 150,
     "hi": 300,
     "room": "diagnostic",
     "sessions": 20,
     "price": 225,
     "gross": 4500,
     "cogs": 1350.0000000000002,
     "net": 3150
    },
    {
     "id": "morpheus",
     "name": "Morpheus8 RF Microneedling",
     "cat": "Aesthetics",
     "margin": 0.68,
     "lo": 835,
     "hi": 1500,
     "room": "treatment",
     "sessions": 30,
     "price": 1168,
     "gross": 35040,
     "cogs": 11212.799999999997,
     "net": 23827.2
    },
    {
     "id": "dna",
     "name": "DNA Analysis",
     "cat": "Diagnostics",
     "margin": 0.67,
     "lo": 300,
     "hi": 500,
     "room": "diagnostic",
     "sessions": 15,
     "price": 400,
     "gross": 6000,
     "cogs": 1979.9999999999998,
     "net": 4020.0000000000005
    },
    {
     "id": "emsculpt",
     "name": "Emsculpt",
     "cat": "Aesthetics",
     "margin": 0.67,
     "lo": 750,
     "hi": 1200,
     "room": "treatment",
     "sessions": 30,
     "price": 975,
     "gross": 29250,
     "cogs": 9652.499999999998,
     "net": 19597.5
    },
    {
     "id": "dutch",
     "name": "DUTCH Testing",
     "cat": "Diagnostics",
     "margin": 0.65,
     "lo": 400,
     "hi": 650,
     "room": "diagnostic",
     "sessions": 20,
     "price": 525,
     "gross": 10500,
     "cogs": 3674.9999999999995,
     "net": 6825
    },
    {
     "id": "coolsculpt",
     "name": "CoolSculpting",
     "cat": "Aesthetics",
     "margin": 0.65,
     "lo": 700,
     "hi": 1200,
     "room": "treatment",
     "sessions": 20,
     "price": 950,
     "gross": 19000,
     "cogs": 6650,
     "net": 12350
    },
    {
     "id": "dexa",
     "name": "DEXA Scan",
     "cat": "Diagnostics",
     "margin": 0.62,
     "lo": 200,
     "hi": 350,
     "room": "diagnostic",
     "sessions": 20,
     "price": 275,
     "gross": 5500,
     "cogs": 2090,
     "net": 3410
    },
    {
     "id": "bleph",
     "name": "Blepharoplasty",
     "cat": "Surgery",
     "margin": 0.72,
     "lo": 4500,
     "hi": 8000,
     "room": "or",
     "sessions": 7,
     "price": 6250,
     "gross": 43750,
     "cogs": 12250.000000000002,
     "net": 31500
    },
    {
     "id": "facialcon",
     "name": "Facial Contouring Surgery",
     "cat": "Surgery",
     "margin": 0.72,
     "lo": 3500,
     "hi": 9000,
     "room": "or",
     "sessions": 5,
     "price": 6250,
     "gross": 31250,
     "cogs": 8750,
     "net": 22500
    },
    {
     "id": "awakelipo",
     "name": "Awake Liposuction & Body Contouring",
     "cat": "Surgery",
     "margin": 0.7,
     "lo": 4500,
     "hi": 9000,
     "room": "or",
     "sessions": 6,
     "price": 6750,
     "gross": 40500,
     "cogs": 12150.000000000002,
     "net": 28350
    },
    {
     "id": "fatgraft",
     "name": "Fat Grafting & Transfer",
     "cat": "Surgery",
     "margin": 0.72,
     "lo": 3500,
     "hi": 7000,
     "room": "or",
     "sessions": 4,
     "price": 5250,
     "gross": 21000,
     "cogs": 5880.000000000001,
     "net": 15120
    },
    {
     "id": "hairrest",
     "name": "Hair Restoration Surgery",
     "cat": "Surgery",
     "margin": 0.74,
     "lo": 6000,
     "hi": 14000,
     "room": "treatment",
     "sessions": 3,
     "price": 10000,
     "gross": 30000,
     "cogs": 7800,
     "net": 22200
    },
    {
     "id": "officesurg",
     "name": "Office Surgical Procedures",
     "cat": "Surgery",
     "margin": 0.76,
     "lo": 900,
     "hi": 3500,
     "room": "treatment",
     "sessions": 12,
     "price": 2200,
     "gross": 26400,
     "cogs": 6336,
     "net": 20064
    },
    {
     "id": "ablative",
     "name": "Ablative Laser & Skin Tightening",
     "cat": "Surgery",
     "margin": 0.73,
     "lo": 2500,
     "hi": 6000,
     "room": "treatment",
     "sessions": 5,
     "price": 4250,
     "gross": 21250,
     "cogs": 5737.5,
     "net": 15512.5
    }
   ],
   "rackValue": 633380,
   "serviceCogs": 173654.6,
   "redeemed": 129500,
   "alaCarteGross": 503880,
   "memberDiscount": 40310.4,
   "alaCarteNet": 463569.6,
   "membershipLines": [
    {
     "id": "friends",
     "name": "Friends of L&K",
     "count": 900,
     "monthly": 22500
    },
    {
     "id": "resident",
     "name": "Resident",
     "count": 350,
     "monthly": 157500
    },
    {
     "id": "longevity",
     "name": "Longevity",
     "count": 40,
     "monthly": 50000
    }
   ],
   "membershipRevenue": 230000,
   "accessRevenue": 20625,
   "totalRevenue": 714194.6,
   "circuitCogs": 18760,
   "totalCogs": 192414.6,
   "netAfterCogs": 521780,
   "blendedMargin": 0.7305851934472761,
   "serviceMargin": 0.7258287284094856,
   "redemptionRatio": 0.6240963855421687,
   "opexTotal": 363650,
   "operatingIncome": 158130,
   "operatingIncomeAnnual": 1897560,
   "operatingMargin": 0.22141024309060864,
   "revenueAnnual": 8570335.2,
   "injectionFloor": 555000,
   "injectionPlanning": 1110000,
   "loanFloor": 4995000,
   "loanPlanning": 4440000,
   "monthlyDebt": 71558,
   "annualDebt": 858701,
   "interestOnlyPayment": 39544,
   "dscr": 2.2098036883528778,
   "rateBand": [
    {
     "rate": 0.095,
     "monthly": 71558,
     "annual": 858701,
     "dscr": 2.2098036883528778
    },
    {
     "rate": 0.105,
     "monthly": 74232,
     "annual": 890788,
     "dscr": 2.1302032784831635
    },
    {
     "rate": 0.115,
     "monthly": 76960,
     "annual": 923521,
     "dscr": 2.0547006108611394
    }
   ],
   "founding": {
    "count": 150,
    "prepay": 3600,
    "discount": 0.33333333333333337,
    "proceeds": 540000
   },
   "capacity": {
    "operatingRoom": {
     "cases": 22,
     "theoretical": 90,
     "practical": 63,
     "demand": 38.5,
     "utilization": 0.6111111111111112,
     "headroom": 24.5
    },
    "circuit": {
     "theoretical": 6384,
     "practical": 3192,
     "demand": 2345,
     "utilization": 0.7346491228070177,
     "headroom": 847
    },
    "treatmentRooms": {
     "theoretical": 780,
     "practical": 507,
     "demand": 300,
     "utilization": 0.591715976331361,
     "headroom": 207
    }
   },
   "ramp": [
    {
     "month": 1,
     "maturity": 0,
     "open": false,
     "revenue": 0,
     "cogs": 0,
     "opex": 127277,
     "operating": -127277,
     "debtService": 19772,
     "foundingProceeds": 90000,
     "netCash": -57049,
     "cumulativeCash": -57049
    },
    {
     "month": 2,
     "maturity": 0,
     "open": false,
     "revenue": 0,
     "cogs": 0,
     "opex": 127277,
     "operating": -127277,
     "debtService": 19772,
     "foundingProceeds": 90000,
     "netCash": -57049,
     "cumulativeCash": -114099
    },
    {
     "month": 3,
     "maturity": 0,
     "open": false,
     "revenue": 0,
     "cogs": 0,
     "opex": 127277,
     "operating": -127277,
     "debtService": 19772,
     "foundingProceeds": 90000,
     "netCash": -57049,
     "cumulativeCash": -171148
    },
    {
     "month": 4,
     "maturity": 0,
     "open": false,
     "revenue": 0,
     "cogs": 0,
     "opex": 127277,
     "operating": -127277,
     "debtService": 19772,
     "foundingProceeds": 90000,
     "netCash": -57049,
     "cumulativeCash": -228197
    },
    {
     "month": 5,
     "maturity": 0,
     "open": false,
     "revenue": 0,
     "cogs": 0,
     "opex": 127277,
     "operating": -127277,
     "debtService": 19772,
     "foundingProceeds": 90000,
     "netCash": -57049,
     "cumulativeCash": -285247
    },
    {
     "month": 6,
     "maturity": 0,
     "open": false,
     "revenue": 0,
     "cogs": 0,
     "opex": 127277,
     "operating": -127277,
     "debtService": 19772,
     "foundingProceeds": 90000,
     "netCash": -57049,
     "cumulativeCash": -342296
    },
    {
     "month": 7,
     "maturity": 0.15,
     "open": true,
     "revenue": 107129,
     "cogs": 28862,
     "opex": 254555,
     "operating": -176288,
     "debtService": 39544,
     "foundingProceeds": 0,
     "netCash": -215832,
     "cumulativeCash": -558128
    },
    {
     "month": 8,
     "maturity": 0.22,
     "open": true,
     "revenue": 157123,
     "cogs": 42331,
     "opex": 254555,
     "operating": -139763,
     "debtService": 39544,
     "foundingProceeds": 0,
     "netCash": -179307,
     "cumulativeCash": -737435
    },
    {
     "month": 9,
     "maturity": 0.3,
     "open": true,
     "revenue": 214258,
     "cogs": 57724,
     "opex": 254555,
     "operating": -98021,
     "debtService": 39544,
     "foundingProceeds": 0,
     "netCash": -137565,
     "cumulativeCash": -875000
    },
    {
     "month": 10,
     "maturity": 0.36,
     "open": true,
     "revenue": 257110,
     "cogs": 69269,
     "opex": 254555,
     "operating": -66714,
     "debtService": 39544,
     "foundingProceeds": 0,
     "netCash": -106258,
     "cumulativeCash": -981258
    },
    {
     "month": 11,
     "maturity": 0.42,
     "open": true,
     "revenue": 299962,
     "cogs": 80814,
     "opex": 254555,
     "operating": -35407,
     "debtService": 39544,
     "foundingProceeds": 0,
     "netCash": -74951,
     "cumulativeCash": -1056209
    },
    {
     "month": 12,
     "maturity": 0.48,
     "open": true,
     "revenue": 342813,
     "cogs": 92359,
     "opex": 254555,
     "operating": -4101,
     "debtService": 39544,
     "foundingProceeds": 0,
     "netCash": -43644,
     "cumulativeCash": -1099853
    },
    {
     "month": 13,
     "maturity": 0.54,
     "open": true,
     "revenue": 385665,
     "cogs": 103904,
     "opex": 254555,
     "operating": 27206,
     "debtService": 39544,
     "foundingProceeds": 0,
     "netCash": -12338,
     "cumulativeCash": -1112191
    },
    {
     "month": 14,
     "maturity": 0.58,
     "open": true,
     "revenue": 414233,
     "cogs": 111600,
     "opex": 254555,
     "operating": 48077,
     "debtService": 39544,
     "foundingProceeds": 0,
     "netCash": 8534,
     "cumulativeCash": -1103657
    },
    {
     "month": 15,
     "maturity": 0.62,
     "open": true,
     "revenue": 442801,
     "cogs": 119297,
     "opex": 254555,
     "operating": 68949,
     "debtService": 39544,
     "foundingProceeds": 0,
     "netCash": 29405,
     "cumulativeCash": -1074252
    },
    {
     "month": 16,
     "maturity": 0.66,
     "open": true,
     "revenue": 471368,
     "cogs": 126994,
     "opex": 254555,
     "operating": 89820,
     "debtService": 39544,
     "foundingProceeds": 0,
     "netCash": 50276,
     "cumulativeCash": -1023976
    },
    {
     "month": 17,
     "maturity": 0.7,
     "open": true,
     "revenue": 499936,
     "cogs": 134690,
     "opex": 254555,
     "operating": 110691,
     "debtService": 39544,
     "foundingProceeds": 0,
     "netCash": 71147,
     "cumulativeCash": -952829
    },
    {
     "month": 18,
     "maturity": 0.73,
     "open": true,
     "revenue": 521362,
     "cogs": 140463,
     "opex": 265465,
     "operating": 115435,
     "debtService": 39544,
     "foundingProceeds": 0,
     "netCash": 75891,
     "cumulativeCash": -876938
    },
    {
     "month": 19,
     "maturity": 0.76,
     "open": true,
     "revenue": 542788,
     "cogs": 146235,
     "opex": 276374,
     "operating": 120179,
     "debtService": 71558,
     "foundingProceeds": 0,
     "netCash": 48620,
     "cumulativeCash": -828318
    },
    {
     "month": 20,
     "maturity": 0.79,
     "open": true,
     "revenue": 564214,
     "cogs": 152008,
     "opex": 287284,
     "operating": 124923,
     "debtService": 71558,
     "foundingProceeds": 0,
     "netCash": 53364,
     "cumulativeCash": -774953
    },
    {
     "month": 21,
     "maturity": 0.82,
     "open": true,
     "revenue": 585640,
     "cogs": 157780,
     "opex": 298193,
     "operating": 129667,
     "debtService": 71558,
     "foundingProceeds": 0,
     "netCash": 58108,
     "cumulativeCash": -716845
    },
    {
     "month": 22,
     "maturity": 0.85,
     "open": true,
     "revenue": 607065,
     "cogs": 163552,
     "opex": 309103,
     "operating": 134410,
     "debtService": 71558,
     "foundingProceeds": 0,
     "netCash": 62852,
     "cumulativeCash": -653993
    },
    {
     "month": 23,
     "maturity": 0.87,
     "open": true,
     "revenue": 621349,
     "cogs": 167401,
     "opex": 316376,
     "operating": 137573,
     "debtService": 71558,
     "foundingProceeds": 0,
     "netCash": 66015,
     "cumulativeCash": -587978
    },
    {
     "month": 24,
     "maturity": 0.89,
     "open": true,
     "revenue": 635633,
     "cogs": 171249,
     "opex": 323649,
     "operating": 140736,
     "debtService": 71558,
     "foundingProceeds": 0,
     "netCash": 69177,
     "cumulativeCash": -518801
    },
    {
     "month": 25,
     "maturity": 0.91,
     "open": true,
     "revenue": 649917,
     "cogs": 175097,
     "opex": 330922,
     "operating": 143898,
     "debtService": 71558,
     "foundingProceeds": 0,
     "netCash": 72340,
     "cumulativeCash": -446461
    },
    {
     "month": 26,
     "maturity": 0.93,
     "open": true,
     "revenue": 664201,
     "cogs": 178946,
     "opex": 338195,
     "operating": 147061,
     "debtService": 71558,
     "foundingProceeds": 0,
     "netCash": 75503,
     "cumulativeCash": -370958
    },
    {
     "month": 27,
     "maturity": 0.94,
     "open": true,
     "revenue": 671343,
     "cogs": 180870,
     "opex": 341831,
     "operating": 148642,
     "debtService": 71558,
     "foundingProceeds": 0,
     "netCash": 77084,
     "cumulativeCash": -293875
    },
    {
     "month": 28,
     "maturity": 0.96,
     "open": true,
     "revenue": 685627,
     "cogs": 184718,
     "opex": 349104,
     "operating": 151805,
     "debtService": 71558,
     "foundingProceeds": 0,
     "netCash": 80246,
     "cumulativeCash": -213628
    },
    {
     "month": 29,
     "maturity": 0.97,
     "open": true,
     "revenue": 692769,
     "cogs": 186642,
     "opex": 352741,
     "operating": 153386,
     "debtService": 71558,
     "foundingProceeds": 0,
     "netCash": 81828,
     "cumulativeCash": -131801
    },
    {
     "month": 30,
     "maturity": 0.98,
     "open": true,
     "revenue": 699911,
     "cogs": 188566,
     "opex": 356377,
     "operating": 154967,
     "debtService": 71558,
     "foundingProceeds": 0,
     "netCash": 83409,
     "cumulativeCash": -48392
    },
    {
     "month": 31,
     "maturity": 0.99,
     "open": true,
     "revenue": 707053,
     "cogs": 190490,
     "opex": 360014,
     "operating": 156549,
     "debtService": 71558,
     "foundingProceeds": 0,
     "netCash": 84990,
     "cumulativeCash": 36599
    },
    {
     "month": 32,
     "maturity": 1,
     "open": true,
     "revenue": 714195,
     "cogs": 192415,
     "opex": 363650,
     "operating": 158130,
     "debtService": 71558,
     "foundingProceeds": 0,
     "netCash": 86572,
     "cumulativeCash": 123170
    },
    {
     "month": 33,
     "maturity": 1,
     "open": true,
     "revenue": 714195,
     "cogs": 192415,
     "opex": 363650,
     "operating": 158130,
     "debtService": 71558,
     "foundingProceeds": 0,
     "netCash": 86572,
     "cumulativeCash": 209742
    },
    {
     "month": 34,
     "maturity": 1,
     "open": true,
     "revenue": 714195,
     "cogs": 192415,
     "opex": 363650,
     "operating": 158130,
     "debtService": 71558,
     "foundingProceeds": 0,
     "netCash": 86572,
     "cumulativeCash": 296314
    },
    {
     "month": 35,
     "maturity": 1,
     "open": true,
     "revenue": 714195,
     "cogs": 192415,
     "opex": 363650,
     "operating": 158130,
     "debtService": 71558,
     "foundingProceeds": 0,
     "netCash": 86572,
     "cumulativeCash": 382885
    },
    {
     "month": 36,
     "maturity": 1,
     "open": true,
     "revenue": 714195,
     "cogs": 192415,
     "opex": 363650,
     "operating": 158130,
     "debtService": 71558,
     "foundingProceeds": 0,
     "netCash": 86572,
     "cumulativeCash": 469457
    }
   ],
   "breakeven": 13,
   "dscrByYear": [
    {
     "year": 1,
     "operating": -1283956,
     "debt": 355896,
     "dscr": -3.6076719041517746,
     "passes": false
    },
    {
     "year": 2,
     "operating": 1247666,
     "debt": 666612,
     "dscr": 1.8716524755029913,
     "passes": true
    },
    {
     "year": 3,
     "operating": 1846958,
     "debt": 858696,
     "dscr": 2.1508869262230172,
     "passes": true
    }
   ],
   "band": [
    {
     "label": "Low",
     "tag": "Slow member ramp, 72% of base volume",
     "revenue": 514220,
     "netAfterCogs": 375682,
     "operating": 12032,
     "annual": 144379,
     "dscr": 0.16813675540147235
    },
    {
     "label": "Base",
     "tag": "Stated assumptions at stabilization",
     "revenue": 714195,
     "netAfterCogs": 521780,
     "operating": 158130,
     "annual": 1897560,
     "dscr": 2.209802946543675
    },
    {
     "label": "Upside",
     "tag": "Waitlist demand, 128% of base volume",
     "revenue": 914169,
     "netAfterCogs": 667878,
     "operating": 304228,
     "annual": 3650741,
     "dscr": 4.251469137685875
    }
   ],
   "trough": {
    "month": 13,
    "amount": -1112191
   },
   "reserve": 1207000,
   "rateStressPasses": true,
   "rateStress": {
    "rate": 0.115,
    "monthly": 76960,
    "annual": 923521,
    "dscr": 2.0547006108611394
   }
  }
 }
};
