/* GENERATED by deck-build/build-sites.js, do not edit by hand. */
window.LK = {
 "generated": "2026-08-20",
 "scenario": "surgical",
 "selectable": [
  "surgical"
 ],
 "assumptions": {
  "redeemsPerMonth": {
   "resident": 270,
   "longevity": 875
  },
  "blendedMemberDiscount": 0.08,
  "circuitVisitsPerMonth": {
   "resident": 5,
   "longevity": 8,
   "dayPass": 1
  },
  "circuitCostPerVisit": 8,
  "clubHoursPerDay": 14,
  "daysPerMonth": 30.4,
  "clinicalHoursPerDay": 10,
  "clinicalDaysPerMonth": 26,
  "circuitPracticalUtilization": 0.5,
  "treatmentRoomUtilization": 0.65,
  "plungeThroughputPerHour": 7.5,
  "procedureHoursEach": 1,
  "redLightSessionHours": 0.5,
  "orBlockDaysPerMonth": 9,
  "orHoursPerDay": 10,
  "orUtilization": 0.7,
  "orHoursPerCase": 1.75,
  "primeRate": 0.0675,
  "sbaMaxSpread": 0.0275,
  "loanTermMonths": 120,
  "interestOnlyMonths": 18,
  "constructionMonths": 6,
  "avgConstructionDraw": 0.5,
  "equityInjectionFloor": 0.1,
  "equityInjectionPlanning": 0.2,
  "dscrThreshold": 1.25,
  "foundingPrepay": 3600,
  "foundingListPrice": 5400,
  "sbaRate": 0.095
 },
 "tiers": [
  {
   "id": "daypass",
   "name": "Day Pass",
   "cadence": "per visit",
   "price": 75,
   "blurb": "One visit to the recovery circuit. Book any procedure at list price.",
   "includes": [
    "Single circuit visit",
    "Procedures at list price",
    "No events or lounge privileges"
   ],
   "counts": {
    "lean": 190,
    "ample": 275,
    "surgical": 275
   },
   "isMembership": false
  },
  {
   "id": "friends",
   "name": "Friends of L&K",
   "cadence": "per year",
   "price": 300,
   "blurb": "The on-ramp. Member pricing without club access.",
   "includes": [
    "Member pricing on all procedures",
    "Priority booking window",
    "Invitations to open events",
    "No club or circuit access"
   ],
   "counts": {
    "lean": 750,
    "ample": 900,
    "surgical": 900
   },
   "isMembership": true,
   "monthly": 25,
   "usesCircuit": false
  },
  {
   "id": "resident",
   "name": "Resident",
   "cadence": "per month",
   "price": 450,
   "blurb": "The core membership. Where the club actually lives.",
   "includes": [
    "Rolling monthly credit bank",
    "Unlimited recovery circuit",
    "Member pricing on all procedures",
    "1 guest pass per month",
    "Member events"
   ],
   "counts": {
    "lean": 300,
    "ample": 350,
    "surgical": 350
   },
   "isMembership": true,
   "monthly": 450,
   "usesCircuit": true,
   "capped": true
  },
  {
   "id": "longevity",
   "name": "Longevity",
   "cadence": "per month",
   "price": 1250,
   "blurb": "Physician-delivered. Hard capped.",
   "includes": [
    "Everything in Resident",
    "Quarterly physician consult",
    "Annual biomarker panel, DEXA and DUTCH",
    "Therapeutic medications included",
    "4 guest passes per month",
    "Private buyout privileges"
   ],
   "counts": {
    "lean": 32,
    "ample": 40,
    "surgical": 40
   },
   "isMembership": true,
   "monthly": 1250,
   "usesCircuit": true,
   "capped": true
  }
 ],
 "surgicalMenu": {
  "or": [
   "Blepharoplasty, upper, lower and combined",
   "Brow lift",
   "Otoplasty",
   "Chin augmentation and implant",
   "Buccal fat removal",
   "Facial fat grafting and transfer",
   "Liposuction, single or limited area, awake tumescent",
   "Submental neck contouring",
   "Limited body-contouring revision",
   "Scar revision, facial and body",
   "Nasal valve procedures sold as elective self-pay"
  ],
  "treatment": [
   "Lipoma removal",
   "Cyst removal",
   "Benign lesion removal",
   "Ablative laser resurfacing",
   "Skin tightening",
   "Hair restoration surgery and transplant"
  ],
  "excluded": [
   [
    "Breast augmentation, lift, implant exchange or removal",
    "General anesthesia in standard practice"
   ],
   [
    "Facelift and neck lift",
    "General anesthesia; recovery well beyond two hours"
   ],
   [
    "Cosmetic and revision rhinoplasty",
    "Airway risk from pharyngeal blood; general anesthesia standard"
   ],
   [
    "Mini and full abdominoplasty",
    "General anesthesia; extended recovery and caregiver discharge"
   ]
  ]
 },
 "market": [
  {
   "id": "wellness-economy",
   "value": "$6.8T",
   "label": "Global wellness economy, 2024",
   "note": "Grew 7.9% from 2023 to 2024 and has doubled in size since 2013.",
   "source": "Global Wellness Institute",
   "url": "https://globalwellnessinstitute.org/press-room/statistics-and-facts/"
  },
  {
   "id": "medspa-global",
   "value": "$27.8B",
   "label": "Global medical spa market, 2026",
   "note": "Up from $24.2B in 2025, projected to $78.2B by 2033 at a 15.9% CAGR. North America holds 41.2% of it, roughly $10B.",
   "source": "Grand View Research",
   "url": "https://www.grandviewresearch.com/industry-analysis/medical-spa-market"
  },
  {
   "id": "medspa-count",
   "value": "10,488",
   "label": "US medical spas, 2023",
   "note": "Up from 8,899 in 2022. The category is being built out right now, which is both the opportunity and the reason to differentiate.",
   "source": "Grand View Research",
   "url": "https://www.grandviewresearch.com/industry-analysis/medical-spa-market"
  },
  {
   "id": "consumer-priority",
   "value": "82%",
   "label": "US consumers calling wellness a top or important priority",
   "note": "The US consumer wellness market runs near $480B and is growing up to 10% a year.",
   "source": "McKinsey",
   "url": "https://patientfy.ai/blog/longevity-medicine-market-2026"
  },
  {
   "id": "concierge",
   "value": "$19.4B",
   "label": "US concierge medicine market by 2034",
   "note": "From about $8B in 2025. Longevity services are overwhelmingly elective, cash-pay, and increasingly sold through membership and concierge structures.",
   "source": "Cited in Patientfy longevity market map",
   "url": "https://patientfy.ai/blog/longevity-medicine-market-2026"
  },
  {
   "id": "glp1",
   "value": "1 in 8",
   "label": "US adults currently taking a GLP-1",
   "note": "For a hormone and longevity practice this is a front door, not a fad line item.",
   "source": "KFF",
   "url": "https://patientfy.ai/blog/longevity-medicine-market-2026"
  },
  {
   "id": "longevity-retreats",
   "value": "$11.1B",
   "label": "Longevity retreats market, 2026",
   "note": "From $9.82B in 2025, projected to $17.8B at a 12.6% CAGR.",
   "source": "Research and Markets",
   "url": "https://www.researchandmarkets.com/reports/6226679/longevity-retreats-market-report"
  }
 ],
 "catchment": [
  {
   "id": "income",
   "value": "$129,942",
   "label": "Playa Vista median household income",
   "note": "Against a Los Angeles County median well below it. This is a cash-pay market.",
   "source": "US Census Bureau, via Point2Homes",
   "url": "https://www.point2homes.com/US/Neighborhood/CA/Los-Angeles/Playa-Vista-Demographics.html"
  },
  {
   "id": "tech-companies",
   "value": "500+",
   "label": "Technology companies in Silicon Beach",
   "note": "The Westside tech corridor that Playa Vista sits at the center of.",
   "source": "Wikipedia, Silicon Beach",
   "url": "https://en.wikipedia.org/wiki/Silicon_Beach"
  },
  {
   "id": "campus-jobs",
   "value": "~5,100",
   "label": "Employed at The Campus at Playa Vista",
   "note": "Up from roughly 2,000 in 2015, a 150% increase. A dense, high-income daytime population inside walking distance.",
   "source": "Los Angeles Business Journal",
   "url": "https://labusinessjournal.com/real-estate/workers-silicon-beach-find-coast-costly/"
  }
 ],
 "geography": [
  "Playa Vista",
  "Marina del Rey",
  "Culver City",
  "Venice",
  "Santa Monica",
  "Playa del Rey",
  "El Segundo",
  "Westchester",
  "Mar Vista",
  "Manhattan Beach"
 ],
 "location": {
  "heading": "Silicon Beach, at its densest.",
  "lead": [
   {
    "t": "Playa Vista is a master-planned innovation district on the old Hughes Aircraft site, and it has become the centre of gravity for the Westside’s technology, media, advertising and creator economy. "
   },
   {
    "t": "Google, YouTube and Meta campuses sit within a walk of one another.",
    "em": true
   },
   {
    "t": " LAX is four miles south, the studios fifteen minutes north, and the district was designed to be walked rather than driven."
   }
  ],
  "intro": "The result is a patient market most operators can only describe aspirationally: high-earning, health-literate, time-poor, and already paying cash for injectables, recovery and labs.",
  "close": [
   {
    "t": "Just not in one building.",
    "rose": true
   },
   {
    "t": " Today that is four addresses, four intakes and four bills. The facility that collapses them into one is what this capital builds, and it is being built where those people already are."
   }
  ],
  "source": "Playa Vista district detail verified by the operator, August 2026. The three figures above carry their own sources."
 },
 "copy": {
  "offering": {
   "eyebrow": "The offering",
   "lead": "The information architecture borrows from how a health club organizes itself rather than how a clinic does. Patients do not shop by billing code; they arrive wanting to feel a specific way.",
   "verbs": [
    [
     "Restore",
     "Regenerative",
     "Six PRP protocols, therapeutic medications, a ten-drip infusion menu and NAD+ by dose."
    ],
    [
     "Renew",
     "Aesthetics",
     "Neuromodulators and filler, RF microneedling, laser resurfacing."
    ],
    [
     "Recover",
     "Recovery",
     "Hyperbaric oxygen, Ammortal chambers, robotic massage, compression, red light."
    ],
    [
     "Reset",
     "Diagnostics",
     "Advanced biometrics, DEXA, DUTCH, DNA analysis. The baseline everything else is measured against."
    ],
    [
     "Reconnect",
     "The Club",
     "The contrast suite, the Lounge, member events, and guest privileges. The reason your membership becomes part of your routine, not just your recovery."
    ]
   ]
  },
  "funnel": {
   "eyebrow": "How the ladder fills",
   "title": "The open clinic is the top of the funnel.",
   "lead": "Because anyone can book a procedure without joining, every non-member treatment is a paid introduction. The conversion path runs in one direction and each step is cheap to take.",
   "steps": [
    {
     "pill": "Step one",
     "title": "Walks in",
     "body": "Books a procedure. Pays list price. Owes nothing further.",
     "bodyDayPass": "Books a procedure or buys a day pass. Pays list price. Owes nothing further."
    },
    {
     "pill": "Step two",
     "title": "Becomes a Friend",
     "body": "$300 a year pays for itself on roughly two procedures. Low friction, high volume, and it captures the database."
    },
    {
     "pill": "Step three",
     "title": "Becomes a Resident",
     "body": "Wants the circuit and the room, not just the treatment. This is where recurring revenue begins."
    },
    {
     "pill": "Step four",
     "title": "Becomes Longevity",
     "accent": true,
     "body": "Physician-delivered programming. Hard capped. The highest retention and the highest lifetime value in the building."
    }
   ]
  }
 },
 "scenarios": {
  "lean": {
   "key": "lean",
   "label": "Lean",
   "menu": "legacy",
   "projectCost": 3500000,
   "sqft": 4500,
   "tagline": "Leased equipment, tighter footprint, fastest path to positive cash flow.",
   "equipmentStrategy": "Leased",
   "stations": {
    "treatment": 2,
    "ivchair": 6,
    "sauna": 1,
    "plunge": 2,
    "aescape": 1,
    "ammortal": 1,
    "hbot": 1,
    "diagnostic": 1,
    "recovery": 3
   },
   "foundingMembers": 100,
   "space": [
    [
     "Arrival, concierge, retail",
     300
    ],
    [
     "The Lounge",
     600
    ],
    [
     "Contrast suite (1 sauna, 2 plunges)",
     420
    ],
    [
     "Recovery floor",
     700
    ],
    [
     "IV and regenerative lounge (6 chairs)",
     560
    ],
    [
     "Treatment rooms (2)",
     400
    ],
    [
     "Diagnostics and consult",
     350
    ],
    [
     "Locker, shower, changing",
     330
    ],
    [
     "Staff, MEP, storage, circulation",
     840
    ]
   ],
   "opex": {
    "Rent (4,500 SF NNN)": 24750,
    "Clinical and club staff": 88000,
    "Admin and management": 22000,
    "Marketing and member acquisition": 20000,
    "Malpractice and liability": 10000,
    "Equipment leases": 34000,
    "Utilities, software, member platform": 13000,
    "Licensing and compliance": 5000
   },
   "useOfFunds": [
    [
     "Buildout and tenant improvements (4,500 SF @ ~$210/SF)",
     945000
    ],
    [
     "Wet areas: sauna, plunges, drainage, ventilation",
     285000
    ],
    [
     "Equipment lease deposits and financed upfront",
     382000
    ],
    [
     "FF&E, lounge, millwork, retail",
     395000
    ],
    [
     "Pre-opening: licensing, legal, insurance, hiring",
     265000
    ],
    [
     "Brand, launch, founding member campaign",
     190000
    ],
    [
     "Working capital and debt service reserve",
     1038000
    ]
   ],
   "lines": [
    {
     "id": "aescape",
     "name": "Aescape Robotic Massage",
     "cat": "Recovery",
     "margin": 0.82,
     "lo": 60,
     "hi": 80,
     "room": "aescape",
     "sessions": 110,
     "price": 70,
     "gross": 7700,
     "cogs": 1386.0000000000005,
     "net": 6314
    },
    {
     "id": "ammortal",
     "name": "Ammortal Chamber",
     "cat": "Recovery",
     "margin": 0.82,
     "lo": 90,
     "hi": 150,
     "room": "ammortal",
     "sessions": 70,
     "price": 120,
     "gross": 8400,
     "cogs": 1512.0000000000005,
     "net": 6888
    },
    {
     "id": "redlight",
     "name": "Red Light Therapy",
     "cat": "Recovery",
     "margin": 0.82,
     "lo": 50,
     "hi": 100,
     "room": "recovery",
     "sessions": 50,
     "price": 75,
     "gross": 3750,
     "cogs": 675.0000000000002,
     "net": 3075
    },
    {
     "id": "hbot",
     "name": "Hyperbaric Oxygen",
     "cat": "Recovery",
     "margin": 0.8,
     "lo": 150,
     "hi": 250,
     "room": "hbot",
     "sessions": 55,
     "price": 200,
     "gross": 11000,
     "cogs": 2199.9999999999995,
     "net": 8800
    },
    {
     "id": "prp",
     "name": "PRP Injections",
     "cat": "Regenerative",
     "margin": 0.78,
     "lo": 800,
     "hi": 1500,
     "room": "treatment",
     "sessions": 36,
     "price": 1150,
     "gross": 41400,
     "cogs": 9107.999999999998,
     "net": 32292
    },
    {
     "id": "compress",
     "name": "Compression / NeuFit",
     "cat": "Recovery",
     "margin": 0.78,
     "lo": 75,
     "hi": 150,
     "room": "recovery",
     "sessions": 50,
     "price": 113,
     "gross": 5650,
     "cogs": 1242.9999999999998,
     "net": 4407
    },
    {
     "id": "hormone",
     "name": "Hormone / Peptide / GLP",
     "cat": "Regenerative",
     "margin": 0.75,
     "lo": 400,
     "hi": 800,
     "room": "treatment",
     "sessions": 30,
     "price": 600,
     "gross": 18000,
     "cogs": 4500,
     "net": 13500
    },
    {
     "id": "iv",
     "name": "IV Therapy (NAD+ / Drips)",
     "cat": "Regenerative",
     "margin": 0.72,
     "lo": 350,
     "hi": 1000,
     "room": "ivchair",
     "sessions": 85,
     "price": 675,
     "gross": 57375,
     "cogs": 16065.000000000002,
     "net": 41310
    },
    {
     "id": "botox",
     "name": "Botox & Fillers",
     "cat": "Aesthetics",
     "margin": 0.7,
     "lo": 500,
     "hi": 950,
     "room": "treatment",
     "sessions": 58,
     "price": 725,
     "gross": 42050,
     "cogs": 12615.000000000002,
     "net": 29434.999999999996
    },
    {
     "id": "laser",
     "name": "Laser Platform",
     "cat": "Aesthetics",
     "margin": 0.7,
     "lo": 500,
     "hi": 1200,
     "room": "treatment",
     "sessions": 20,
     "price": 850,
     "gross": 17000,
     "cogs": 5100.000000000001,
     "net": 11900
    },
    {
     "id": "biometric",
     "name": "Advanced Biometrics",
     "cat": "Diagnostics",
     "margin": 0.7,
     "lo": 150,
     "hi": 300,
     "room": "diagnostic",
     "sessions": 14,
     "price": 225,
     "gross": 3150,
     "cogs": 945.0000000000001,
     "net": 2205
    },
    {
     "id": "morpheus",
     "name": "Morpheus8 RF Microneedling",
     "cat": "Aesthetics",
     "margin": 0.68,
     "lo": 835,
     "hi": 1500,
     "room": "treatment",
     "sessions": 20,
     "price": 1168,
     "gross": 23360,
     "cogs": 7475.199999999999,
     "net": 15884.800000000001
    },
    {
     "id": "dna",
     "name": "DNA Analysis",
     "cat": "Diagnostics",
     "margin": 0.67,
     "lo": 300,
     "hi": 500,
     "room": "diagnostic",
     "sessions": 11,
     "price": 400,
     "gross": 4400,
     "cogs": 1451.9999999999998,
     "net": 2948
    },
    {
     "id": "emsculpt",
     "name": "Emsculpt",
     "cat": "Aesthetics",
     "margin": 0.67,
     "lo": 750,
     "hi": 1200,
     "room": "treatment",
     "sessions": 20,
     "price": 975,
     "gross": 19500,
     "cogs": 6434.999999999999,
     "net": 13065
    },
    {
     "id": "dutch",
     "name": "DUTCH Testing",
     "cat": "Diagnostics",
     "margin": 0.65,
     "lo": 400,
     "hi": 650,
     "room": "diagnostic",
     "sessions": 14,
     "price": 525,
     "gross": 7350,
     "cogs": 2572.5,
     "net": 4777.5
    },
    {
     "id": "coolsculpt",
     "name": "CoolSculpting",
     "cat": "Aesthetics",
     "margin": 0.65,
     "lo": 700,
     "hi": 1200,
     "room": "treatment",
     "sessions": 14,
     "price": 950,
     "gross": 13300,
     "cogs": 4655,
     "net": 8645
    },
    {
     "id": "dexa",
     "name": "DEXA Scan",
     "cat": "Diagnostics",
     "margin": 0.62,
     "lo": 200,
     "hi": 350,
     "room": "diagnostic",
     "sessions": 14,
     "price": 275,
     "gross": 3850,
     "cogs": 1463,
     "net": 2387
    }
   ],
   "rackValue": 287235,
   "serviceCogs": 79401.7,
   "redeemed": 109000,
   "alaCarteGross": 178235,
   "memberDiscount": 14258.800000000001,
   "alaCarteNet": 163976.2,
   "membershipLines": [
    {
     "id": "friends",
     "name": "Friends of L&K",
     "count": 750,
     "monthly": 18750
    },
    {
     "id": "resident",
     "name": "Resident",
     "count": 300,
     "monthly": 135000
    },
    {
     "id": "longevity",
     "name": "Longevity",
     "count": 32,
     "monthly": 40000
    }
   ],
   "membershipRevenue": 193750,
   "accessRevenue": 14250,
   "totalRevenue": 371976.2,
   "circuitCogs": 15568,
   "totalCogs": 94969.7,
   "netAfterCogs": 277006.5,
   "blendedMargin": 0.744688773098924,
   "serviceMargin": 0.7235653733006074,
   "redemptionRatio": 0.6228571428571429,
   "opexTotal": 216750,
   "operatingIncome": 60256.5,
   "operatingIncomeAnnual": 723078,
   "operatingMargin": 0.16199020259898347,
   "revenueAnnual": 4463714.4,
   "injectionFloor": 350000,
   "injectionPlanning": 700000,
   "loanFloor": 3150000,
   "loanPlanning": 2800000,
   "isPrivate": false,
   "allEquity": false,
   "injectionPct": 0.1,
   "monthlyDebt": 45127,
   "annualDebt": 541523,
   "interestOnlyPayment": 24938,
   "dscr": 1.3352674553616015,
   "unleveredYield": 0.2065937142857143,
   "rateBand": [
    {
     "rate": 0.095,
     "monthly": 45127,
     "annual": 541523,
     "dscr": 1.3352674553616015
    },
    {
     "rate": 0.105,
     "monthly": 46813,
     "annual": 561758,
     "dscr": 1.2871691390755529
    },
    {
     "rate": 0.115,
     "monthly": 48533,
     "annual": 582401,
     "dscr": 1.241546871631598
    }
   ],
   "founding": {
    "count": 100,
    "prepay": 3600,
    "discount": 0.33333333333333337,
    "proceeds": 360000
   },
   "capacity": {
    "operatingRoom": null,
    "circuit": {
     "theoretical": 6384,
     "practical": 3192,
     "demand": 1946,
     "utilization": 0.6096491228070177,
     "headroom": 1246
    },
    "treatmentRooms": {
     "theoretical": 520,
     "practical": 338,
     "demand": 198,
     "utilization": 0.5857988165680473,
     "headroom": 140
    },
    "redLight": null
   },
   "ramp": [
    {
     "month": 1,
     "maturity": 0,
     "open": false,
     "revenue": 0,
     "cogs": 0,
     "opex": 75863,
     "operating": -75862,
     "debtService": 12469,
     "foundingProceeds": 60000,
     "netCash": -28331,
     "cumulativeCash": -28331
    },
    {
     "month": 2,
     "maturity": 0,
     "open": false,
     "revenue": 0,
     "cogs": 0,
     "opex": 75863,
     "operating": -75862,
     "debtService": 12469,
     "foundingProceeds": 60000,
     "netCash": -28331,
     "cumulativeCash": -56662
    },
    {
     "month": 3,
     "maturity": 0,
     "open": false,
     "revenue": 0,
     "cogs": 0,
     "opex": 75863,
     "operating": -75862,
     "debtService": 12469,
     "foundingProceeds": 60000,
     "netCash": -28331,
     "cumulativeCash": -84994
    },
    {
     "month": 4,
     "maturity": 0,
     "open": false,
     "revenue": 0,
     "cogs": 0,
     "opex": 75863,
     "operating": -75862,
     "debtService": 12469,
     "foundingProceeds": 60000,
     "netCash": -28331,
     "cumulativeCash": -113325
    },
    {
     "month": 5,
     "maturity": 0,
     "open": false,
     "revenue": 0,
     "cogs": 0,
     "opex": 75863,
     "operating": -75862,
     "debtService": 12469,
     "foundingProceeds": 60000,
     "netCash": -28331,
     "cumulativeCash": -141656
    },
    {
     "month": 6,
     "maturity": 0,
     "open": false,
     "revenue": 0,
     "cogs": 0,
     "opex": 75863,
     "operating": -75862,
     "debtService": 12469,
     "foundingProceeds": 60000,
     "netCash": -28331,
     "cumulativeCash": -169987
    },
    {
     "month": 7,
     "maturity": 0.15,
     "open": true,
     "revenue": 55796,
     "cogs": 14245,
     "opex": 151725,
     "operating": -110174,
     "debtService": 24938,
     "foundingProceeds": 0,
     "netCash": -135112,
     "cumulativeCash": -305099
    },
    {
     "month": 8,
     "maturity": 0.22,
     "open": true,
     "revenue": 81835,
     "cogs": 20893,
     "opex": 151725,
     "operating": -90784,
     "debtService": 24938,
     "foundingProceeds": 0,
     "netCash": -115721,
     "cumulativeCash": -420820
    },
    {
     "month": 9,
     "maturity": 0.3,
     "open": true,
     "revenue": 111593,
     "cogs": 28491,
     "opex": 151725,
     "operating": -68623,
     "debtService": 24938,
     "foundingProceeds": 0,
     "netCash": -93561,
     "cumulativeCash": -514381
    },
    {
     "month": 10,
     "maturity": 0.36,
     "open": true,
     "revenue": 133911,
     "cogs": 34189,
     "opex": 151725,
     "operating": -52003,
     "debtService": 24938,
     "foundingProceeds": 0,
     "netCash": -76940,
     "cumulativeCash": -591321
    },
    {
     "month": 11,
     "maturity": 0.42,
     "open": true,
     "revenue": 156230,
     "cogs": 39887,
     "opex": 151725,
     "operating": -35382,
     "debtService": 24938,
     "foundingProceeds": 0,
     "netCash": -60320,
     "cumulativeCash": -651641
    },
    {
     "month": 12,
     "maturity": 0.48,
     "open": true,
     "revenue": 178549,
     "cogs": 45585,
     "opex": 151725,
     "operating": -18762,
     "debtService": 24938,
     "foundingProceeds": 0,
     "netCash": -43699,
     "cumulativeCash": -695340
    },
    {
     "month": 13,
     "maturity": 0.54,
     "open": true,
     "revenue": 200867,
     "cogs": 51284,
     "opex": 151725,
     "operating": -2141,
     "debtService": 24938,
     "foundingProceeds": 0,
     "netCash": -27079,
     "cumulativeCash": -722419
    },
    {
     "month": 14,
     "maturity": 0.58,
     "open": true,
     "revenue": 215746,
     "cogs": 55082,
     "opex": 151725,
     "operating": 8939,
     "debtService": 24938,
     "foundingProceeds": 0,
     "netCash": -15999,
     "cumulativeCash": -738418
    },
    {
     "month": 15,
     "maturity": 0.62,
     "open": true,
     "revenue": 230625,
     "cogs": 58881,
     "opex": 151725,
     "operating": 20019,
     "debtService": 24938,
     "foundingProceeds": 0,
     "netCash": -4918,
     "cumulativeCash": -743336
    },
    {
     "month": 16,
     "maturity": 0.66,
     "open": true,
     "revenue": 245504,
     "cogs": 62680,
     "opex": 151725,
     "operating": 31099,
     "debtService": 24938,
     "foundingProceeds": 0,
     "netCash": 6162,
     "cumulativeCash": -737174
    },
    {
     "month": 17,
     "maturity": 0.7,
     "open": true,
     "revenue": 260383,
     "cogs": 66479,
     "opex": 151725,
     "operating": 42180,
     "debtService": 24938,
     "foundingProceeds": 0,
     "netCash": 17242,
     "cumulativeCash": -719932
    },
    {
     "month": 18,
     "maturity": 0.73,
     "open": true,
     "revenue": 271543,
     "cogs": 69328,
     "opex": 158228,
     "operating": 43987,
     "debtService": 24938,
     "foundingProceeds": 0,
     "netCash": 19050,
     "cumulativeCash": -700883
    },
    {
     "month": 19,
     "maturity": 0.76,
     "open": true,
     "revenue": 282702,
     "cogs": 72177,
     "opex": 164730,
     "operating": 45795,
     "debtService": 45127,
     "foundingProceeds": 0,
     "netCash": 668,
     "cumulativeCash": -700215
    },
    {
     "month": 20,
     "maturity": 0.79,
     "open": true,
     "revenue": 293861,
     "cogs": 75026,
     "opex": 171233,
     "operating": 47603,
     "debtService": 45127,
     "foundingProceeds": 0,
     "netCash": 2476,
     "cumulativeCash": -697739
    },
    {
     "month": 21,
     "maturity": 0.82,
     "open": true,
     "revenue": 305020,
     "cogs": 77875,
     "opex": 177735,
     "operating": 49410,
     "debtService": 45127,
     "foundingProceeds": 0,
     "netCash": 4283,
     "cumulativeCash": -693455
    },
    {
     "month": 22,
     "maturity": 0.85,
     "open": true,
     "revenue": 316180,
     "cogs": 80724,
     "opex": 184238,
     "operating": 51218,
     "debtService": 45127,
     "foundingProceeds": 0,
     "netCash": 6091,
     "cumulativeCash": -687364
    },
    {
     "month": 23,
     "maturity": 0.87,
     "open": true,
     "revenue": 323619,
     "cogs": 82624,
     "opex": 188573,
     "operating": 52423,
     "debtService": 45127,
     "foundingProceeds": 0,
     "netCash": 7296,
     "cumulativeCash": -680068
    },
    {
     "month": 24,
     "maturity": 0.89,
     "open": true,
     "revenue": 331059,
     "cogs": 84523,
     "opex": 192908,
     "operating": 53628,
     "debtService": 45127,
     "foundingProceeds": 0,
     "netCash": 8501,
     "cumulativeCash": -671567
    },
    {
     "month": 25,
     "maturity": 0.91,
     "open": true,
     "revenue": 338498,
     "cogs": 86422,
     "opex": 197243,
     "operating": 54833,
     "debtService": 45127,
     "foundingProceeds": 0,
     "netCash": 9707,
     "cumulativeCash": -661860
    },
    {
     "month": 26,
     "maturity": 0.93,
     "open": true,
     "revenue": 345938,
     "cogs": 88322,
     "opex": 201578,
     "operating": 56039,
     "debtService": 45127,
     "foundingProceeds": 0,
     "netCash": 10912,
     "cumulativeCash": -650949
    },
    {
     "month": 27,
     "maturity": 0.94,
     "open": true,
     "revenue": 349658,
     "cogs": 89272,
     "opex": 203745,
     "operating": 56641,
     "debtService": 45127,
     "foundingProceeds": 0,
     "netCash": 11514,
     "cumulativeCash": -639434
    },
    {
     "month": 28,
     "maturity": 0.96,
     "open": true,
     "revenue": 357097,
     "cogs": 91171,
     "opex": 208080,
     "operating": 57846,
     "debtService": 45127,
     "foundingProceeds": 0,
     "netCash": 12719,
     "cumulativeCash": -626715
    },
    {
     "month": 29,
     "maturity": 0.97,
     "open": true,
     "revenue": 360817,
     "cogs": 92121,
     "opex": 210248,
     "operating": 58449,
     "debtService": 45127,
     "foundingProceeds": 0,
     "netCash": 13322,
     "cumulativeCash": -613393
    },
    {
     "month": 30,
     "maturity": 0.98,
     "open": true,
     "revenue": 364537,
     "cogs": 93070,
     "opex": 212415,
     "operating": 59051,
     "debtService": 45127,
     "foundingProceeds": 0,
     "netCash": 13924,
     "cumulativeCash": -599469
    },
    {
     "month": 31,
     "maturity": 0.99,
     "open": true,
     "revenue": 368256,
     "cogs": 94020,
     "opex": 214583,
     "operating": 59654,
     "debtService": 45127,
     "foundingProceeds": 0,
     "netCash": 14527,
     "cumulativeCash": -584942
    },
    {
     "month": 32,
     "maturity": 1,
     "open": true,
     "revenue": 371976,
     "cogs": 94970,
     "opex": 216750,
     "operating": 60257,
     "debtService": 45127,
     "foundingProceeds": 0,
     "netCash": 15130,
     "cumulativeCash": -569812
    },
    {
     "month": 33,
     "maturity": 1,
     "open": true,
     "revenue": 371976,
     "cogs": 94970,
     "opex": 216750,
     "operating": 60257,
     "debtService": 45127,
     "foundingProceeds": 0,
     "netCash": 15130,
     "cumulativeCash": -554682
    },
    {
     "month": 34,
     "maturity": 1,
     "open": true,
     "revenue": 371976,
     "cogs": 94970,
     "opex": 216750,
     "operating": 60257,
     "debtService": 45127,
     "foundingProceeds": 0,
     "netCash": 15130,
     "cumulativeCash": -539553
    },
    {
     "month": 35,
     "maturity": 1,
     "open": true,
     "revenue": 371976,
     "cogs": 94970,
     "opex": 216750,
     "operating": 60257,
     "debtService": 45127,
     "foundingProceeds": 0,
     "netCash": 15130,
     "cumulativeCash": -524423
    },
    {
     "month": 36,
     "maturity": 1,
     "open": true,
     "revenue": 371976,
     "cogs": 94970,
     "opex": 216750,
     "operating": 60257,
     "debtService": 45127,
     "foundingProceeds": 0,
     "netCash": 15130,
     "cumulativeCash": -509294
    }
   ],
   "breakeven": 14,
   "dscrByYear": [
    {
     "year": 1,
     "operating": -830900,
     "debt": 224442,
     "dscr": -3.7020700225447998,
     "passes": false
    },
    {
     "year": 2,
     "operating": 444160,
     "debt": 420390,
     "dscr": 1.0565427341278337,
     "passes": false
    },
    {
     "year": 3,
     "operating": 703798,
     "debt": 541524,
     "dscr": 1.299661695511187,
     "passes": true
    }
   ],
   "band": [
    {
     "label": "Low",
     "tag": "Slow member ramp, 72% of base volume",
     "revenue": 267823,
     "netAfterCogs": 199445,
     "operating": -17305,
     "annual": -207664,
     "dscr": -0.3834811079123141
    },
    {
     "label": "Base",
     "tag": "Stated assumptions at stabilization",
     "revenue": 371976,
     "netAfterCogs": 277007,
     "operating": 60257,
     "annual": 723078,
     "dscr": 1.3352673847648207
    },
    {
     "label": "Upside",
     "tag": "Waitlist demand, 128% of base volume",
     "revenue": 476130,
     "netAfterCogs": 354568,
     "operating": 137818,
     "annual": 1653820,
     "dscr": 3.0540158774419557
    }
   ],
   "deal": null,
   "scope": {
    "total": 17,
    "licensed": 11,
    "openToAnyone": 6
   },
   "trough": {
    "month": 15,
    "amount": -743336
   },
   "reserve": 1038000,
   "rateStressPasses": false,
   "rateStress": {
    "rate": 0.115,
    "monthly": 48533,
    "annual": 582401,
    "dscr": 1.241546871631598
   },
   "cumulativeCash36": -509294,
   "paybackMonth": {
    "month": 83,
    "extrapolated": true
   }
  },
  "ample": {
   "key": "ample",
   "label": "Ample",
   "menu": "current",
   "projectCost": 4750000,
   "sqft": 4925,
   "tagline": "Full contrast suite, owned equipment, the facility the brand deserves.",
   "equipmentStrategy": "Purchased where payback justifies it",
   "stations": {
    "treatment": 3,
    "ivchair": 8,
    "sauna": 2,
    "plunge": 2,
    "aescape": 1,
    "ammortal": 1,
    "hbot": 1,
    "redlight": 2,
    "diagnostic": 2,
    "dexa": 1,
    "recovery": 4
   },
   "foundingMembers": 150,
   "space": [
    [
     "Arrival, concierge, retail",
     350
    ],
    [
     "The Lounge",
     700
    ],
    [
     "Contrast suite (2 saunas, 2 plunges)",
     250
    ],
    [
     "Aescape",
     120
    ],
    [
     "Ammortal chamber",
     90
    ],
    [
     "Hyperbaric room (seated)",
     120
    ],
    [
     "Red light beds (2)",
     150
    ],
    [
     "IV and regenerative lounge (8 chairs)",
     375
    ],
    [
     "Treatment rooms (3)",
     300
    ],
    [
     "Diagnostics and consult (2)",
     250
    ],
    [
     "Diagnostic imaging (GE iDXA densitometer)",
     125
    ],
    [
     "Locker, shower, changing, bathrooms",
     550
    ],
    [
     "Admin offices (2)",
     200
    ],
    [
     "Kitchen and breakroom",
     200
    ],
    [
     "Storage",
     150
    ],
    [
     "MEP",
     75
    ],
    [
     "Biohazard and linen closets",
     30
    ],
    [
     "Circulation and grossing factor",
     890
    ]
   ],
   "opex": {
    "Rent (4,925 SF NNN)": 27087.5,
    "Clinical and club staff": 85920,
    "Admin and management": 18500,
    "Marketing and member acquisition": 30000,
    "Malpractice and liability": 12000,
    "Equipment leases": 16555,
    "Utilities, software, member platform": 16000,
    "Licensing and compliance": 1610
   },
   "useOfFunds": [
    [
     "Buildout and tenant improvements (4,925 SF @ $250/SF)",
     1231250
    ],
    [
     "Wet areas: 2 saunas, 2 plunges, steam, drainage, ventilation",
     465000
    ],
    [
     "Medical and aesthetic equipment (purchased)",
     780000
    ],
    [
     "Recovery technology: HBOT purchased, Ammortal deposit",
     165950
    ],
    [
     "GE iDXA bone densitometer, purchased",
     25000
    ],
    [
     "FF&E, lounge, millwork, retail",
     430000
    ],
    [
     "Pre-opening: licensing, legal, insurance, hiring",
     310000
    ],
    [
     "Brand, launch, founding member campaign",
     237000
    ],
    [
     "Working capital and debt service reserve",
     1105800
    ]
   ],
   "lines": [
    {
     "id": "aescape",
     "name": "Aescape Robotic Massage",
     "cat": "Recovery",
     "margin": 0.82,
     "price": 70,
     "room": "aescape",
     "sessions": 200,
     "gross": 14000,
     "cogs": 2520.000000000001,
     "net": 11480
    },
    {
     "id": "ammortal",
     "name": "Ammortal Chamber",
     "cat": "Recovery",
     "margin": 0.82,
     "price": 140,
     "room": "ammortal",
     "sessions": 120,
     "gross": 16800,
     "cogs": 3024.000000000001,
     "net": 13776
    },
    {
     "id": "redlight",
     "name": "Red Light Therapy",
     "cat": "Recovery",
     "margin": 0.82,
     "price": 60,
     "room": "redlight",
     "sessions": 650,
     "gross": 39000,
     "cogs": 7020.000000000002,
     "net": 31979.999999999996
    },
    {
     "id": "hbot",
     "name": "Hyperbaric Oxygen",
     "cat": "Recovery",
     "margin": 0.8,
     "price": 200,
     "room": "hbot",
     "sessions": 50,
     "gross": 10000,
     "cogs": 1999.9999999999995,
     "net": 8000
    },
    {
     "id": "compress",
     "name": "Compression Therapy",
     "cat": "Recovery",
     "margin": 0.82,
     "price": 45,
     "room": "recovery",
     "sessions": 225,
     "gross": 10125,
     "cogs": 1822.5000000000005,
     "net": 8302.5
    },
    {
     "id": "prpHair",
     "name": "PRP: Hair & Scalp",
     "cat": "PRP",
     "margin": 0.72,
     "price": 995,
     "room": "treatment",
     "sessions": 33,
     "gross": 32835,
     "cogs": 9193.800000000001,
     "net": 23641.2
    },
    {
     "id": "prpFace",
     "name": "PRP: Face & Aesthetic",
     "cat": "PRP",
     "margin": 0.68,
     "price": 700,
     "room": "treatment",
     "sessions": 35,
     "gross": 24500,
     "cogs": 7839.999999999999,
     "net": 16660
    },
    {
     "id": "prpScar",
     "name": "PRP: Scar & Skin Repair",
     "cat": "PRP",
     "margin": 0.65,
     "price": 600,
     "room": "treatment",
     "sessions": 10,
     "gross": 6000,
     "cogs": 2100,
     "net": 3900
    },
    {
     "id": "prpSoft",
     "name": "PRP: Soft Tissue",
     "cat": "PRP",
     "margin": 0.65,
     "price": 1000,
     "room": "treatment",
     "sessions": 25,
     "gross": 25000,
     "cogs": 8750,
     "net": 16250
    },
    {
     "id": "prpJoint",
     "name": "PRP: Joint & Cartilage",
     "cat": "PRP",
     "margin": 0.62,
     "price": 1200,
     "room": "treatment",
     "sessions": 25,
     "gross": 30000,
     "cogs": 11400,
     "net": 18600
    },
    {
     "id": "prpPost",
     "name": "PRP: Post-procedure",
     "cat": "PRP",
     "margin": 0.6,
     "price": 650,
     "room": "treatment",
     "sessions": 15,
     "gross": 9750,
     "cogs": 3900,
     "net": 5850
    },
    {
     "id": "ivBasic",
     "name": "Basic Hydration",
     "cat": "Regenerative",
     "margin": 0.68,
     "price": 99,
     "room": "ivchair",
     "sessions": 71,
     "gross": 7029,
     "cogs": 2249.2799999999997,
     "net": 4779.72
    },
    {
     "id": "ivMyers",
     "name": "Myers Cocktail",
     "cat": "Regenerative",
     "margin": 0.56,
     "price": 199,
     "room": "ivchair",
     "sessions": 34,
     "gross": 6766,
     "cogs": 2977.0399999999995,
     "net": 3788.9600000000005
    },
    {
     "id": "ivRecovery",
     "name": "Recovery / Hangover",
     "cat": "Regenerative",
     "margin": 0.62,
     "price": 249,
     "room": "ivchair",
     "sessions": 34,
     "gross": 8466,
     "cogs": 3217.08,
     "net": 5248.92
    },
    {
     "id": "ivImmunity",
     "name": "Immunity / High-Dose C",
     "cat": "Regenerative",
     "margin": 0.61,
     "price": 289,
     "room": "ivchair",
     "sessions": 25,
     "gross": 7225,
     "cogs": 2817.75,
     "net": 4407.25
    },
    {
     "id": "ivBeauty",
     "name": "Beauty / Glutathione",
     "cat": "Regenerative",
     "margin": 0.66,
     "price": 165,
     "room": "ivchair",
     "sessions": 57,
     "gross": 9405,
     "cogs": 3197.7,
     "net": 6207.3
    },
    {
     "id": "ivAthletic",
     "name": "Athletic Performance",
     "cat": "Regenerative",
     "margin": 0.65,
     "price": 249,
     "room": "ivchair",
     "sessions": 40,
     "gross": 9960,
     "cogs": 3486,
     "net": 6474
    },
    {
     "id": "nad100",
     "name": "NAD+ 100mg",
     "cat": "Regenerative",
     "margin": 0.74,
     "price": 289,
     "room": "ivchair",
     "sessions": 25,
     "gross": 7225,
     "cogs": 1878.5,
     "net": 5346.5
    },
    {
     "id": "nad250",
     "name": "NAD+ 250mg",
     "cat": "Regenerative",
     "margin": 0.76,
     "price": 350,
     "room": "ivchair",
     "sessions": 33,
     "gross": 11550,
     "cogs": 2772,
     "net": 8778
    },
    {
     "id": "nad500",
     "name": "NAD+ 500mg",
     "cat": "Regenerative",
     "margin": 0.78,
     "price": 550,
     "room": "ivchair",
     "sessions": 33,
     "gross": 18150,
     "cogs": 3992.9999999999995,
     "net": 14157
    },
    {
     "id": "imShot",
     "name": "IM Shot: B12 / Lipo",
     "cat": "Regenerative",
     "margin": 0.65,
     "price": 95,
     "room": "ivchair",
     "sessions": 58,
     "gross": 5510,
     "cogs": 1928.4999999999998,
     "net": 3581.5
    },
    {
     "id": "thermeds",
     "name": "Therapeutic medications",
     "cat": "Regenerative",
     "margin": 0.75,
     "price": 300,
     "room": "treatment",
     "sessions": 60,
     "gross": 18000,
     "cogs": 4500,
     "net": 13500
    },
    {
     "id": "botox",
     "name": "Botox (15-unit minimum)",
     "cat": "Aesthetics",
     "margin": 0.7,
     "price": 240,
     "room": "treatment",
     "sessions": 80,
     "gross": 19200,
     "cogs": 5760.000000000001,
     "net": 13440
    },
    {
     "id": "filler",
     "name": "Filler (0.5 ml)",
     "cat": "Aesthetics",
     "margin": 0.65,
     "price": 850,
     "room": "treatment",
     "sessions": 56,
     "gross": 47600,
     "cogs": 16660,
     "net": 30940
    },
    {
     "id": "rfmicro",
     "name": "RF Microneedling",
     "cat": "Aesthetics",
     "margin": 0.75,
     "price": 1000,
     "room": "treatment",
     "sessions": 50,
     "gross": 50000,
     "cogs": 12500,
     "net": 37500
    },
    {
     "id": "laser",
     "name": "Laser Platform",
     "cat": "Aesthetics",
     "margin": 0.7,
     "price": 850,
     "room": "treatment",
     "sessions": 30,
     "gross": 25500,
     "cogs": 7650.000000000001,
     "net": 17850
    },
    {
     "id": "biometric",
     "name": "Advanced Biometrics",
     "cat": "Diagnostics",
     "margin": 0.7,
     "price": 225,
     "room": "diagnostic",
     "sessions": 20,
     "gross": 4500,
     "cogs": 1350.0000000000002,
     "net": 3150
    },
    {
     "id": "dna",
     "name": "DNA Analysis",
     "cat": "Diagnostics",
     "margin": 0.67,
     "price": 600,
     "room": "diagnostic",
     "sessions": 15,
     "gross": 9000,
     "cogs": 2969.9999999999995,
     "net": 6030
    },
    {
     "id": "dutch",
     "name": "DUTCH Plus Test",
     "cat": "Diagnostics",
     "margin": 0.65,
     "price": 750,
     "room": "diagnostic",
     "sessions": 20,
     "gross": 15000,
     "cogs": 5250,
     "net": 9750
    },
    {
     "id": "dexa",
     "name": "DEXA Scan",
     "cat": "Diagnostics",
     "margin": 0.77,
     "price": 95,
     "room": "diagnostic",
     "sessions": 95,
     "gross": 9025,
     "cogs": 2075.75,
     "net": 6949.25
    }
   ],
   "rackValue": 507121,
   "serviceCogs": 146802.9,
   "redeemed": 129500,
   "alaCarteGross": 377621,
   "memberDiscount": 30209.68,
   "alaCarteNet": 347411.32,
   "membershipLines": [
    {
     "id": "friends",
     "name": "Friends of L&K",
     "count": 900,
     "monthly": 22500
    },
    {
     "id": "resident",
     "name": "Resident",
     "count": 350,
     "monthly": 157500
    },
    {
     "id": "longevity",
     "name": "Longevity",
     "count": 40,
     "monthly": 50000
    }
   ],
   "membershipRevenue": 230000,
   "accessRevenue": 20625,
   "totalRevenue": 598036.3200000001,
   "circuitCogs": 18760,
   "totalCogs": 165562.9,
   "netAfterCogs": 432473.42000000004,
   "blendedMargin": 0.7231557775621387,
   "serviceMargin": 0.7105170166488866,
   "redemptionRatio": 0.6240963855421687,
   "opexTotal": 207672.5,
   "operatingIncome": 224800.92000000004,
   "operatingIncomeAnnual": 2697611.0400000005,
   "operatingMargin": 0.37589844041579284,
   "revenueAnnual": 7176435.840000001,
   "injectionFloor": 475000,
   "injectionPlanning": 950000,
   "loanFloor": 4275000,
   "loanPlanning": 3800000,
   "isPrivate": false,
   "allEquity": false,
   "injectionPct": 0.1,
   "monthlyDebt": 61244,
   "annualDebt": 734924,
   "interestOnlyPayment": 33844,
   "dscr": 3.670598484250756,
   "unleveredYield": 0.5679181136842106,
   "rateBand": [
    {
     "rate": 0.095,
     "monthly": 61244,
     "annual": 734924,
     "dscr": 3.670598484250756
    },
    {
     "rate": 0.105,
     "monthly": 63532,
     "annual": 762386,
     "dscr": 3.538378076911635
    },
    {
     "rate": 0.115,
     "monthly": 65867,
     "annual": 790401,
     "dscr": 3.412964231875987
    }
   ],
   "founding": {
    "count": 150,
    "prepay": 3600,
    "discount": 0.33333333333333337,
    "proceeds": 540000
   },
   "capacity": {
    "operatingRoom": null,
    "circuit": {
     "theoretical": 6384,
     "practical": 3192,
     "demand": 2345,
     "utilization": 0.7346491228070177,
     "headroom": 847
    },
    "treatmentRooms": {
     "theoretical": 780,
     "practical": 507,
     "demand": 419,
     "utilization": 0.8264299802761341,
     "headroom": 88
    },
    "redLight": {
     "beds": 2,
     "theoretical": 1702,
     "practical": 851,
     "demand": 650,
     "utilization": 0.7636278195488723,
     "headroom": 201
    }
   },
   "ramp": [
    {
     "month": 1,
     "maturity": 0,
     "open": false,
     "revenue": 0,
     "cogs": 0,
     "opex": 72685,
     "operating": -72685,
     "debtService": 16922,
     "foundingProceeds": 90000,
     "netCash": 393,
     "cumulativeCash": 393
    },
    {
     "month": 2,
     "maturity": 0,
     "open": false,
     "revenue": 0,
     "cogs": 0,
     "opex": 72685,
     "operating": -72685,
     "debtService": 16922,
     "foundingProceeds": 90000,
     "netCash": 393,
     "cumulativeCash": 786
    },
    {
     "month": 3,
     "maturity": 0,
     "open": false,
     "revenue": 0,
     "cogs": 0,
     "opex": 72685,
     "operating": -72685,
     "debtService": 16922,
     "foundingProceeds": 90000,
     "netCash": 393,
     "cumulativeCash": 1178
    },
    {
     "month": 4,
     "maturity": 0,
     "open": false,
     "revenue": 0,
     "cogs": 0,
     "opex": 72685,
     "operating": -72685,
     "debtService": 16922,
     "foundingProceeds": 90000,
     "netCash": 393,
     "cumulativeCash": 1571
    },
    {
     "month": 5,
     "maturity": 0,
     "open": false,
     "revenue": 0,
     "cogs": 0,
     "opex": 72685,
     "operating": -72685,
     "debtService": 16922,
     "foundingProceeds": 90000,
     "netCash": 393,
     "cumulativeCash": 1964
    },
    {
     "month": 6,
     "maturity": 0,
     "open": false,
     "revenue": 0,
     "cogs": 0,
     "opex": 72685,
     "operating": -72685,
     "debtService": 16922,
     "foundingProceeds": 90000,
     "netCash": 393,
     "cumulativeCash": 2357
    },
    {
     "month": 7,
     "maturity": 0.15,
     "open": true,
     "revenue": 89705,
     "cogs": 24834,
     "opex": 145371,
     "operating": -80500,
     "debtService": 33844,
     "foundingProceeds": 0,
     "netCash": -114343,
     "cumulativeCash": -111987
    },
    {
     "month": 8,
     "maturity": 0.22,
     "open": true,
     "revenue": 131568,
     "cogs": 36424,
     "opex": 145371,
     "operating": -50227,
     "debtService": 33844,
     "foundingProceeds": 0,
     "netCash": -84070,
     "cumulativeCash": -196057
    },
    {
     "month": 9,
     "maturity": 0.3,
     "open": true,
     "revenue": 179411,
     "cogs": 49669,
     "opex": 145371,
     "operating": -15629,
     "debtService": 33844,
     "foundingProceeds": 0,
     "netCash": -49472,
     "cumulativeCash": -245530
    },
    {
     "month": 10,
     "maturity": 0.36,
     "open": true,
     "revenue": 215293,
     "cogs": 59603,
     "opex": 145371,
     "operating": 10320,
     "debtService": 33844,
     "foundingProceeds": 0,
     "netCash": -23524,
     "cumulativeCash": -269054
    },
    {
     "month": 11,
     "maturity": 0.42,
     "open": true,
     "revenue": 251175,
     "cogs": 69536,
     "opex": 145371,
     "operating": 36268,
     "debtService": 33844,
     "foundingProceeds": 0,
     "netCash": 2424,
     "cumulativeCash": -266630
    },
    {
     "month": 12,
     "maturity": 0.48,
     "open": true,
     "revenue": 287057,
     "cogs": 79470,
     "opex": 145371,
     "operating": 62216,
     "debtService": 33844,
     "foundingProceeds": 0,
     "netCash": 28373,
     "cumulativeCash": -238257
    },
    {
     "month": 13,
     "maturity": 0.54,
     "open": true,
     "revenue": 322940,
     "cogs": 89404,
     "opex": 145371,
     "operating": 88165,
     "debtService": 33844,
     "foundingProceeds": 0,
     "netCash": 54321,
     "cumulativeCash": -183936
    },
    {
     "month": 14,
     "maturity": 0.58,
     "open": true,
     "revenue": 346861,
     "cogs": 96026,
     "opex": 145371,
     "operating": 105464,
     "debtService": 33844,
     "foundingProceeds": 0,
     "netCash": 71620,
     "cumulativeCash": -112316
    },
    {
     "month": 15,
     "maturity": 0.62,
     "open": true,
     "revenue": 370783,
     "cogs": 102649,
     "opex": 145371,
     "operating": 122763,
     "debtService": 33844,
     "foundingProceeds": 0,
     "netCash": 88919,
     "cumulativeCash": -23397
    },
    {
     "month": 16,
     "maturity": 0.66,
     "open": true,
     "revenue": 394704,
     "cogs": 109272,
     "opex": 145371,
     "operating": 140062,
     "debtService": 33844,
     "foundingProceeds": 0,
     "netCash": 106218,
     "cumulativeCash": 82821
    },
    {
     "month": 17,
     "maturity": 0.7,
     "open": true,
     "revenue": 418625,
     "cogs": 115894,
     "opex": 145371,
     "operating": 157361,
     "debtService": 33844,
     "foundingProceeds": 0,
     "netCash": 123517,
     "cumulativeCash": 206338
    },
    {
     "month": 18,
     "maturity": 0.73,
     "open": true,
     "revenue": 436567,
     "cogs": 120861,
     "opex": 151601,
     "operating": 164105,
     "debtService": 33844,
     "foundingProceeds": 0,
     "netCash": 130261,
     "cumulativeCash": 336599
    },
    {
     "month": 19,
     "maturity": 0.76,
     "open": true,
     "revenue": 454508,
     "cogs": 125828,
     "opex": 157831,
     "operating": 170849,
     "debtService": 61244,
     "foundingProceeds": 0,
     "netCash": 109605,
     "cumulativeCash": 446204
    },
    {
     "month": 20,
     "maturity": 0.79,
     "open": true,
     "revenue": 472449,
     "cogs": 130795,
     "opex": 164061,
     "operating": 177593,
     "debtService": 61244,
     "foundingProceeds": 0,
     "netCash": 116349,
     "cumulativeCash": 562553
    },
    {
     "month": 21,
     "maturity": 0.82,
     "open": true,
     "revenue": 490390,
     "cogs": 135762,
     "opex": 170291,
     "operating": 184337,
     "debtService": 61244,
     "foundingProceeds": 0,
     "netCash": 123093,
     "cumulativeCash": 685646
    },
    {
     "month": 22,
     "maturity": 0.85,
     "open": true,
     "revenue": 508331,
     "cogs": 140728,
     "opex": 176522,
     "operating": 191081,
     "debtService": 61244,
     "foundingProceeds": 0,
     "netCash": 129837,
     "cumulativeCash": 815484
    },
    {
     "month": 23,
     "maturity": 0.87,
     "open": true,
     "revenue": 520292,
     "cogs": 144040,
     "opex": 180675,
     "operating": 195577,
     "debtService": 61244,
     "foundingProceeds": 0,
     "netCash": 134333,
     "cumulativeCash": 949817
    },
    {
     "month": 24,
     "maturity": 0.89,
     "open": true,
     "revenue": 532252,
     "cogs": 147351,
     "opex": 184829,
     "operating": 200073,
     "debtService": 61244,
     "foundingProceeds": 0,
     "netCash": 138829,
     "cumulativeCash": 1088646
    },
    {
     "month": 25,
     "maturity": 0.91,
     "open": true,
     "revenue": 544213,
     "cogs": 150662,
     "opex": 188982,
     "operating": 204569,
     "debtService": 61244,
     "foundingProceeds": 0,
     "netCash": 143325,
     "cumulativeCash": 1231971
    },
    {
     "month": 26,
     "maturity": 0.93,
     "open": true,
     "revenue": 556174,
     "cogs": 153973,
     "opex": 193135,
     "operating": 209065,
     "debtService": 61244,
     "foundingProceeds": 0,
     "netCash": 147821,
     "cumulativeCash": 1379792
    },
    {
     "month": 27,
     "maturity": 0.94,
     "open": true,
     "revenue": 562154,
     "cogs": 155629,
     "opex": 195212,
     "operating": 211313,
     "debtService": 61244,
     "foundingProceeds": 0,
     "netCash": 150069,
     "cumulativeCash": 1529861
    },
    {
     "month": 28,
     "maturity": 0.96,
     "open": true,
     "revenue": 574115,
     "cogs": 158940,
     "opex": 199366,
     "operating": 215809,
     "debtService": 61244,
     "foundingProceeds": 0,
     "netCash": 154565,
     "cumulativeCash": 1684427
    },
    {
     "month": 29,
     "maturity": 0.97,
     "open": true,
     "revenue": 580095,
     "cogs": 160596,
     "opex": 201442,
     "operating": 218057,
     "debtService": 61244,
     "foundingProceeds": 0,
     "netCash": 156813,
     "cumulativeCash": 1841240
    },
    {
     "month": 30,
     "maturity": 0.98,
     "open": true,
     "revenue": 586076,
     "cogs": 162252,
     "opex": 203519,
     "operating": 220305,
     "debtService": 61244,
     "foundingProceeds": 0,
     "netCash": 159061,
     "cumulativeCash": 2000301
    },
    {
     "month": 31,
     "maturity": 0.99,
     "open": true,
     "revenue": 592056,
     "cogs": 163907,
     "opex": 205596,
     "operating": 222553,
     "debtService": 61244,
     "foundingProceeds": 0,
     "netCash": 161309,
     "cumulativeCash": 2161610
    },
    {
     "month": 32,
     "maturity": 1,
     "open": true,
     "revenue": 598036,
     "cogs": 165563,
     "opex": 207673,
     "operating": 224801,
     "debtService": 61244,
     "foundingProceeds": 0,
     "netCash": 163557,
     "cumulativeCash": 2325168
    },
    {
     "month": 33,
     "maturity": 1,
     "open": true,
     "revenue": 598036,
     "cogs": 165563,
     "opex": 207673,
     "operating": 224801,
     "debtService": 61244,
     "foundingProceeds": 0,
     "netCash": 163557,
     "cumulativeCash": 2488725
    },
    {
     "month": 34,
     "maturity": 1,
     "open": true,
     "revenue": 598036,
     "cogs": 165563,
     "opex": 207673,
     "operating": 224801,
     "debtService": 61244,
     "foundingProceeds": 0,
     "netCash": 163557,
     "cumulativeCash": 2652282
    },
    {
     "month": 35,
     "maturity": 1,
     "open": true,
     "revenue": 598036,
     "cogs": 165563,
     "opex": 207673,
     "operating": 224801,
     "debtService": 61244,
     "foundingProceeds": 0,
     "netCash": 163557,
     "cumulativeCash": 2815839
    },
    {
     "month": 36,
     "maturity": 1,
     "open": true,
     "revenue": 598036,
     "cogs": 165563,
     "opex": 207673,
     "operating": 224801,
     "debtService": 61244,
     "foundingProceeds": 0,
     "netCash": 163557,
     "cumulativeCash": 2979397
    }
   ],
   "breakeven": 10,
   "dscrByYear": [
    {
     "year": 1,
     "operating": -473662,
     "debt": 304596,
     "dscr": -1.5550499678262355,
     "passes": false
    },
    {
     "year": 2,
     "operating": 1897430,
     "debt": 570528,
     "dscr": 3.3257438723428123,
     "passes": true
    },
    {
     "year": 3,
     "operating": 2625676,
     "debt": 734928,
     "dscr": 3.5726982779265453,
     "passes": true
    }
   ],
   "band": [
    {
     "label": "Low",
     "tag": "Slow member ramp, 72% of base volume",
     "revenue": 430586,
     "netAfterCogs": 311381,
     "operating": 103708,
     "annual": 1244500,
     "dscr": 1.6933728505260415
    },
    {
     "label": "Base",
     "tag": "Stated assumptions at stabilization",
     "revenue": 598036,
     "netAfterCogs": 432473,
     "operating": 224801,
     "annual": 2697611,
     "dscr": 3.6705986469349217
    },
    {
     "label": "Upside",
     "tag": "Waitlist demand, 128% of base volume",
     "revenue": 765486,
     "netAfterCogs": 553566,
     "operating": 345893,
     "annual": 4150722,
     "dscr": 5.647824443343803
    }
   ],
   "deal": null,
   "scope": {
    "total": 30,
    "licensed": 24,
    "openToAnyone": 6
   },
   "trough": {
    "month": 10,
    "amount": -269054
   },
   "reserve": 1105800,
   "rateStressPasses": true,
   "rateStress": {
    "rate": 0.115,
    "monthly": 65867,
    "annual": 790401,
    "dscr": 3.412964231875987
   },
   "cumulativeCash36": 2979397,
   "paybackMonth": {
    "month": 37,
    "extrapolated": true
   }
  },
  "surgical": {
   "key": "surgical",
   "label": "Surgical",
   "menu": "current",
   "projectCost": 5300000,
   "sqft": 5825,
   "tagline": "Everything in the ample case, plus one accredited office-based surgery suite.",
   "equipmentStrategy": "Purchased where payback justifies it, surgical equipment part leased",
   "stations": {
    "treatment": 3,
    "ivchair": 8,
    "sauna": 2,
    "plunge": 2,
    "aescape": 1,
    "ammortal": 1,
    "hbot": 1,
    "redlight": 2,
    "diagnostic": 2,
    "dexa": 1,
    "recovery": 4,
    "or": 1
   },
   "foundingMembers": 150,
   "space": [
    [
     "Arrival, concierge, retail",
     350
    ],
    [
     "The Lounge",
     700
    ],
    [
     "Contrast suite (2 saunas, 2 plunges)",
     250
    ],
    [
     "Aescape",
     120
    ],
    [
     "Ammortal chamber",
     90
    ],
    [
     "Hyperbaric room (seated)",
     120
    ],
    [
     "Red light beds (2)",
     150
    ],
    [
     "IV and regenerative lounge (8 chairs)",
     375
    ],
    [
     "Treatment rooms (3)",
     300
    ],
    [
     "Diagnostics and consult (2)",
     250
    ],
    [
     "Diagnostic imaging (GE iDXA densitometer)",
     125
    ],
    [
     "Operating room",
     350
    ],
    [
     "Pre-op and PACU (3 monitored bays)",
     220
    ],
    [
     "Sterile processing",
     110
    ],
    [
     "Sterile supply",
     90
    ],
    [
     "Soiled utility",
     50
    ],
    [
     "Surgical suite circulation",
     80
    ],
    [
     "Locker, shower, changing, bathrooms",
     550
    ],
    [
     "Admin offices (2)",
     200
    ],
    [
     "Kitchen and breakroom",
     200
    ],
    [
     "Storage",
     150
    ],
    [
     "MEP",
     75
    ],
    [
     "Biohazard and linen closets",
     30
    ],
    [
     "Circulation and grossing factor",
     890
    ]
   ],
   "opex": {
    "Rent (5,825 SF NNN)": 32037.5,
    "Clinical and club staff": 165000,
    "Admin and management": 30000,
    "Marketing and member acquisition": 32000,
    "Malpractice and liability": 26000,
    "Equipment leases": 29175,
    "Utilities, software, member platform": 18500,
    "Licensing, compliance and accreditation": 10000
   },
   "useOfFunds": [
    [
     "Buildout and tenant improvements (4,925 SF clinic and club @ $250/SF)",
     1231250
    ],
    [
     "Surgical suite buildout (900 SF @ $320/SF, OR-grade HVAC and finishes)",
     288000
    ],
    [
     "Medical gas, emergency power, life-safety branch for the suite",
     100000
    ],
    [
     "Wet areas: 2 saunas, 2 plunges, steam, drainage, ventilation",
     465000
    ],
    [
     "Medical and aesthetic equipment (purchased)",
     450000
    ],
    [
     "Surgical capital equipment (balance leased)",
     200000
    ],
    [
     "Recovery technology: HBOT purchased, Ammortal deposit",
     165950
    ],
    [
     "GE iDXA bone densitometer, purchased",
     25000
    ],
    [
     "FF&E, lounge, millwork, retail",
     400000
    ],
    [
     "Pre-opening: licensing, legal, insurance, hiring, transfer agreement",
     310000
    ],
    [
     "Accreditation: Quad A survey, policies, QA/PI program, staff training",
     110000
    ],
    [
     "Brand, launch, founding member campaign",
     200000
    ],
    [
     "Working capital and debt service reserve",
     1354800
    ]
   ],
   "lines": [
    {
     "id": "aescape",
     "name": "Aescape Robotic Massage",
     "cat": "Recovery",
     "margin": 0.82,
     "price": 70,
     "room": "aescape",
     "sessions": 200,
     "gross": 14000,
     "cogs": 2520.000000000001,
     "net": 11480
    },
    {
     "id": "ammortal",
     "name": "Ammortal Chamber",
     "cat": "Recovery",
     "margin": 0.82,
     "price": 140,
     "room": "ammortal",
     "sessions": 120,
     "gross": 16800,
     "cogs": 3024.000000000001,
     "net": 13776
    },
    {
     "id": "redlight",
     "name": "Red Light Therapy",
     "cat": "Recovery",
     "margin": 0.82,
     "price": 60,
     "room": "redlight",
     "sessions": 650,
     "gross": 39000,
     "cogs": 7020.000000000002,
     "net": 31979.999999999996
    },
    {
     "id": "hbot",
     "name": "Hyperbaric Oxygen",
     "cat": "Recovery",
     "margin": 0.8,
     "price": 200,
     "room": "hbot",
     "sessions": 50,
     "gross": 10000,
     "cogs": 1999.9999999999995,
     "net": 8000
    },
    {
     "id": "compress",
     "name": "Compression Therapy",
     "cat": "Recovery",
     "margin": 0.82,
     "price": 45,
     "room": "recovery",
     "sessions": 225,
     "gross": 10125,
     "cogs": 1822.5000000000005,
     "net": 8302.5
    },
    {
     "id": "prpHair",
     "name": "PRP: Hair & Scalp",
     "cat": "PRP",
     "margin": 0.72,
     "price": 995,
     "room": "treatment",
     "sessions": 33,
     "gross": 32835,
     "cogs": 9193.800000000001,
     "net": 23641.2
    },
    {
     "id": "prpFace",
     "name": "PRP: Face & Aesthetic",
     "cat": "PRP",
     "margin": 0.68,
     "price": 700,
     "room": "treatment",
     "sessions": 35,
     "gross": 24500,
     "cogs": 7839.999999999999,
     "net": 16660
    },
    {
     "id": "prpScar",
     "name": "PRP: Scar & Skin Repair",
     "cat": "PRP",
     "margin": 0.65,
     "price": 600,
     "room": "treatment",
     "sessions": 10,
     "gross": 6000,
     "cogs": 2100,
     "net": 3900
    },
    {
     "id": "prpSoft",
     "name": "PRP: Soft Tissue",
     "cat": "PRP",
     "margin": 0.65,
     "price": 1000,
     "room": "treatment",
     "sessions": 25,
     "gross": 25000,
     "cogs": 8750,
     "net": 16250
    },
    {
     "id": "prpJoint",
     "name": "PRP: Joint & Cartilage",
     "cat": "PRP",
     "margin": 0.62,
     "price": 1200,
     "room": "treatment",
     "sessions": 25,
     "gross": 30000,
     "cogs": 11400,
     "net": 18600
    },
    {
     "id": "prpPost",
     "name": "PRP: Post-procedure",
     "cat": "PRP",
     "margin": 0.6,
     "price": 650,
     "room": "treatment",
     "sessions": 15,
     "gross": 9750,
     "cogs": 3900,
     "net": 5850
    },
    {
     "id": "ivBasic",
     "name": "Basic Hydration",
     "cat": "Regenerative",
     "margin": 0.68,
     "price": 99,
     "room": "ivchair",
     "sessions": 71,
     "gross": 7029,
     "cogs": 2249.2799999999997,
     "net": 4779.72
    },
    {
     "id": "ivMyers",
     "name": "Myers Cocktail",
     "cat": "Regenerative",
     "margin": 0.56,
     "price": 199,
     "room": "ivchair",
     "sessions": 34,
     "gross": 6766,
     "cogs": 2977.0399999999995,
     "net": 3788.9600000000005
    },
    {
     "id": "ivRecovery",
     "name": "Recovery / Hangover",
     "cat": "Regenerative",
     "margin": 0.62,
     "price": 249,
     "room": "ivchair",
     "sessions": 34,
     "gross": 8466,
     "cogs": 3217.08,
     "net": 5248.92
    },
    {
     "id": "ivImmunity",
     "name": "Immunity / High-Dose C",
     "cat": "Regenerative",
     "margin": 0.61,
     "price": 289,
     "room": "ivchair",
     "sessions": 25,
     "gross": 7225,
     "cogs": 2817.75,
     "net": 4407.25
    },
    {
     "id": "ivBeauty",
     "name": "Beauty / Glutathione",
     "cat": "Regenerative",
     "margin": 0.66,
     "price": 165,
     "room": "ivchair",
     "sessions": 57,
     "gross": 9405,
     "cogs": 3197.7,
     "net": 6207.3
    },
    {
     "id": "ivAthletic",
     "name": "Athletic Performance",
     "cat": "Regenerative",
     "margin": 0.65,
     "price": 249,
     "room": "ivchair",
     "sessions": 40,
     "gross": 9960,
     "cogs": 3486,
     "net": 6474
    },
    {
     "id": "nad100",
     "name": "NAD+ 100mg",
     "cat": "Regenerative",
     "margin": 0.74,
     "price": 289,
     "room": "ivchair",
     "sessions": 25,
     "gross": 7225,
     "cogs": 1878.5,
     "net": 5346.5
    },
    {
     "id": "nad250",
     "name": "NAD+ 250mg",
     "cat": "Regenerative",
     "margin": 0.76,
     "price": 350,
     "room": "ivchair",
     "sessions": 33,
     "gross": 11550,
     "cogs": 2772,
     "net": 8778
    },
    {
     "id": "nad500",
     "name": "NAD+ 500mg",
     "cat": "Regenerative",
     "margin": 0.78,
     "price": 550,
     "room": "ivchair",
     "sessions": 33,
     "gross": 18150,
     "cogs": 3992.9999999999995,
     "net": 14157
    },
    {
     "id": "imShot",
     "name": "IM Shot: B12 / Lipo",
     "cat": "Regenerative",
     "margin": 0.65,
     "price": 95,
     "room": "ivchair",
     "sessions": 58,
     "gross": 5510,
     "cogs": 1928.4999999999998,
     "net": 3581.5
    },
    {
     "id": "thermeds",
     "name": "Therapeutic medications",
     "cat": "Regenerative",
     "margin": 0.75,
     "price": 300,
     "room": "treatment",
     "sessions": 60,
     "gross": 18000,
     "cogs": 4500,
     "net": 13500
    },
    {
     "id": "botox",
     "name": "Botox (15-unit minimum)",
     "cat": "Aesthetics",
     "margin": 0.7,
     "price": 240,
     "room": "treatment",
     "sessions": 80,
     "gross": 19200,
     "cogs": 5760.000000000001,
     "net": 13440
    },
    {
     "id": "filler",
     "name": "Filler (0.5 ml)",
     "cat": "Aesthetics",
     "margin": 0.65,
     "price": 850,
     "room": "treatment",
     "sessions": 56,
     "gross": 47600,
     "cogs": 16660,
     "net": 30940
    },
    {
     "id": "rfmicro",
     "name": "RF Microneedling",
     "cat": "Aesthetics",
     "margin": 0.75,
     "price": 1000,
     "room": "treatment",
     "sessions": 50,
     "gross": 50000,
     "cogs": 12500,
     "net": 37500
    },
    {
     "id": "laser",
     "name": "Laser Platform",
     "cat": "Aesthetics",
     "margin": 0.7,
     "price": 850,
     "room": "treatment",
     "sessions": 30,
     "gross": 25500,
     "cogs": 7650.000000000001,
     "net": 17850
    },
    {
     "id": "biometric",
     "name": "Advanced Biometrics",
     "cat": "Diagnostics",
     "margin": 0.7,
     "price": 225,
     "room": "diagnostic",
     "sessions": 20,
     "gross": 4500,
     "cogs": 1350.0000000000002,
     "net": 3150
    },
    {
     "id": "dna",
     "name": "DNA Analysis",
     "cat": "Diagnostics",
     "margin": 0.67,
     "price": 600,
     "room": "diagnostic",
     "sessions": 15,
     "gross": 9000,
     "cogs": 2969.9999999999995,
     "net": 6030
    },
    {
     "id": "dutch",
     "name": "DUTCH Plus Test",
     "cat": "Diagnostics",
     "margin": 0.65,
     "price": 750,
     "room": "diagnostic",
     "sessions": 20,
     "gross": 15000,
     "cogs": 5250,
     "net": 9750
    },
    {
     "id": "dexa",
     "name": "DEXA Scan",
     "cat": "Diagnostics",
     "margin": 0.77,
     "price": 95,
     "room": "diagnostic",
     "sessions": 95,
     "gross": 9025,
     "cogs": 2075.75,
     "net": 6949.25
    },
    {
     "id": "bleph",
     "name": "Blepharoplasty (facility fee)",
     "cat": "Surgery",
     "margin": 0.8,
     "lo": 2200,
     "hi": 3400,
     "room": "or",
     "facilityFee": true,
     "sessions": 7,
     "price": 2800,
     "gross": 19600,
     "cogs": 3919.999999999999,
     "net": 15680
    },
    {
     "id": "facialcon",
     "name": "Facial Contouring Surgery (facility fee)",
     "cat": "Surgery",
     "margin": 0.8,
     "lo": 2200,
     "hi": 3400,
     "room": "or",
     "facilityFee": true,
     "sessions": 5,
     "price": 2800,
     "gross": 14000,
     "cogs": 2799.9999999999995,
     "net": 11200
    },
    {
     "id": "awakelipo",
     "name": "Awake Liposuction & Body Contouring (facility fee)",
     "cat": "Surgery",
     "margin": 0.78,
     "lo": 3000,
     "hi": 4600,
     "room": "or",
     "facilityFee": true,
     "sessions": 6,
     "price": 3800,
     "gross": 22800,
     "cogs": 5015.999999999999,
     "net": 17784
    },
    {
     "id": "fatgraft",
     "name": "Fat Grafting & Transfer (facility fee)",
     "cat": "Surgery",
     "margin": 0.8,
     "lo": 2200,
     "hi": 3400,
     "room": "or",
     "facilityFee": true,
     "sessions": 4,
     "price": 2800,
     "gross": 11200,
     "cogs": 2239.9999999999995,
     "net": 8960
    },
    {
     "id": "hairrest",
     "name": "Hair Restoration Surgery",
     "cat": "Surgery",
     "margin": 0.74,
     "lo": 6000,
     "hi": 14000,
     "room": "treatment",
     "sessions": 3,
     "price": 10000,
     "gross": 30000,
     "cogs": 7800,
     "net": 22200
    },
    {
     "id": "officesurg",
     "name": "Office Surgical Procedures",
     "cat": "Surgery",
     "margin": 0.76,
     "lo": 900,
     "hi": 3500,
     "room": "treatment",
     "sessions": 12,
     "price": 2200,
     "gross": 26400,
     "cogs": 6336,
     "net": 20064
    },
    {
     "id": "ablative",
     "name": "Ablative Laser & Skin Tightening",
     "cat": "Surgery",
     "margin": 0.73,
     "lo": 2500,
     "hi": 6000,
     "room": "treatment",
     "sessions": 5,
     "price": 4250,
     "gross": 21250,
     "cogs": 5737.5,
     "net": 15512.5
    }
   ],
   "rackValue": 652371,
   "serviceCogs": 180652.4,
   "redeemed": 129500,
   "alaCarteGross": 522871,
   "memberDiscount": 41829.68,
   "alaCarteNet": 481041.32,
   "membershipLines": [
    {
     "id": "friends",
     "name": "Friends of L&K",
     "count": 900,
     "monthly": 22500
    },
    {
     "id": "resident",
     "name": "Resident",
     "count": 350,
     "monthly": 157500
    },
    {
     "id": "longevity",
     "name": "Longevity",
     "count": 40,
     "monthly": 50000
    }
   ],
   "membershipRevenue": 230000,
   "accessRevenue": 20625,
   "totalRevenue": 731666.3200000001,
   "circuitCogs": 18760,
   "totalCogs": 199412.4,
   "netAfterCogs": 532253.92,
   "blendedMargin": 0.7274544494545,
   "serviceMargin": 0.7230833375487261,
   "redemptionRatio": 0.6240963855421687,
   "opexTotal": 342712.5,
   "operatingIncome": 189541.42000000004,
   "operatingIncomeAnnual": 2274497.0400000005,
   "operatingMargin": 0.259054455315095,
   "revenueAnnual": 8779995.84,
   "injectionFloor": 530000,
   "injectionPlanning": 1060000,
   "loanFloor": 4770000,
   "loanPlanning": 4240000,
   "isPrivate": false,
   "allEquity": false,
   "injectionPct": 0.1,
   "monthlyDebt": 68335,
   "annualDebt": 820020,
   "interestOnlyPayment": 37763,
   "dscr": 2.7737075370451265,
   "unleveredYield": 0.4291503849056605,
   "rateBand": [
    {
     "rate": 0.095,
     "monthly": 68335,
     "annual": 820020,
     "dscr": 2.7737075370451265
    },
    {
     "rate": 0.105,
     "monthly": 70889,
     "annual": 850663,
     "dscr": 2.6737944732869265
    },
    {
     "rate": 0.115,
     "monthly": 73493,
     "annual": 881921,
     "dscr": 2.5790248250353573
    }
   ],
   "founding": {
    "count": 150,
    "prepay": 3600,
    "discount": 0.33333333333333337,
    "proceeds": 540000
   },
   "capacity": {
    "operatingRoom": {
     "cases": 22,
     "theoretical": 90,
     "practical": 63,
     "demand": 38.5,
     "utilization": 0.6111111111111112,
     "headroom": 24.5
    },
    "circuit": {
     "theoretical": 6384,
     "practical": 3192,
     "demand": 2345,
     "utilization": 0.7346491228070177,
     "headroom": 847
    },
    "treatmentRooms": {
     "theoretical": 780,
     "practical": 507,
     "demand": 439,
     "utilization": 0.8658777120315582,
     "headroom": 68
    },
    "redLight": {
     "beds": 2,
     "theoretical": 1702,
     "practical": 851,
     "demand": 650,
     "utilization": 0.7636278195488723,
     "headroom": 201
    }
   },
   "ramp": [
    {
     "month": 1,
     "maturity": 0,
     "open": false,
     "revenue": 0,
     "cogs": 0,
     "opex": 119949,
     "operating": -119949,
     "debtService": 18881,
     "foundingProceeds": 90000,
     "netCash": -48831,
     "cumulativeCash": -48831
    },
    {
     "month": 2,
     "maturity": 0,
     "open": false,
     "revenue": 0,
     "cogs": 0,
     "opex": 119949,
     "operating": -119949,
     "debtService": 18881,
     "foundingProceeds": 90000,
     "netCash": -48831,
     "cumulativeCash": -97661
    },
    {
     "month": 3,
     "maturity": 0,
     "open": false,
     "revenue": 0,
     "cogs": 0,
     "opex": 119949,
     "operating": -119949,
     "debtService": 18881,
     "foundingProceeds": 90000,
     "netCash": -48831,
     "cumulativeCash": -146492
    },
    {
     "month": 4,
     "maturity": 0,
     "open": false,
     "revenue": 0,
     "cogs": 0,
     "opex": 119949,
     "operating": -119949,
     "debtService": 18881,
     "foundingProceeds": 90000,
     "netCash": -48831,
     "cumulativeCash": -195322
    },
    {
     "month": 5,
     "maturity": 0,
     "open": false,
     "revenue": 0,
     "cogs": 0,
     "opex": 119949,
     "operating": -119949,
     "debtService": 18881,
     "foundingProceeds": 90000,
     "netCash": -48831,
     "cumulativeCash": -244153
    },
    {
     "month": 6,
     "maturity": 0,
     "open": false,
     "revenue": 0,
     "cogs": 0,
     "opex": 119949,
     "operating": -119949,
     "debtService": 18881,
     "foundingProceeds": 90000,
     "netCash": -48831,
     "cumulativeCash": -292984
    },
    {
     "month": 7,
     "maturity": 0.15,
     "open": true,
     "revenue": 109750,
     "cogs": 29912,
     "opex": 239899,
     "operating": -160061,
     "debtService": 37763,
     "foundingProceeds": 0,
     "netCash": -197823,
     "cumulativeCash": -490807
    },
    {
     "month": 8,
     "maturity": 0.22,
     "open": true,
     "revenue": 160967,
     "cogs": 43871,
     "opex": 239899,
     "operating": -122803,
     "debtService": 37763,
     "foundingProceeds": 0,
     "netCash": -160565,
     "cumulativeCash": -651372
    },
    {
     "month": 9,
     "maturity": 0.3,
     "open": true,
     "revenue": 219500,
     "cogs": 59824,
     "opex": 239899,
     "operating": -80223,
     "debtService": 37763,
     "foundingProceeds": 0,
     "netCash": -117985,
     "cumulativeCash": -769357
    },
    {
     "month": 10,
     "maturity": 0.36,
     "open": true,
     "revenue": 263400,
     "cogs": 71788,
     "opex": 239899,
     "operating": -48287,
     "debtService": 37763,
     "foundingProceeds": 0,
     "netCash": -86050,
     "cumulativeCash": -855407
    },
    {
     "month": 11,
     "maturity": 0.42,
     "open": true,
     "revenue": 307300,
     "cogs": 83753,
     "opex": 239899,
     "operating": -16352,
     "debtService": 37763,
     "foundingProceeds": 0,
     "netCash": -54115,
     "cumulativeCash": -909522
    },
    {
     "month": 12,
     "maturity": 0.48,
     "open": true,
     "revenue": 351200,
     "cogs": 95718,
     "opex": 239899,
     "operating": 15583,
     "debtService": 37763,
     "foundingProceeds": 0,
     "netCash": -22179,
     "cumulativeCash": -931701
    },
    {
     "month": 13,
     "maturity": 0.54,
     "open": true,
     "revenue": 395100,
     "cogs": 107683,
     "opex": 239899,
     "operating": 47518,
     "debtService": 37763,
     "foundingProceeds": 0,
     "netCash": 9756,
     "cumulativeCash": -921945
    },
    {
     "month": 14,
     "maturity": 0.58,
     "open": true,
     "revenue": 424366,
     "cogs": 115659,
     "opex": 239899,
     "operating": 68809,
     "debtService": 37763,
     "foundingProceeds": 0,
     "netCash": 31046,
     "cumulativeCash": -890899
    },
    {
     "month": 15,
     "maturity": 0.62,
     "open": true,
     "revenue": 453633,
     "cogs": 123636,
     "opex": 239899,
     "operating": 90099,
     "debtService": 37763,
     "foundingProceeds": 0,
     "netCash": 52336,
     "cumulativeCash": -838563
    },
    {
     "month": 16,
     "maturity": 0.66,
     "open": true,
     "revenue": 482900,
     "cogs": 131612,
     "opex": 239899,
     "operating": 111389,
     "debtService": 37763,
     "foundingProceeds": 0,
     "netCash": 73626,
     "cumulativeCash": -764937
    },
    {
     "month": 17,
     "maturity": 0.7,
     "open": true,
     "revenue": 512166,
     "cogs": 139589,
     "opex": 239899,
     "operating": 132679,
     "debtService": 37763,
     "foundingProceeds": 0,
     "netCash": 94916,
     "cumulativeCash": -670020
    },
    {
     "month": 18,
     "maturity": 0.73,
     "open": true,
     "revenue": 534116,
     "cogs": 145571,
     "opex": 250180,
     "operating": 138365,
     "debtService": 37763,
     "foundingProceeds": 0,
     "netCash": 100603,
     "cumulativeCash": -569418
    },
    {
     "month": 19,
     "maturity": 0.76,
     "open": true,
     "revenue": 556066,
     "cogs": 151553,
     "opex": 260462,
     "operating": 144051,
     "debtService": 68335,
     "foundingProceeds": 0,
     "netCash": 75716,
     "cumulativeCash": -493701
    },
    {
     "month": 20,
     "maturity": 0.79,
     "open": true,
     "revenue": 578016,
     "cogs": 157536,
     "opex": 270743,
     "operating": 149738,
     "debtService": 68335,
     "foundingProceeds": 0,
     "netCash": 81403,
     "cumulativeCash": -412298
    },
    {
     "month": 21,
     "maturity": 0.82,
     "open": true,
     "revenue": 599966,
     "cogs": 163518,
     "opex": 281024,
     "operating": 155424,
     "debtService": 68335,
     "foundingProceeds": 0,
     "netCash": 87089,
     "cumulativeCash": -325210
    },
    {
     "month": 22,
     "maturity": 0.85,
     "open": true,
     "revenue": 621916,
     "cogs": 169501,
     "opex": 291306,
     "operating": 161110,
     "debtService": 68335,
     "foundingProceeds": 0,
     "netCash": 92775,
     "cumulativeCash": -232434
    },
    {
     "month": 23,
     "maturity": 0.87,
     "open": true,
     "revenue": 636550,
     "cogs": 173489,
     "opex": 298160,
     "operating": 164901,
     "debtService": 68335,
     "foundingProceeds": 0,
     "netCash": 96566,
     "cumulativeCash": -135868
    },
    {
     "month": 24,
     "maturity": 0.89,
     "open": true,
     "revenue": 651183,
     "cogs": 177477,
     "opex": 305014,
     "operating": 168692,
     "debtService": 68335,
     "foundingProceeds": 0,
     "netCash": 100357,
     "cumulativeCash": -35512
    },
    {
     "month": 25,
     "maturity": 0.91,
     "open": true,
     "revenue": 665816,
     "cogs": 181465,
     "opex": 311868,
     "operating": 172483,
     "debtService": 68335,
     "foundingProceeds": 0,
     "netCash": 104148,
     "cumulativeCash": 68636
    },
    {
     "month": 26,
     "maturity": 0.93,
     "open": true,
     "revenue": 680450,
     "cogs": 185454,
     "opex": 318723,
     "operating": 176274,
     "debtService": 68335,
     "foundingProceeds": 0,
     "netCash": 107938,
     "cumulativeCash": 176575
    },
    {
     "month": 27,
     "maturity": 0.94,
     "open": true,
     "revenue": 687766,
     "cogs": 187448,
     "opex": 322150,
     "operating": 178169,
     "debtService": 68335,
     "foundingProceeds": 0,
     "netCash": 109834,
     "cumulativeCash": 286408
    },
    {
     "month": 28,
     "maturity": 0.96,
     "open": true,
     "revenue": 702400,
     "cogs": 191436,
     "opex": 329004,
     "operating": 181960,
     "debtService": 68335,
     "foundingProceeds": 0,
     "netCash": 113625,
     "cumulativeCash": 400033
    },
    {
     "month": 29,
     "maturity": 0.97,
     "open": true,
     "revenue": 709716,
     "cogs": 193430,
     "opex": 332431,
     "operating": 183855,
     "debtService": 68335,
     "foundingProceeds": 0,
     "netCash": 115520,
     "cumulativeCash": 515553
    },
    {
     "month": 30,
     "maturity": 0.98,
     "open": true,
     "revenue": 717033,
     "cogs": 195424,
     "opex": 335858,
     "operating": 185751,
     "debtService": 68335,
     "foundingProceeds": 0,
     "netCash": 117416,
     "cumulativeCash": 632969
    },
    {
     "month": 31,
     "maturity": 0.99,
     "open": true,
     "revenue": 724350,
     "cogs": 197418,
     "opex": 339285,
     "operating": 187646,
     "debtService": 68335,
     "foundingProceeds": 0,
     "netCash": 119311,
     "cumulativeCash": 752280
    },
    {
     "month": 32,
     "maturity": 1,
     "open": true,
     "revenue": 731666,
     "cogs": 199412,
     "opex": 342713,
     "operating": 189541,
     "debtService": 68335,
     "foundingProceeds": 0,
     "netCash": 121206,
     "cumulativeCash": 873486
    },
    {
     "month": 33,
     "maturity": 1,
     "open": true,
     "revenue": 731666,
     "cogs": 199412,
     "opex": 342713,
     "operating": 189541,
     "debtService": 68335,
     "foundingProceeds": 0,
     "netCash": 121206,
     "cumulativeCash": 994693
    },
    {
     "month": 34,
     "maturity": 1,
     "open": true,
     "revenue": 731666,
     "cogs": 199412,
     "opex": 342713,
     "operating": 189541,
     "debtService": 68335,
     "foundingProceeds": 0,
     "netCash": 121206,
     "cumulativeCash": 1115899
    },
    {
     "month": 35,
     "maturity": 1,
     "open": true,
     "revenue": 731666,
     "cogs": 199412,
     "opex": 342713,
     "operating": 189541,
     "debtService": 68335,
     "foundingProceeds": 0,
     "netCash": 121206,
     "cumulativeCash": 1237105
    },
    {
     "month": 36,
     "maturity": 1,
     "open": true,
     "revenue": 731666,
     "cogs": 199412,
     "opex": 342713,
     "operating": 189541,
     "debtService": 68335,
     "foundingProceeds": 0,
     "netCash": 121206,
     "cumulativeCash": 1358312
    }
   ],
   "breakeven": 12,
   "dscrByYear": [
    {
     "year": 1,
     "operating": -1131837,
     "debt": 339864,
     "dscr": -3.3302644587246664,
     "passes": false
    },
    {
     "year": 2,
     "operating": 1532775,
     "debt": 636588,
     "dscr": 2.407797507964335,
     "passes": true
    },
    {
     "year": 3,
     "operating": 2213843,
     "debt": 820020,
     "dscr": 2.6997426892027026,
     "passes": true
    }
   ],
   "band": [
    {
     "label": "Low",
     "tag": "Slow member ramp, 72% of base volume",
     "revenue": 526800,
     "netAfterCogs": 383223,
     "operating": 40510,
     "annual": 486124,
     "dscr": 0.5928195273286027
    },
    {
     "label": "Base",
     "tag": "Stated assumptions at stabilization",
     "revenue": 731666,
     "netAfterCogs": 532254,
     "operating": 189541,
     "annual": 2274497,
     "dscr": 2.77370922660423
    },
    {
     "label": "Upside",
     "tag": "Waitlist demand, 128% of base volume",
     "revenue": 936533,
     "netAfterCogs": 681285,
     "operating": 338573,
     "annual": 4062870,
     "dscr": 4.954598925879859
    }
   ],
   "deal": null,
   "scope": {
    "total": 30,
    "licensed": 24,
    "openToAnyone": 6
   },
   "trough": {
    "month": 12,
    "amount": -931701
   },
   "reserve": 1354800,
   "rateStressPasses": true,
   "rateStress": {
    "rate": 0.115,
    "monthly": 73493,
    "annual": 881921,
    "dscr": 2.5790248250353573
   },
   "cumulativeCash36": 1358312,
   "paybackMonth": {
    "month": 48,
    "extrapolated": true
   }
  }
 }
};
