/* GENERATED by deck-build/build-sites.js — do not edit by hand. */
window.LK = {
 "generated": "2026-08-12",
 "scenario": "surgical",
 "selectable": [
  "surgical"
 ],
 "assumptions": {
  "redeemsPerMonth": {
   "resident": 270,
   "longevity": 875
  },
  "blendedMemberDiscount": 0.08,
  "circuitVisitsPerMonth": {
   "resident": 5,
   "longevity": 8,
   "dayPass": 1
  },
  "circuitCostPerVisit": 8,
  "clubHoursPerDay": 14,
  "daysPerMonth": 30.4,
  "clinicalHoursPerDay": 10,
  "clinicalDaysPerMonth": 26,
  "circuitPracticalUtilization": 0.5,
  "treatmentRoomUtilization": 0.65,
  "plungeThroughputPerHour": 7.5,
  "procedureHoursEach": 1,
  "orBlockDaysPerMonth": 9,
  "orHoursPerDay": 10,
  "orUtilization": 0.7,
  "orHoursPerCase": 1.75,
  "primeRate": 0.0675,
  "sbaMaxSpread": 0.0275,
  "loanTermMonths": 120,
  "interestOnlyMonths": 18,
  "constructionMonths": 6,
  "avgConstructionDraw": 0.5,
  "equityInjectionFloor": 0.1,
  "equityInjectionPlanning": 0.2,
  "dscrThreshold": 1.25,
  "foundingPrepay": 3600,
  "foundingListPrice": 5400,
  "sbaRate": 0.095
 },
 "services": [
  {
   "id": "aescape",
   "name": "Aescape Robotic Massage",
   "cat": "Recovery",
   "margin": 0.82,
   "lo": 60,
   "hi": 80,
   "room": "aescape",
   "sessions": {
    "lean": 110,
    "ample": 200,
    "surgical": 200
   }
  },
  {
   "id": "ammortal",
   "name": "Ammortal Chamber",
   "cat": "Recovery",
   "margin": 0.82,
   "lo": 90,
   "hi": 150,
   "room": "ammortal",
   "sessions": {
    "lean": 70,
    "ample": 120,
    "surgical": 120
   }
  },
  {
   "id": "redlight",
   "name": "Red Light Therapy",
   "cat": "Recovery",
   "margin": 0.82,
   "lo": 50,
   "hi": 100,
   "room": "recovery",
   "sessions": {
    "lean": 50,
    "ample": 80,
    "surgical": 80
   }
  },
  {
   "id": "hbot",
   "name": "Hyperbaric Oxygen",
   "cat": "Recovery",
   "margin": 0.8,
   "lo": 150,
   "hi": 250,
   "room": "hbot",
   "sessions": {
    "lean": 55,
    "ample": 100,
    "surgical": 100
   }
  },
  {
   "id": "prp",
   "name": "PRP Injections",
   "cat": "Regenerative",
   "margin": 0.78,
   "lo": 800,
   "hi": 1500,
   "room": "treatment",
   "sessions": {
    "lean": 36,
    "ample": 50,
    "surgical": 50
   }
  },
  {
   "id": "compress",
   "name": "Compression / NeuFit",
   "cat": "Recovery",
   "margin": 0.78,
   "lo": 75,
   "hi": 150,
   "room": "recovery",
   "sessions": {
    "lean": 50,
    "ample": 80,
    "surgical": 80
   }
  },
  {
   "id": "hormone",
   "name": "Hormone / Peptide / GLP",
   "cat": "Regenerative",
   "margin": 0.75,
   "lo": 400,
   "hi": 800,
   "room": "treatment",
   "sessions": {
    "lean": 30,
    "ample": 40,
    "surgical": 40
   }
  },
  {
   "id": "iv",
   "name": "IV Therapy (NAD+ / Drips)",
   "cat": "Regenerative",
   "margin": 0.72,
   "lo": 350,
   "hi": 1000,
   "room": "ivchair",
   "sessions": {
    "lean": 85,
    "ample": 120,
    "surgical": 120
   }
  },
  {
   "id": "botox",
   "name": "Botox & Fillers",
   "cat": "Aesthetics",
   "margin": 0.7,
   "lo": 500,
   "hi": 950,
   "room": "treatment",
   "sessions": {
    "lean": 58,
    "ample": 80,
    "surgical": 80
   }
  },
  {
   "id": "laser",
   "name": "Laser Platform",
   "cat": "Aesthetics",
   "margin": 0.7,
   "lo": 500,
   "hi": 1200,
   "room": "treatment",
   "sessions": {
    "lean": 20,
    "ample": 30,
    "surgical": 30
   }
  },
  {
   "id": "biometric",
   "name": "Advanced Biometrics",
   "cat": "Diagnostics",
   "margin": 0.7,
   "lo": 150,
   "hi": 300,
   "room": "diagnostic",
   "sessions": {
    "lean": 14,
    "ample": 20,
    "surgical": 20
   }
  },
  {
   "id": "morpheus",
   "name": "Morpheus8 RF Microneedling",
   "cat": "Aesthetics",
   "margin": 0.68,
   "lo": 835,
   "hi": 1500,
   "room": "treatment",
   "sessions": {
    "lean": 20,
    "ample": 30,
    "surgical": 30
   }
  },
  {
   "id": "dna",
   "name": "DNA Analysis",
   "cat": "Diagnostics",
   "margin": 0.67,
   "lo": 300,
   "hi": 500,
   "room": "diagnostic",
   "sessions": {
    "lean": 11,
    "ample": 15,
    "surgical": 15
   }
  },
  {
   "id": "emsculpt",
   "name": "Emsculpt",
   "cat": "Aesthetics",
   "margin": 0.67,
   "lo": 750,
   "hi": 1200,
   "room": "treatment",
   "sessions": {
    "lean": 20,
    "ample": 30,
    "surgical": 30
   }
  },
  {
   "id": "dutch",
   "name": "DUTCH Testing",
   "cat": "Diagnostics",
   "margin": 0.65,
   "lo": 400,
   "hi": 650,
   "room": "diagnostic",
   "sessions": {
    "lean": 14,
    "ample": 20,
    "surgical": 20
   }
  },
  {
   "id": "coolsculpt",
   "name": "CoolSculpting",
   "cat": "Aesthetics",
   "margin": 0.65,
   "lo": 700,
   "hi": 1200,
   "room": "treatment",
   "sessions": {
    "lean": 14,
    "ample": 20,
    "surgical": 20
   }
  },
  {
   "id": "dexa",
   "name": "DEXA Scan",
   "cat": "Diagnostics",
   "margin": 0.62,
   "lo": 200,
   "hi": 350,
   "room": "diagnostic",
   "sessions": {
    "lean": 14,
    "ample": 20,
    "surgical": 20
   }
  },
  {
   "id": "bleph",
   "name": "Blepharoplasty (facility fee)",
   "cat": "Surgery",
   "margin": 0.8,
   "lo": 2200,
   "hi": 3400,
   "room": "or",
   "facilityFee": true,
   "sessions": {
    "lean": 0,
    "ample": 0,
    "surgical": 7
   }
  },
  {
   "id": "facialcon",
   "name": "Facial Contouring Surgery (facility fee)",
   "cat": "Surgery",
   "margin": 0.8,
   "lo": 2200,
   "hi": 3400,
   "room": "or",
   "facilityFee": true,
   "sessions": {
    "lean": 0,
    "ample": 0,
    "surgical": 5
   }
  },
  {
   "id": "awakelipo",
   "name": "Awake Liposuction & Body Contouring (facility fee)",
   "cat": "Surgery",
   "margin": 0.78,
   "lo": 3000,
   "hi": 4600,
   "room": "or",
   "facilityFee": true,
   "sessions": {
    "lean": 0,
    "ample": 0,
    "surgical": 6
   }
  },
  {
   "id": "fatgraft",
   "name": "Fat Grafting & Transfer (facility fee)",
   "cat": "Surgery",
   "margin": 0.8,
   "lo": 2200,
   "hi": 3400,
   "room": "or",
   "facilityFee": true,
   "sessions": {
    "lean": 0,
    "ample": 0,
    "surgical": 4
   }
  },
  {
   "id": "hairrest",
   "name": "Hair Restoration Surgery",
   "cat": "Surgery",
   "margin": 0.74,
   "lo": 6000,
   "hi": 14000,
   "room": "treatment",
   "sessions": {
    "lean": 0,
    "ample": 0,
    "surgical": 3
   }
  },
  {
   "id": "officesurg",
   "name": "Office Surgical Procedures",
   "cat": "Surgery",
   "margin": 0.76,
   "lo": 900,
   "hi": 3500,
   "room": "treatment",
   "sessions": {
    "lean": 0,
    "ample": 0,
    "surgical": 12
   }
  },
  {
   "id": "ablative",
   "name": "Ablative Laser & Skin Tightening",
   "cat": "Surgery",
   "margin": 0.73,
   "lo": 2500,
   "hi": 6000,
   "room": "treatment",
   "sessions": {
    "lean": 0,
    "ample": 0,
    "surgical": 5
   }
  }
 ],
 "tiers": [
  {
   "id": "daypass",
   "name": "Day Pass",
   "cadence": "per visit",
   "price": 75,
   "blurb": "One visit to the recovery circuit. Book any procedure at rack rate.",
   "includes": [
    "Single circuit visit",
    "Procedures at rack rate",
    "No events or lounge privileges"
   ],
   "counts": {
    "lean": 190,
    "ample": 275,
    "surgical": 275
   },
   "isMembership": false
  },
  {
   "id": "friends",
   "name": "Friends of L&K",
   "cadence": "per year",
   "price": 300,
   "blurb": "The on-ramp. Member pricing without club access.",
   "includes": [
    "Member pricing on all procedures",
    "Priority booking window",
    "Invitations to open events",
    "No club or circuit access"
   ],
   "counts": {
    "lean": 750,
    "ample": 900,
    "surgical": 900
   },
   "isMembership": true,
   "monthly": 25,
   "usesCircuit": false
  },
  {
   "id": "resident",
   "name": "Resident",
   "cadence": "per month",
   "price": 450,
   "blurb": "The core membership. Where the club actually lives.",
   "includes": [
    "Rolling monthly credit bank",
    "Unlimited recovery circuit",
    "Member pricing on all procedures",
    "1 guest pass per month",
    "Member events"
   ],
   "counts": {
    "lean": 300,
    "ample": 350,
    "surgical": 350
   },
   "isMembership": true,
   "monthly": 450,
   "usesCircuit": true,
   "capped": true
  },
  {
   "id": "longevity",
   "name": "Longevity",
   "cadence": "per month",
   "price": 1250,
   "blurb": "Physician-led. Hard capped.",
   "includes": [
    "Everything in Resident",
    "Quarterly physician consult",
    "Annual biomarker panel, DEXA and DUTCH",
    "Hormone and peptide program included",
    "4 guest passes per month",
    "Private buyout privileges"
   ],
   "counts": {
    "lean": 32,
    "ample": 40,
    "surgical": 40
   },
   "isMembership": true,
   "monthly": 1250,
   "usesCircuit": true,
   "capped": true
  }
 ],
 "surgicalMenu": {
  "or": [
   "Blepharoplasty, upper, lower and combined",
   "Brow lift",
   "Otoplasty",
   "Chin augmentation and implant",
   "Buccal fat removal",
   "Facial fat grafting and transfer",
   "Liposuction, single or limited area, awake tumescent",
   "Submental neck contouring",
   "Limited body-contouring revision",
   "Scar revision, facial and body",
   "Nasal valve procedures sold as elective self-pay"
  ],
  "treatment": [
   "Lipoma removal",
   "Cyst removal",
   "Benign lesion removal",
   "Ablative laser resurfacing",
   "Skin tightening",
   "Hair restoration surgery and transplant"
  ],
  "excluded": [
   [
    "Breast augmentation, lift, implant exchange or removal",
    "General anesthesia in standard practice"
   ],
   [
    "Facelift and neck lift",
    "General anesthesia; recovery well beyond two hours"
   ],
   [
    "Cosmetic and revision rhinoplasty",
    "Airway risk from pharyngeal blood; general anesthesia standard"
   ],
   [
    "Mini and full abdominoplasty",
    "General anesthesia; extended recovery and caregiver discharge"
   ]
  ]
 },
 "market": [
  {
   "id": "wellness-economy",
   "value": "$6.8T",
   "label": "Global wellness economy, 2024",
   "note": "Grew 7.9% from 2023 to 2024 and has doubled in size since 2013.",
   "source": "Global Wellness Institute",
   "url": "https://globalwellnessinstitute.org/press-room/statistics-and-facts/"
  },
  {
   "id": "medspa-global",
   "value": "$27.8B",
   "label": "Global medical spa market, 2026",
   "note": "Up from $24.2B in 2025, projected to $78.2B by 2033 at a 15.9% CAGR. North America holds 41.2% of it, roughly $10B.",
   "source": "Grand View Research",
   "url": "https://www.grandviewresearch.com/industry-analysis/medical-spa-market"
  },
  {
   "id": "medspa-count",
   "value": "10,488",
   "label": "US medical spas, 2023",
   "note": "Up from 8,899 in 2022. The category is being built out right now, which is both the opportunity and the reason to differentiate.",
   "source": "Grand View Research",
   "url": "https://www.grandviewresearch.com/industry-analysis/medical-spa-market"
  },
  {
   "id": "consumer-priority",
   "value": "82%",
   "label": "US consumers calling wellness a top or important priority",
   "note": "The US consumer wellness market runs near $480B and is growing up to 10% a year.",
   "source": "McKinsey",
   "url": "https://patientfy.ai/blog/longevity-medicine-market-2026"
  },
  {
   "id": "concierge",
   "value": "$19.4B",
   "label": "US concierge medicine market by 2034",
   "note": "From about $8B in 2025. Longevity services are overwhelmingly elective, cash-pay, and increasingly sold through membership and concierge structures.",
   "source": "Cited in Patientfy longevity market map",
   "url": "https://patientfy.ai/blog/longevity-medicine-market-2026"
  },
  {
   "id": "glp1",
   "value": "1 in 8",
   "label": "US adults currently taking a GLP-1",
   "note": "For a hormone and longevity practice this is a front door, not a fad line item.",
   "source": "KFF",
   "url": "https://patientfy.ai/blog/longevity-medicine-market-2026"
  },
  {
   "id": "longevity-retreats",
   "value": "$11.1B",
   "label": "Longevity retreats market, 2026",
   "note": "From $9.82B in 2025, projected to $17.8B at a 12.6% CAGR.",
   "source": "Research and Markets",
   "url": "https://www.researchandmarkets.com/reports/6226679/longevity-retreats-market-report"
  }
 ],
 "catchment": [
  {
   "id": "income",
   "value": "$129,942",
   "label": "Playa Vista median household income",
   "note": "Against a Los Angeles County median well below it. This is a cash-pay catchment.",
   "source": "US Census Bureau, via Point2Homes",
   "url": "https://www.point2homes.com/US/Neighborhood/CA/Los-Angeles/Playa-Vista-Demographics.html"
  },
  {
   "id": "tech-companies",
   "value": "500+",
   "label": "Technology companies in Silicon Beach",
   "note": "The Westside tech corridor that Playa Vista sits at the center of.",
   "source": "Wikipedia, Silicon Beach",
   "url": "https://en.wikipedia.org/wiki/Silicon_Beach"
  },
  {
   "id": "campus-jobs",
   "value": "~5,100",
   "label": "Employed at The Campus at Playa Vista",
   "note": "Up from roughly 2,000 in 2015, a 150% increase. A dense, high-income daytime population inside walking distance.",
   "source": "Los Angeles Business Journal",
   "url": "https://labusinessjournal.com/real-estate/workers-silicon-beach-find-coast-costly/"
  }
 ],
 "geography": [
  "Playa Vista",
  "Marina del Rey",
  "Culver City",
  "Venice",
  "Santa Monica",
  "Playa del Rey",
  "El Segundo",
  "Westchester",
  "Mar Vista",
  "Manhattan Beach"
 ],
 "scenarios": {
  "lean": {
   "key": "lean",
   "label": "Lean",
   "projectCost": 3500000,
   "sqft": 4500,
   "tagline": "Leased equipment, tighter footprint, fastest path to positive cash flow.",
   "equipmentStrategy": "Leased",
   "stations": {
    "treatment": 2,
    "ivchair": 6,
    "sauna": 1,
    "plunge": 2,
    "aescape": 1,
    "ammortal": 1,
    "hbot": 1,
    "diagnostic": 1,
    "recovery": 3
   },
   "foundingMembers": 100,
   "space": [
    [
     "Arrival, concierge, retail",
     300
    ],
    [
     "The Lounge",
     600
    ],
    [
     "Contrast suite (1 sauna, 2 plunges)",
     420
    ],
    [
     "Recovery floor",
     700
    ],
    [
     "IV and regenerative lounge (6 chairs)",
     560
    ],
    [
     "Treatment rooms (2)",
     400
    ],
    [
     "Diagnostics and consult",
     350
    ],
    [
     "Locker, shower, changing",
     330
    ],
    [
     "Staff, MEP, storage, circulation",
     840
    ]
   ],
   "opex": {
    "Rent (4,500 SF NNN)": 24750,
    "Clinical and club staff": 88000,
    "Admin and management": 22000,
    "Marketing and member acquisition": 20000,
    "Malpractice and liability": 10000,
    "Equipment leases": 34000,
    "Utilities, software, member platform": 13000,
    "Licensing and compliance": 5000
   },
   "useOfFunds": [
    [
     "Buildout and tenant improvements (4,500 SF @ ~$210/SF)",
     945000
    ],
    [
     "Wet areas: sauna, plunges, drainage, ventilation",
     285000
    ],
    [
     "Equipment lease deposits and financed upfront",
     382000
    ],
    [
     "FF&E, lounge, millwork, retail",
     395000
    ],
    [
     "Pre-opening: licensing, legal, insurance, hiring",
     265000
    ],
    [
     "Brand, launch, founding member campaign",
     190000
    ],
    [
     "Working capital and debt service reserve",
     1038000
    ]
   ],
   "lines": [
    {
     "id": "aescape",
     "name": "Aescape Robotic Massage",
     "cat": "Recovery",
     "margin": 0.82,
     "lo": 60,
     "hi": 80,
     "room": "aescape",
     "sessions": 110,
     "price": 70,
     "gross": 7700,
     "cogs": 1386.0000000000005,
     "net": 6314
    },
    {
     "id": "ammortal",
     "name": "Ammortal Chamber",
     "cat": "Recovery",
     "margin": 0.82,
     "lo": 90,
     "hi": 150,
     "room": "ammortal",
     "sessions": 70,
     "price": 120,
     "gross": 8400,
     "cogs": 1512.0000000000005,
     "net": 6888
    },
    {
     "id": "redlight",
     "name": "Red Light Therapy",
     "cat": "Recovery",
     "margin": 0.82,
     "lo": 50,
     "hi": 100,
     "room": "recovery",
     "sessions": 50,
     "price": 75,
     "gross": 3750,
     "cogs": 675.0000000000002,
     "net": 3075
    },
    {
     "id": "hbot",
     "name": "Hyperbaric Oxygen",
     "cat": "Recovery",
     "margin": 0.8,
     "lo": 150,
     "hi": 250,
     "room": "hbot",
     "sessions": 55,
     "price": 200,
     "gross": 11000,
     "cogs": 2199.9999999999995,
     "net": 8800
    },
    {
     "id": "prp",
     "name": "PRP Injections",
     "cat": "Regenerative",
     "margin": 0.78,
     "lo": 800,
     "hi": 1500,
     "room": "treatment",
     "sessions": 36,
     "price": 1150,
     "gross": 41400,
     "cogs": 9107.999999999998,
     "net": 32292
    },
    {
     "id": "compress",
     "name": "Compression / NeuFit",
     "cat": "Recovery",
     "margin": 0.78,
     "lo": 75,
     "hi": 150,
     "room": "recovery",
     "sessions": 50,
     "price": 113,
     "gross": 5650,
     "cogs": 1242.9999999999998,
     "net": 4407
    },
    {
     "id": "hormone",
     "name": "Hormone / Peptide / GLP",
     "cat": "Regenerative",
     "margin": 0.75,
     "lo": 400,
     "hi": 800,
     "room": "treatment",
     "sessions": 30,
     "price": 600,
     "gross": 18000,
     "cogs": 4500,
     "net": 13500
    },
    {
     "id": "iv",
     "name": "IV Therapy (NAD+ / Drips)",
     "cat": "Regenerative",
     "margin": 0.72,
     "lo": 350,
     "hi": 1000,
     "room": "ivchair",
     "sessions": 85,
     "price": 675,
     "gross": 57375,
     "cogs": 16065.000000000002,
     "net": 41310
    },
    {
     "id": "botox",
     "name": "Botox & Fillers",
     "cat": "Aesthetics",
     "margin": 0.7,
     "lo": 500,
     "hi": 950,
     "room": "treatment",
     "sessions": 58,
     "price": 725,
     "gross": 42050,
     "cogs": 12615.000000000002,
     "net": 29434.999999999996
    },
    {
     "id": "laser",
     "name": "Laser Platform",
     "cat": "Aesthetics",
     "margin": 0.7,
     "lo": 500,
     "hi": 1200,
     "room": "treatment",
     "sessions": 20,
     "price": 850,
     "gross": 17000,
     "cogs": 5100.000000000001,
     "net": 11900
    },
    {
     "id": "biometric",
     "name": "Advanced Biometrics",
     "cat": "Diagnostics",
     "margin": 0.7,
     "lo": 150,
     "hi": 300,
     "room": "diagnostic",
     "sessions": 14,
     "price": 225,
     "gross": 3150,
     "cogs": 945.0000000000001,
     "net": 2205
    },
    {
     "id": "morpheus",
     "name": "Morpheus8 RF Microneedling",
     "cat": "Aesthetics",
     "margin": 0.68,
     "lo": 835,
     "hi": 1500,
     "room": "treatment",
     "sessions": 20,
     "price": 1168,
     "gross": 23360,
     "cogs": 7475.199999999999,
     "net": 15884.800000000001
    },
    {
     "id": "dna",
     "name": "DNA Analysis",
     "cat": "Diagnostics",
     "margin": 0.67,
     "lo": 300,
     "hi": 500,
     "room": "diagnostic",
     "sessions": 11,
     "price": 400,
     "gross": 4400,
     "cogs": 1451.9999999999998,
     "net": 2948
    },
    {
     "id": "emsculpt",
     "name": "Emsculpt",
     "cat": "Aesthetics",
     "margin": 0.67,
     "lo": 750,
     "hi": 1200,
     "room": "treatment",
     "sessions": 20,
     "price": 975,
     "gross": 19500,
     "cogs": 6434.999999999999,
     "net": 13065
    },
    {
     "id": "dutch",
     "name": "DUTCH Testing",
     "cat": "Diagnostics",
     "margin": 0.65,
     "lo": 400,
     "hi": 650,
     "room": "diagnostic",
     "sessions": 14,
     "price": 525,
     "gross": 7350,
     "cogs": 2572.5,
     "net": 4777.5
    },
    {
     "id": "coolsculpt",
     "name": "CoolSculpting",
     "cat": "Aesthetics",
     "margin": 0.65,
     "lo": 700,
     "hi": 1200,
     "room": "treatment",
     "sessions": 14,
     "price": 950,
     "gross": 13300,
     "cogs": 4655,
     "net": 8645
    },
    {
     "id": "dexa",
     "name": "DEXA Scan",
     "cat": "Diagnostics",
     "margin": 0.62,
     "lo": 200,
     "hi": 350,
     "room": "diagnostic",
     "sessions": 14,
     "price": 275,
     "gross": 3850,
     "cogs": 1463,
     "net": 2387
    },
    {
     "id": "bleph",
     "name": "Blepharoplasty (facility fee)",
     "cat": "Surgery",
     "margin": 0.8,
     "lo": 2200,
     "hi": 3400,
     "room": "or",
     "facilityFee": true,
     "sessions": 0,
     "price": 2800,
     "gross": 0,
     "cogs": 0,
     "net": 0
    },
    {
     "id": "facialcon",
     "name": "Facial Contouring Surgery (facility fee)",
     "cat": "Surgery",
     "margin": 0.8,
     "lo": 2200,
     "hi": 3400,
     "room": "or",
     "facilityFee": true,
     "sessions": 0,
     "price": 2800,
     "gross": 0,
     "cogs": 0,
     "net": 0
    },
    {
     "id": "awakelipo",
     "name": "Awake Liposuction & Body Contouring (facility fee)",
     "cat": "Surgery",
     "margin": 0.78,
     "lo": 3000,
     "hi": 4600,
     "room": "or",
     "facilityFee": true,
     "sessions": 0,
     "price": 3800,
     "gross": 0,
     "cogs": 0,
     "net": 0
    },
    {
     "id": "fatgraft",
     "name": "Fat Grafting & Transfer (facility fee)",
     "cat": "Surgery",
     "margin": 0.8,
     "lo": 2200,
     "hi": 3400,
     "room": "or",
     "facilityFee": true,
     "sessions": 0,
     "price": 2800,
     "gross": 0,
     "cogs": 0,
     "net": 0
    },
    {
     "id": "hairrest",
     "name": "Hair Restoration Surgery",
     "cat": "Surgery",
     "margin": 0.74,
     "lo": 6000,
     "hi": 14000,
     "room": "treatment",
     "sessions": 0,
     "price": 10000,
     "gross": 0,
     "cogs": 0,
     "net": 0
    },
    {
     "id": "officesurg",
     "name": "Office Surgical Procedures",
     "cat": "Surgery",
     "margin": 0.76,
     "lo": 900,
     "hi": 3500,
     "room": "treatment",
     "sessions": 0,
     "price": 2200,
     "gross": 0,
     "cogs": 0,
     "net": 0
    },
    {
     "id": "ablative",
     "name": "Ablative Laser & Skin Tightening",
     "cat": "Surgery",
     "margin": 0.73,
     "lo": 2500,
     "hi": 6000,
     "room": "treatment",
     "sessions": 0,
     "price": 4250,
     "gross": 0,
     "cogs": 0,
     "net": 0
    }
   ],
   "rackValue": 287235,
   "serviceCogs": 79401.7,
   "redeemed": 109000,
   "alaCarteGross": 178235,
   "memberDiscount": 14258.800000000001,
   "alaCarteNet": 163976.2,
   "membershipLines": [
    {
     "id": "friends",
     "name": "Friends of L&K",
     "count": 750,
     "monthly": 18750
    },
    {
     "id": "resident",
     "name": "Resident",
     "count": 300,
     "monthly": 135000
    },
    {
     "id": "longevity",
     "name": "Longevity",
     "count": 32,
     "monthly": 40000
    }
   ],
   "membershipRevenue": 193750,
   "accessRevenue": 14250,
   "totalRevenue": 371976.2,
   "circuitCogs": 15568,
   "totalCogs": 94969.7,
   "netAfterCogs": 277006.5,
   "blendedMargin": 0.744688773098924,
   "serviceMargin": 0.7235653733006074,
   "redemptionRatio": 0.6228571428571429,
   "opexTotal": 216750,
   "operatingIncome": 60256.5,
   "operatingIncomeAnnual": 723078,
   "operatingMargin": 0.16199020259898347,
   "revenueAnnual": 4463714.4,
   "injectionFloor": 350000,
   "injectionPlanning": 700000,
   "loanFloor": 3150000,
   "loanPlanning": 2800000,
   "isPrivate": false,
   "injectionPct": 0.1,
   "monthlyDebt": 45127,
   "annualDebt": 541523,
   "interestOnlyPayment": 24938,
   "dscr": 1.3352674553616015,
   "rateBand": [
    {
     "rate": 0.095,
     "monthly": 45127,
     "annual": 541523,
     "dscr": 1.3352674553616015
    },
    {
     "rate": 0.105,
     "monthly": 46813,
     "annual": 561758,
     "dscr": 1.2871691390755529
    },
    {
     "rate": 0.115,
     "monthly": 48533,
     "annual": 582401,
     "dscr": 1.241546871631598
    }
   ],
   "founding": {
    "count": 100,
    "prepay": 3600,
    "discount": 0.33333333333333337,
    "proceeds": 360000
   },
   "capacity": {
    "operatingRoom": null,
    "circuit": {
     "theoretical": 6384,
     "practical": 3192,
     "demand": 1946,
     "utilization": 0.6096491228070177,
     "headroom": 1246
    },
    "treatmentRooms": {
     "theoretical": 520,
     "practical": 338,
     "demand": 198,
     "utilization": 0.5857988165680473,
     "headroom": 140
    }
   },
   "ramp": [
    {
     "month": 1,
     "maturity": 0,
     "open": false,
     "revenue": 0,
     "cogs": 0,
     "opex": 75863,
     "operating": -75862,
     "debtService": 12469,
     "foundingProceeds": 60000,
     "netCash": -28331,
     "cumulativeCash": -28331
    },
    {
     "month": 2,
     "maturity": 0,
     "open": false,
     "revenue": 0,
     "cogs": 0,
     "opex": 75863,
     "operating": -75862,
     "debtService": 12469,
     "foundingProceeds": 60000,
     "netCash": -28331,
     "cumulativeCash": -56662
    },
    {
     "month": 3,
     "maturity": 0,
     "open": false,
     "revenue": 0,
     "cogs": 0,
     "opex": 75863,
     "operating": -75862,
     "debtService": 12469,
     "foundingProceeds": 60000,
     "netCash": -28331,
     "cumulativeCash": -84994
    },
    {
     "month": 4,
     "maturity": 0,
     "open": false,
     "revenue": 0,
     "cogs": 0,
     "opex": 75863,
     "operating": -75862,
     "debtService": 12469,
     "foundingProceeds": 60000,
     "netCash": -28331,
     "cumulativeCash": -113325
    },
    {
     "month": 5,
     "maturity": 0,
     "open": false,
     "revenue": 0,
     "cogs": 0,
     "opex": 75863,
     "operating": -75862,
     "debtService": 12469,
     "foundingProceeds": 60000,
     "netCash": -28331,
     "cumulativeCash": -141656
    },
    {
     "month": 6,
     "maturity": 0,
     "open": false,
     "revenue": 0,
     "cogs": 0,
     "opex": 75863,
     "operating": -75862,
     "debtService": 12469,
     "foundingProceeds": 60000,
     "netCash": -28331,
     "cumulativeCash": -169987
    },
    {
     "month": 7,
     "maturity": 0.15,
     "open": true,
     "revenue": 55796,
     "cogs": 14245,
     "opex": 151725,
     "operating": -110174,
     "debtService": 24938,
     "foundingProceeds": 0,
     "netCash": -135112,
     "cumulativeCash": -305099
    },
    {
     "month": 8,
     "maturity": 0.22,
     "open": true,
     "revenue": 81835,
     "cogs": 20893,
     "opex": 151725,
     "operating": -90784,
     "debtService": 24938,
     "foundingProceeds": 0,
     "netCash": -115721,
     "cumulativeCash": -420820
    },
    {
     "month": 9,
     "maturity": 0.3,
     "open": true,
     "revenue": 111593,
     "cogs": 28491,
     "opex": 151725,
     "operating": -68623,
     "debtService": 24938,
     "foundingProceeds": 0,
     "netCash": -93561,
     "cumulativeCash": -514381
    },
    {
     "month": 10,
     "maturity": 0.36,
     "open": true,
     "revenue": 133911,
     "cogs": 34189,
     "opex": 151725,
     "operating": -52003,
     "debtService": 24938,
     "foundingProceeds": 0,
     "netCash": -76940,
     "cumulativeCash": -591321
    },
    {
     "month": 11,
     "maturity": 0.42,
     "open": true,
     "revenue": 156230,
     "cogs": 39887,
     "opex": 151725,
     "operating": -35382,
     "debtService": 24938,
     "foundingProceeds": 0,
     "netCash": -60320,
     "cumulativeCash": -651641
    },
    {
     "month": 12,
     "maturity": 0.48,
     "open": true,
     "revenue": 178549,
     "cogs": 45585,
     "opex": 151725,
     "operating": -18762,
     "debtService": 24938,
     "foundingProceeds": 0,
     "netCash": -43699,
     "cumulativeCash": -695340
    },
    {
     "month": 13,
     "maturity": 0.54,
     "open": true,
     "revenue": 200867,
     "cogs": 51284,
     "opex": 151725,
     "operating": -2141,
     "debtService": 24938,
     "foundingProceeds": 0,
     "netCash": -27079,
     "cumulativeCash": -722419
    },
    {
     "month": 14,
     "maturity": 0.58,
     "open": true,
     "revenue": 215746,
     "cogs": 55082,
     "opex": 151725,
     "operating": 8939,
     "debtService": 24938,
     "foundingProceeds": 0,
     "netCash": -15999,
     "cumulativeCash": -738418
    },
    {
     "month": 15,
     "maturity": 0.62,
     "open": true,
     "revenue": 230625,
     "cogs": 58881,
     "opex": 151725,
     "operating": 20019,
     "debtService": 24938,
     "foundingProceeds": 0,
     "netCash": -4918,
     "cumulativeCash": -743336
    },
    {
     "month": 16,
     "maturity": 0.66,
     "open": true,
     "revenue": 245504,
     "cogs": 62680,
     "opex": 151725,
     "operating": 31099,
     "debtService": 24938,
     "foundingProceeds": 0,
     "netCash": 6162,
     "cumulativeCash": -737174
    },
    {
     "month": 17,
     "maturity": 0.7,
     "open": true,
     "revenue": 260383,
     "cogs": 66479,
     "opex": 151725,
     "operating": 42180,
     "debtService": 24938,
     "foundingProceeds": 0,
     "netCash": 17242,
     "cumulativeCash": -719932
    },
    {
     "month": 18,
     "maturity": 0.73,
     "open": true,
     "revenue": 271543,
     "cogs": 69328,
     "opex": 158228,
     "operating": 43987,
     "debtService": 24938,
     "foundingProceeds": 0,
     "netCash": 19050,
     "cumulativeCash": -700883
    },
    {
     "month": 19,
     "maturity": 0.76,
     "open": true,
     "revenue": 282702,
     "cogs": 72177,
     "opex": 164730,
     "operating": 45795,
     "debtService": 45127,
     "foundingProceeds": 0,
     "netCash": 668,
     "cumulativeCash": -700215
    },
    {
     "month": 20,
     "maturity": 0.79,
     "open": true,
     "revenue": 293861,
     "cogs": 75026,
     "opex": 171233,
     "operating": 47603,
     "debtService": 45127,
     "foundingProceeds": 0,
     "netCash": 2476,
     "cumulativeCash": -697739
    },
    {
     "month": 21,
     "maturity": 0.82,
     "open": true,
     "revenue": 305020,
     "cogs": 77875,
     "opex": 177735,
     "operating": 49410,
     "debtService": 45127,
     "foundingProceeds": 0,
     "netCash": 4283,
     "cumulativeCash": -693455
    },
    {
     "month": 22,
     "maturity": 0.85,
     "open": true,
     "revenue": 316180,
     "cogs": 80724,
     "opex": 184238,
     "operating": 51218,
     "debtService": 45127,
     "foundingProceeds": 0,
     "netCash": 6091,
     "cumulativeCash": -687364
    },
    {
     "month": 23,
     "maturity": 0.87,
     "open": true,
     "revenue": 323619,
     "cogs": 82624,
     "opex": 188573,
     "operating": 52423,
     "debtService": 45127,
     "foundingProceeds": 0,
     "netCash": 7296,
     "cumulativeCash": -680068
    },
    {
     "month": 24,
     "maturity": 0.89,
     "open": true,
     "revenue": 331059,
     "cogs": 84523,
     "opex": 192908,
     "operating": 53628,
     "debtService": 45127,
     "foundingProceeds": 0,
     "netCash": 8501,
     "cumulativeCash": -671567
    },
    {
     "month": 25,
     "maturity": 0.91,
     "open": true,
     "revenue": 338498,
     "cogs": 86422,
     "opex": 197243,
     "operating": 54833,
     "debtService": 45127,
     "foundingProceeds": 0,
     "netCash": 9707,
     "cumulativeCash": -661860
    },
    {
     "month": 26,
     "maturity": 0.93,
     "open": true,
     "revenue": 345938,
     "cogs": 88322,
     "opex": 201578,
     "operating": 56039,
     "debtService": 45127,
     "foundingProceeds": 0,
     "netCash": 10912,
     "cumulativeCash": -650949
    },
    {
     "month": 27,
     "maturity": 0.94,
     "open": true,
     "revenue": 349658,
     "cogs": 89272,
     "opex": 203745,
     "operating": 56641,
     "debtService": 45127,
     "foundingProceeds": 0,
     "netCash": 11514,
     "cumulativeCash": -639434
    },
    {
     "month": 28,
     "maturity": 0.96,
     "open": true,
     "revenue": 357097,
     "cogs": 91171,
     "opex": 208080,
     "operating": 57846,
     "debtService": 45127,
     "foundingProceeds": 0,
     "netCash": 12719,
     "cumulativeCash": -626715
    },
    {
     "month": 29,
     "maturity": 0.97,
     "open": true,
     "revenue": 360817,
     "cogs": 92121,
     "opex": 210248,
     "operating": 58449,
     "debtService": 45127,
     "foundingProceeds": 0,
     "netCash": 13322,
     "cumulativeCash": -613393
    },
    {
     "month": 30,
     "maturity": 0.98,
     "open": true,
     "revenue": 364537,
     "cogs": 93070,
     "opex": 212415,
     "operating": 59051,
     "debtService": 45127,
     "foundingProceeds": 0,
     "netCash": 13924,
     "cumulativeCash": -599469
    },
    {
     "month": 31,
     "maturity": 0.99,
     "open": true,
     "revenue": 368256,
     "cogs": 94020,
     "opex": 214583,
     "operating": 59654,
     "debtService": 45127,
     "foundingProceeds": 0,
     "netCash": 14527,
     "cumulativeCash": -584942
    },
    {
     "month": 32,
     "maturity": 1,
     "open": true,
     "revenue": 371976,
     "cogs": 94970,
     "opex": 216750,
     "operating": 60257,
     "debtService": 45127,
     "foundingProceeds": 0,
     "netCash": 15130,
     "cumulativeCash": -569812
    },
    {
     "month": 33,
     "maturity": 1,
     "open": true,
     "revenue": 371976,
     "cogs": 94970,
     "opex": 216750,
     "operating": 60257,
     "debtService": 45127,
     "foundingProceeds": 0,
     "netCash": 15130,
     "cumulativeCash": -554682
    },
    {
     "month": 34,
     "maturity": 1,
     "open": true,
     "revenue": 371976,
     "cogs": 94970,
     "opex": 216750,
     "operating": 60257,
     "debtService": 45127,
     "foundingProceeds": 0,
     "netCash": 15130,
     "cumulativeCash": -539553
    },
    {
     "month": 35,
     "maturity": 1,
     "open": true,
     "revenue": 371976,
     "cogs": 94970,
     "opex": 216750,
     "operating": 60257,
     "debtService": 45127,
     "foundingProceeds": 0,
     "netCash": 15130,
     "cumulativeCash": -524423
    },
    {
     "month": 36,
     "maturity": 1,
     "open": true,
     "revenue": 371976,
     "cogs": 94970,
     "opex": 216750,
     "operating": 60257,
     "debtService": 45127,
     "foundingProceeds": 0,
     "netCash": 15130,
     "cumulativeCash": -509294
    }
   ],
   "breakeven": 14,
   "dscrByYear": [
    {
     "year": 1,
     "operating": -830900,
     "debt": 224442,
     "dscr": -3.7020700225447998,
     "passes": false
    },
    {
     "year": 2,
     "operating": 444160,
     "debt": 420390,
     "dscr": 1.0565427341278337,
     "passes": false
    },
    {
     "year": 3,
     "operating": 703798,
     "debt": 541524,
     "dscr": 1.299661695511187,
     "passes": true
    }
   ],
   "band": [
    {
     "label": "Low",
     "tag": "Slow member ramp, 72% of base volume",
     "revenue": 267823,
     "netAfterCogs": 199445,
     "operating": -17305,
     "annual": -207664,
     "dscr": -0.3834811079123141
    },
    {
     "label": "Base",
     "tag": "Stated assumptions at stabilization",
     "revenue": 371976,
     "netAfterCogs": 277007,
     "operating": 60257,
     "annual": 723078,
     "dscr": 1.3352673847648207
    },
    {
     "label": "Upside",
     "tag": "Waitlist demand, 128% of base volume",
     "revenue": 476130,
     "netAfterCogs": 354568,
     "operating": 137818,
     "annual": 1653820,
     "dscr": 3.0540158774419557
    }
   ],
   "trough": {
    "month": 15,
    "amount": -743336
   },
   "reserve": 1038000,
   "rateStressPasses": false,
   "rateStress": {
    "rate": 0.115,
    "monthly": 48533,
    "annual": 582401,
    "dscr": 1.241546871631598
   }
  },
  "ample": {
   "key": "ample",
   "label": "Ample",
   "projectCost": 5000000,
   "sqft": 5800,
   "tagline": "Full contrast suite, owned equipment, the facility the brand deserves.",
   "equipmentStrategy": "Purchased where payback justifies it",
   "stations": {
    "treatment": 3,
    "ivchair": 8,
    "sauna": 2,
    "plunge": 2,
    "aescape": 2,
    "ammortal": 2,
    "hbot": 1,
    "diagnostic": 2,
    "recovery": 4
   },
   "foundingMembers": 150,
   "space": [
    [
     "Arrival, concierge, retail",
     350
    ],
    [
     "The Lounge",
     700
    ],
    [
     "Contrast suite (2 saunas, 2 plunges)",
     550
    ],
    [
     "Recovery floor",
     900
    ],
    [
     "IV and regenerative lounge (8 chairs)",
     700
    ],
    [
     "Treatment rooms (3)",
     600
    ],
    [
     "Diagnostics and consult",
     450
    ],
    [
     "Locker, shower, changing",
     400
    ],
    [
     "Staff, MEP, storage, circulation",
     1150
    ]
   ],
   "opex": {
    "Rent (5,800 SF NNN)": 31900,
    "Clinical and club staff": 135000,
    "Admin and management": 28000,
    "Marketing and member acquisition": 30000,
    "Malpractice and liability": 12000,
    "Equipment leases": 24000,
    "Utilities, software, member platform": 16000,
    "Licensing and compliance": 6000
   },
   "useOfFunds": [
    [
     "Buildout and tenant improvements (5,800 SF @ $250/SF)",
     1450000
    ],
    [
     "Wet areas: 2 saunas, 2 plunges, steam, drainage, ventilation",
     465000
    ],
    [
     "Medical and aesthetic equipment (purchased)",
     780000
    ],
    [
     "Recovery technology: HBOT purchased, Ammortal deposit",
     182000
    ],
    [
     "FF&E, lounge, millwork, retail",
     430000
    ],
    [
     "Pre-opening: licensing, legal, insurance, hiring",
     310000
    ],
    [
     "Brand, launch, founding member campaign",
     237000
    ],
    [
     "Working capital and debt service reserve",
     1146000
    ]
   ],
   "lines": [
    {
     "id": "aescape",
     "name": "Aescape Robotic Massage",
     "cat": "Recovery",
     "margin": 0.82,
     "lo": 60,
     "hi": 80,
     "room": "aescape",
     "sessions": 200,
     "price": 70,
     "gross": 14000,
     "cogs": 2520.000000000001,
     "net": 11480
    },
    {
     "id": "ammortal",
     "name": "Ammortal Chamber",
     "cat": "Recovery",
     "margin": 0.82,
     "lo": 90,
     "hi": 150,
     "room": "ammortal",
     "sessions": 120,
     "price": 120,
     "gross": 14400,
     "cogs": 2592.000000000001,
     "net": 11808
    },
    {
     "id": "redlight",
     "name": "Red Light Therapy",
     "cat": "Recovery",
     "margin": 0.82,
     "lo": 50,
     "hi": 100,
     "room": "recovery",
     "sessions": 80,
     "price": 75,
     "gross": 6000,
     "cogs": 1080.0000000000002,
     "net": 4920
    },
    {
     "id": "hbot",
     "name": "Hyperbaric Oxygen",
     "cat": "Recovery",
     "margin": 0.8,
     "lo": 150,
     "hi": 250,
     "room": "hbot",
     "sessions": 100,
     "price": 200,
     "gross": 20000,
     "cogs": 3999.999999999999,
     "net": 16000
    },
    {
     "id": "prp",
     "name": "PRP Injections",
     "cat": "Regenerative",
     "margin": 0.78,
     "lo": 800,
     "hi": 1500,
     "room": "treatment",
     "sessions": 50,
     "price": 1150,
     "gross": 57500,
     "cogs": 12649.999999999998,
     "net": 44850
    },
    {
     "id": "compress",
     "name": "Compression / NeuFit",
     "cat": "Recovery",
     "margin": 0.78,
     "lo": 75,
     "hi": 150,
     "room": "recovery",
     "sessions": 80,
     "price": 113,
     "gross": 9040,
     "cogs": 1988.7999999999997,
     "net": 7051.2
    },
    {
     "id": "hormone",
     "name": "Hormone / Peptide / GLP",
     "cat": "Regenerative",
     "margin": 0.75,
     "lo": 400,
     "hi": 800,
     "room": "treatment",
     "sessions": 40,
     "price": 600,
     "gross": 24000,
     "cogs": 6000,
     "net": 18000
    },
    {
     "id": "iv",
     "name": "IV Therapy (NAD+ / Drips)",
     "cat": "Regenerative",
     "margin": 0.72,
     "lo": 350,
     "hi": 1000,
     "room": "ivchair",
     "sessions": 120,
     "price": 675,
     "gross": 81000,
     "cogs": 22680.000000000004,
     "net": 58320
    },
    {
     "id": "botox",
     "name": "Botox & Fillers",
     "cat": "Aesthetics",
     "margin": 0.7,
     "lo": 500,
     "hi": 950,
     "room": "treatment",
     "sessions": 80,
     "price": 725,
     "gross": 58000,
     "cogs": 17400.000000000004,
     "net": 40600
    },
    {
     "id": "laser",
     "name": "Laser Platform",
     "cat": "Aesthetics",
     "margin": 0.7,
     "lo": 500,
     "hi": 1200,
     "room": "treatment",
     "sessions": 30,
     "price": 850,
     "gross": 25500,
     "cogs": 7650.000000000001,
     "net": 17850
    },
    {
     "id": "biometric",
     "name": "Advanced Biometrics",
     "cat": "Diagnostics",
     "margin": 0.7,
     "lo": 150,
     "hi": 300,
     "room": "diagnostic",
     "sessions": 20,
     "price": 225,
     "gross": 4500,
     "cogs": 1350.0000000000002,
     "net": 3150
    },
    {
     "id": "morpheus",
     "name": "Morpheus8 RF Microneedling",
     "cat": "Aesthetics",
     "margin": 0.68,
     "lo": 835,
     "hi": 1500,
     "room": "treatment",
     "sessions": 30,
     "price": 1168,
     "gross": 35040,
     "cogs": 11212.799999999997,
     "net": 23827.2
    },
    {
     "id": "dna",
     "name": "DNA Analysis",
     "cat": "Diagnostics",
     "margin": 0.67,
     "lo": 300,
     "hi": 500,
     "room": "diagnostic",
     "sessions": 15,
     "price": 400,
     "gross": 6000,
     "cogs": 1979.9999999999998,
     "net": 4020.0000000000005
    },
    {
     "id": "emsculpt",
     "name": "Emsculpt",
     "cat": "Aesthetics",
     "margin": 0.67,
     "lo": 750,
     "hi": 1200,
     "room": "treatment",
     "sessions": 30,
     "price": 975,
     "gross": 29250,
     "cogs": 9652.499999999998,
     "net": 19597.5
    },
    {
     "id": "dutch",
     "name": "DUTCH Testing",
     "cat": "Diagnostics",
     "margin": 0.65,
     "lo": 400,
     "hi": 650,
     "room": "diagnostic",
     "sessions": 20,
     "price": 525,
     "gross": 10500,
     "cogs": 3674.9999999999995,
     "net": 6825
    },
    {
     "id": "coolsculpt",
     "name": "CoolSculpting",
     "cat": "Aesthetics",
     "margin": 0.65,
     "lo": 700,
     "hi": 1200,
     "room": "treatment",
     "sessions": 20,
     "price": 950,
     "gross": 19000,
     "cogs": 6650,
     "net": 12350
    },
    {
     "id": "dexa",
     "name": "DEXA Scan",
     "cat": "Diagnostics",
     "margin": 0.62,
     "lo": 200,
     "hi": 350,
     "room": "diagnostic",
     "sessions": 20,
     "price": 275,
     "gross": 5500,
     "cogs": 2090,
     "net": 3410
    },
    {
     "id": "bleph",
     "name": "Blepharoplasty (facility fee)",
     "cat": "Surgery",
     "margin": 0.8,
     "lo": 2200,
     "hi": 3400,
     "room": "or",
     "facilityFee": true,
     "sessions": 0,
     "price": 2800,
     "gross": 0,
     "cogs": 0,
     "net": 0
    },
    {
     "id": "facialcon",
     "name": "Facial Contouring Surgery (facility fee)",
     "cat": "Surgery",
     "margin": 0.8,
     "lo": 2200,
     "hi": 3400,
     "room": "or",
     "facilityFee": true,
     "sessions": 0,
     "price": 2800,
     "gross": 0,
     "cogs": 0,
     "net": 0
    },
    {
     "id": "awakelipo",
     "name": "Awake Liposuction & Body Contouring (facility fee)",
     "cat": "Surgery",
     "margin": 0.78,
     "lo": 3000,
     "hi": 4600,
     "room": "or",
     "facilityFee": true,
     "sessions": 0,
     "price": 3800,
     "gross": 0,
     "cogs": 0,
     "net": 0
    },
    {
     "id": "fatgraft",
     "name": "Fat Grafting & Transfer (facility fee)",
     "cat": "Surgery",
     "margin": 0.8,
     "lo": 2200,
     "hi": 3400,
     "room": "or",
     "facilityFee": true,
     "sessions": 0,
     "price": 2800,
     "gross": 0,
     "cogs": 0,
     "net": 0
    },
    {
     "id": "hairrest",
     "name": "Hair Restoration Surgery",
     "cat": "Surgery",
     "margin": 0.74,
     "lo": 6000,
     "hi": 14000,
     "room": "treatment",
     "sessions": 0,
     "price": 10000,
     "gross": 0,
     "cogs": 0,
     "net": 0
    },
    {
     "id": "officesurg",
     "name": "Office Surgical Procedures",
     "cat": "Surgery",
     "margin": 0.76,
     "lo": 900,
     "hi": 3500,
     "room": "treatment",
     "sessions": 0,
     "price": 2200,
     "gross": 0,
     "cogs": 0,
     "net": 0
    },
    {
     "id": "ablative",
     "name": "Ablative Laser & Skin Tightening",
     "cat": "Surgery",
     "margin": 0.73,
     "lo": 2500,
     "hi": 6000,
     "room": "treatment",
     "sessions": 0,
     "price": 4250,
     "gross": 0,
     "cogs": 0,
     "net": 0
    }
   ],
   "rackValue": 419230,
   "serviceCogs": 115171.1,
   "redeemed": 129500,
   "alaCarteGross": 289730,
   "memberDiscount": 23178.4,
   "alaCarteNet": 266551.6,
   "membershipLines": [
    {
     "id": "friends",
     "name": "Friends of L&K",
     "count": 900,
     "monthly": 22500
    },
    {
     "id": "resident",
     "name": "Resident",
     "count": 350,
     "monthly": 157500
    },
    {
     "id": "longevity",
     "name": "Longevity",
     "count": 40,
     "monthly": 50000
    }
   ],
   "membershipRevenue": 230000,
   "accessRevenue": 20625,
   "totalRevenue": 517176.6,
   "circuitCogs": 18760,
   "totalCogs": 133931.1,
   "netAfterCogs": 383245.5,
   "blendedMargin": 0.7410341071115747,
   "serviceMargin": 0.7252794408797081,
   "redemptionRatio": 0.6240963855421687,
   "opexTotal": 282900,
   "operatingIncome": 100345.5,
   "operatingIncomeAnnual": 1204146,
   "operatingMargin": 0.19402559976611472,
   "revenueAnnual": 6206119.199999999,
   "injectionFloor": 500000,
   "injectionPlanning": 1000000,
   "loanFloor": 4500000,
   "loanPlanning": 4000000,
   "isPrivate": false,
   "injectionPct": 0.1,
   "monthlyDebt": 64467,
   "annualDebt": 773604,
   "interestOnlyPayment": 35625,
   "dscr": 1.5565400630536341,
   "rateBand": [
    {
     "rate": 0.095,
     "monthly": 64467,
     "annual": 773604,
     "dscr": 1.5565400630536341
    },
    {
     "rate": 0.105,
     "monthly": 66876,
     "annual": 802512,
     "dscr": 1.5004711789030918
    },
    {
     "rate": 0.115,
     "monthly": 69333,
     "annual": 832001,
     "dscr": 1.4472886597315802
    }
   ],
   "founding": {
    "count": 150,
    "prepay": 3600,
    "discount": 0.33333333333333337,
    "proceeds": 540000
   },
   "capacity": {
    "operatingRoom": null,
    "circuit": {
     "theoretical": 6384,
     "practical": 3192,
     "demand": 2345,
     "utilization": 0.7346491228070177,
     "headroom": 847
    },
    "treatmentRooms": {
     "theoretical": 780,
     "practical": 507,
     "demand": 280,
     "utilization": 0.5522682445759369,
     "headroom": 227
    }
   },
   "ramp": [
    {
     "month": 1,
     "maturity": 0,
     "open": false,
     "revenue": 0,
     "cogs": 0,
     "opex": 99015,
     "operating": -99015,
     "debtService": 17813,
     "foundingProceeds": 90000,
     "netCash": -26827,
     "cumulativeCash": -26827
    },
    {
     "month": 2,
     "maturity": 0,
     "open": false,
     "revenue": 0,
     "cogs": 0,
     "opex": 99015,
     "operating": -99015,
     "debtService": 17813,
     "foundingProceeds": 90000,
     "netCash": -26827,
     "cumulativeCash": -53655
    },
    {
     "month": 3,
     "maturity": 0,
     "open": false,
     "revenue": 0,
     "cogs": 0,
     "opex": 99015,
     "operating": -99015,
     "debtService": 17813,
     "foundingProceeds": 90000,
     "netCash": -26827,
     "cumulativeCash": -80482
    },
    {
     "month": 4,
     "maturity": 0,
     "open": false,
     "revenue": 0,
     "cogs": 0,
     "opex": 99015,
     "operating": -99015,
     "debtService": 17813,
     "foundingProceeds": 90000,
     "netCash": -26827,
     "cumulativeCash": -107310
    },
    {
     "month": 5,
     "maturity": 0,
     "open": false,
     "revenue": 0,
     "cogs": 0,
     "opex": 99015,
     "operating": -99015,
     "debtService": 17813,
     "foundingProceeds": 90000,
     "netCash": -26827,
     "cumulativeCash": -134137
    },
    {
     "month": 6,
     "maturity": 0,
     "open": false,
     "revenue": 0,
     "cogs": 0,
     "opex": 99015,
     "operating": -99015,
     "debtService": 17813,
     "foundingProceeds": 90000,
     "netCash": -26827,
     "cumulativeCash": -160965
    },
    {
     "month": 7,
     "maturity": 0.15,
     "open": true,
     "revenue": 77576,
     "cogs": 20090,
     "opex": 198030,
     "operating": -140543,
     "debtService": 35625,
     "foundingProceeds": 0,
     "netCash": -176168,
     "cumulativeCash": -337133
    },
    {
     "month": 8,
     "maturity": 0.22,
     "open": true,
     "revenue": 113779,
     "cogs": 29465,
     "opex": 198030,
     "operating": -113716,
     "debtService": 35625,
     "foundingProceeds": 0,
     "netCash": -149341,
     "cumulativeCash": -486474
    },
    {
     "month": 9,
     "maturity": 0.3,
     "open": true,
     "revenue": 155153,
     "cogs": 40179,
     "opex": 198030,
     "operating": -83056,
     "debtService": 35625,
     "foundingProceeds": 0,
     "netCash": -118681,
     "cumulativeCash": -605156
    },
    {
     "month": 10,
     "maturity": 0.36,
     "open": true,
     "revenue": 186184,
     "cogs": 48215,
     "opex": 198030,
     "operating": -60062,
     "debtService": 35625,
     "foundingProceeds": 0,
     "netCash": -95687,
     "cumulativeCash": -700842
    },
    {
     "month": 11,
     "maturity": 0.42,
     "open": true,
     "revenue": 217214,
     "cogs": 56251,
     "opex": 198030,
     "operating": -37067,
     "debtService": 35625,
     "foundingProceeds": 0,
     "netCash": -72692,
     "cumulativeCash": -773534
    },
    {
     "month": 12,
     "maturity": 0.48,
     "open": true,
     "revenue": 248245,
     "cogs": 64287,
     "opex": 198030,
     "operating": -14072,
     "debtService": 35625,
     "foundingProceeds": 0,
     "netCash": -49697,
     "cumulativeCash": -823231
    },
    {
     "month": 13,
     "maturity": 0.54,
     "open": true,
     "revenue": 279275,
     "cogs": 72323,
     "opex": 198030,
     "operating": 8923,
     "debtService": 35625,
     "foundingProceeds": 0,
     "netCash": -26702,
     "cumulativeCash": -849934
    },
    {
     "month": 14,
     "maturity": 0.58,
     "open": true,
     "revenue": 299962,
     "cogs": 77680,
     "opex": 198030,
     "operating": 24252,
     "debtService": 35625,
     "foundingProceeds": 0,
     "netCash": -11373,
     "cumulativeCash": -861306
    },
    {
     "month": 15,
     "maturity": 0.62,
     "open": true,
     "revenue": 320649,
     "cogs": 83037,
     "opex": 198030,
     "operating": 39582,
     "debtService": 35625,
     "foundingProceeds": 0,
     "netCash": 3957,
     "cumulativeCash": -857349
    },
    {
     "month": 16,
     "maturity": 0.66,
     "open": true,
     "revenue": 341337,
     "cogs": 88395,
     "opex": 198030,
     "operating": 54912,
     "debtService": 35625,
     "foundingProceeds": 0,
     "netCash": 19287,
     "cumulativeCash": -838062
    },
    {
     "month": 17,
     "maturity": 0.7,
     "open": true,
     "revenue": 362024,
     "cogs": 93752,
     "opex": 198030,
     "operating": 70242,
     "debtService": 35625,
     "foundingProceeds": 0,
     "netCash": 34617,
     "cumulativeCash": -803445
    },
    {
     "month": 18,
     "maturity": 0.73,
     "open": true,
     "revenue": 377539,
     "cogs": 97770,
     "opex": 206517,
     "operating": 73252,
     "debtService": 35625,
     "foundingProceeds": 0,
     "netCash": 37627,
     "cumulativeCash": -765818
    },
    {
     "month": 19,
     "maturity": 0.76,
     "open": true,
     "revenue": 393054,
     "cogs": 101788,
     "opex": 215004,
     "operating": 76263,
     "debtService": 64467,
     "foundingProceeds": 0,
     "netCash": 11796,
     "cumulativeCash": -754022
    },
    {
     "month": 20,
     "maturity": 0.79,
     "open": true,
     "revenue": 408570,
     "cogs": 105806,
     "opex": 223491,
     "operating": 79273,
     "debtService": 64467,
     "foundingProceeds": 0,
     "netCash": 14806,
     "cumulativeCash": -739216
    },
    {
     "month": 21,
     "maturity": 0.82,
     "open": true,
     "revenue": 424085,
     "cogs": 109824,
     "opex": 231978,
     "operating": 82283,
     "debtService": 64467,
     "foundingProceeds": 0,
     "netCash": 17816,
     "cumulativeCash": -721400
    },
    {
     "month": 22,
     "maturity": 0.85,
     "open": true,
     "revenue": 439600,
     "cogs": 113841,
     "opex": 240465,
     "operating": 85294,
     "debtService": 64467,
     "foundingProceeds": 0,
     "netCash": 20827,
     "cumulativeCash": -700573
    },
    {
     "month": 23,
     "maturity": 0.87,
     "open": true,
     "revenue": 449944,
     "cogs": 116520,
     "opex": 246123,
     "operating": 87301,
     "debtService": 64467,
     "foundingProceeds": 0,
     "netCash": 22834,
     "cumulativeCash": -677740
    },
    {
     "month": 24,
     "maturity": 0.89,
     "open": true,
     "revenue": 460287,
     "cogs": 119199,
     "opex": 251781,
     "operating": 89307,
     "debtService": 64467,
     "foundingProceeds": 0,
     "netCash": 24840,
     "cumulativeCash": -652899
    },
    {
     "month": 25,
     "maturity": 0.91,
     "open": true,
     "revenue": 470631,
     "cogs": 121877,
     "opex": 257439,
     "operating": 91314,
     "debtService": 64467,
     "foundingProceeds": 0,
     "netCash": 26847,
     "cumulativeCash": -626052
    },
    {
     "month": 26,
     "maturity": 0.93,
     "open": true,
     "revenue": 480974,
     "cogs": 124556,
     "opex": 263097,
     "operating": 93321,
     "debtService": 64467,
     "foundingProceeds": 0,
     "netCash": 28854,
     "cumulativeCash": -597198
    },
    {
     "month": 27,
     "maturity": 0.94,
     "open": true,
     "revenue": 486146,
     "cogs": 125895,
     "opex": 265926,
     "operating": 94325,
     "debtService": 64467,
     "foundingProceeds": 0,
     "netCash": 29858,
     "cumulativeCash": -567340
    },
    {
     "month": 28,
     "maturity": 0.96,
     "open": true,
     "revenue": 496490,
     "cogs": 128574,
     "opex": 271584,
     "operating": 96332,
     "debtService": 64467,
     "foundingProceeds": 0,
     "netCash": 31865,
     "cumulativeCash": -535475
    },
    {
     "month": 29,
     "maturity": 0.97,
     "open": true,
     "revenue": 501661,
     "cogs": 129913,
     "opex": 274413,
     "operating": 97335,
     "debtService": 64467,
     "foundingProceeds": 0,
     "netCash": 32868,
     "cumulativeCash": -502607
    },
    {
     "month": 30,
     "maturity": 0.98,
     "open": true,
     "revenue": 506833,
     "cogs": 131252,
     "opex": 277242,
     "operating": 98339,
     "debtService": 64467,
     "foundingProceeds": 0,
     "netCash": 33872,
     "cumulativeCash": -468736
    },
    {
     "month": 31,
     "maturity": 0.99,
     "open": true,
     "revenue": 512005,
     "cogs": 132592,
     "opex": 280071,
     "operating": 99342,
     "debtService": 64467,
     "foundingProceeds": 0,
     "netCash": 34875,
     "cumulativeCash": -433861
    },
    {
     "month": 32,
     "maturity": 1,
     "open": true,
     "revenue": 517177,
     "cogs": 133931,
     "opex": 282900,
     "operating": 100346,
     "debtService": 64467,
     "foundingProceeds": 0,
     "netCash": 35878,
     "cumulativeCash": -397982
    },
    {
     "month": 33,
     "maturity": 1,
     "open": true,
     "revenue": 517177,
     "cogs": 133931,
     "opex": 282900,
     "operating": 100346,
     "debtService": 64467,
     "foundingProceeds": 0,
     "netCash": 35878,
     "cumulativeCash": -362104
    },
    {
     "month": 34,
     "maturity": 1,
     "open": true,
     "revenue": 517177,
     "cogs": 133931,
     "opex": 282900,
     "operating": 100346,
     "debtService": 64467,
     "foundingProceeds": 0,
     "netCash": 35878,
     "cumulativeCash": -326225
    },
    {
     "month": 35,
     "maturity": 1,
     "open": true,
     "revenue": 517177,
     "cogs": 133931,
     "opex": 282900,
     "operating": 100346,
     "debtService": 64467,
     "foundingProceeds": 0,
     "netCash": 35878,
     "cumulativeCash": -290347
    },
    {
     "month": 36,
     "maturity": 1,
     "open": true,
     "revenue": 517177,
     "cogs": 133931,
     "opex": 282900,
     "operating": 100346,
     "debtService": 64467,
     "foundingProceeds": 0,
     "netCash": 35878,
     "cumulativeCash": -254468
    }
   ],
   "breakeven": 13,
   "dscrByYear": [
    {
     "year": 1,
     "operating": -1042606,
     "debt": 320628,
     "dscr": -3.2517621667477576,
     "passes": false
    },
    {
     "year": 2,
     "operating": 770884,
     "debt": 600552,
     "dscr": 1.2836257309941521,
     "passes": true
    },
    {
     "year": 3,
     "operating": 1172038,
     "debt": 773604,
     "dscr": 1.5150361166695105,
     "passes": true
    }
   ],
   "band": [
    {
     "label": "Low",
     "tag": "Slow member ramp, 72% of base volume",
     "revenue": 372367,
     "netAfterCogs": 275937,
     "operating": -6963,
     "annual": -83559,
     "dscr": -0.10801247149704576
    },
    {
     "label": "Base",
     "tag": "Stated assumptions at stabilization",
     "revenue": 517177,
     "netAfterCogs": 383246,
     "operating": 100346,
     "annual": 1204146,
     "dscr": 1.5565405556331147
    },
    {
     "label": "Upside",
     "tag": "Waitlist demand, 128% of base volume",
     "revenue": 661986,
     "netAfterCogs": 490554,
     "operating": 207654,
     "annual": 2491851,
     "dscr": 3.221093582763273
    }
   ],
   "trough": {
    "month": 14,
    "amount": -861306
   },
   "reserve": 1146000,
   "rateStressPasses": true,
   "rateStress": {
    "rate": 0.115,
    "monthly": 69333,
    "annual": 832001,
    "dscr": 1.4472886597315802
   }
  },
  "surgical": {
   "key": "surgical",
   "label": "Surgical",
   "projectCost": 5550000,
   "sqft": 6700,
   "tagline": "Everything in the ample case, plus one accredited office-based surgery suite.",
   "equipmentStrategy": "Purchased where payback justifies it, surgical equipment part leased",
   "stations": {
    "treatment": 3,
    "ivchair": 8,
    "sauna": 2,
    "plunge": 2,
    "aescape": 2,
    "ammortal": 2,
    "hbot": 1,
    "diagnostic": 2,
    "recovery": 4,
    "or": 1
   },
   "foundingMembers": 150,
   "space": [
    [
     "Arrival, concierge, retail",
     350
    ],
    [
     "The Lounge",
     700
    ],
    [
     "Contrast suite (2 saunas, 2 plunges)",
     550
    ],
    [
     "Recovery floor",
     900
    ],
    [
     "IV and regenerative lounge (8 chairs)",
     700
    ],
    [
     "Treatment rooms (3)",
     600
    ],
    [
     "Diagnostics and consult",
     450
    ],
    [
     "Operating room",
     350
    ],
    [
     "Pre-op and PACU (3 monitored bays)",
     220
    ],
    [
     "Sterile processing",
     110
    ],
    [
     "Sterile supply",
     90
    ],
    [
     "Soiled utility",
     50
    ],
    [
     "Surgical suite circulation",
     80
    ],
    [
     "Locker, shower, changing",
     400
    ],
    [
     "Staff, MEP, storage, circulation",
     1150
    ]
   ],
   "opex": {
    "Rent (6,700 SF NNN)": 36850,
    "Clinical and club staff": 165000,
    "Admin and management": 30000,
    "Marketing and member acquisition": 32000,
    "Malpractice and liability": 26000,
    "Equipment leases": 37300,
    "Utilities, software, member platform": 18500,
    "Licensing, compliance and accreditation": 10000
   },
   "useOfFunds": [
    [
     "Buildout and tenant improvements (5,800 SF clinic and club @ $250/SF)",
     1450000
    ],
    [
     "Surgical suite buildout (900 SF @ $320/SF, OR-grade HVAC and finishes)",
     288000
    ],
    [
     "Medical gas, emergency power, life-safety branch for the suite",
     100000
    ],
    [
     "Wet areas: 2 saunas, 2 plunges, steam, drainage, ventilation",
     465000
    ],
    [
     "Medical and aesthetic equipment (purchased)",
     450000
    ],
    [
     "Surgical capital equipment (balance leased)",
     200000
    ],
    [
     "Recovery technology: HBOT purchased, Ammortal deposit",
     182000
    ],
    [
     "FF&E, lounge, millwork, retail",
     400000
    ],
    [
     "Pre-opening: licensing, legal, insurance, hiring, transfer agreement",
     310000
    ],
    [
     "Accreditation: Quad A survey, policies, QA/PI program, staff training",
     110000
    ],
    [
     "Brand, launch, founding member campaign",
     200000
    ],
    [
     "Working capital and debt service reserve",
     1395000
    ]
   ],
   "lines": [
    {
     "id": "aescape",
     "name": "Aescape Robotic Massage",
     "cat": "Recovery",
     "margin": 0.82,
     "lo": 60,
     "hi": 80,
     "room": "aescape",
     "sessions": 200,
     "price": 70,
     "gross": 14000,
     "cogs": 2520.000000000001,
     "net": 11480
    },
    {
     "id": "ammortal",
     "name": "Ammortal Chamber",
     "cat": "Recovery",
     "margin": 0.82,
     "lo": 90,
     "hi": 150,
     "room": "ammortal",
     "sessions": 120,
     "price": 120,
     "gross": 14400,
     "cogs": 2592.000000000001,
     "net": 11808
    },
    {
     "id": "redlight",
     "name": "Red Light Therapy",
     "cat": "Recovery",
     "margin": 0.82,
     "lo": 50,
     "hi": 100,
     "room": "recovery",
     "sessions": 80,
     "price": 75,
     "gross": 6000,
     "cogs": 1080.0000000000002,
     "net": 4920
    },
    {
     "id": "hbot",
     "name": "Hyperbaric Oxygen",
     "cat": "Recovery",
     "margin": 0.8,
     "lo": 150,
     "hi": 250,
     "room": "hbot",
     "sessions": 100,
     "price": 200,
     "gross": 20000,
     "cogs": 3999.999999999999,
     "net": 16000
    },
    {
     "id": "prp",
     "name": "PRP Injections",
     "cat": "Regenerative",
     "margin": 0.78,
     "lo": 800,
     "hi": 1500,
     "room": "treatment",
     "sessions": 50,
     "price": 1150,
     "gross": 57500,
     "cogs": 12649.999999999998,
     "net": 44850
    },
    {
     "id": "compress",
     "name": "Compression / NeuFit",
     "cat": "Recovery",
     "margin": 0.78,
     "lo": 75,
     "hi": 150,
     "room": "recovery",
     "sessions": 80,
     "price": 113,
     "gross": 9040,
     "cogs": 1988.7999999999997,
     "net": 7051.2
    },
    {
     "id": "hormone",
     "name": "Hormone / Peptide / GLP",
     "cat": "Regenerative",
     "margin": 0.75,
     "lo": 400,
     "hi": 800,
     "room": "treatment",
     "sessions": 40,
     "price": 600,
     "gross": 24000,
     "cogs": 6000,
     "net": 18000
    },
    {
     "id": "iv",
     "name": "IV Therapy (NAD+ / Drips)",
     "cat": "Regenerative",
     "margin": 0.72,
     "lo": 350,
     "hi": 1000,
     "room": "ivchair",
     "sessions": 120,
     "price": 675,
     "gross": 81000,
     "cogs": 22680.000000000004,
     "net": 58320
    },
    {
     "id": "botox",
     "name": "Botox & Fillers",
     "cat": "Aesthetics",
     "margin": 0.7,
     "lo": 500,
     "hi": 950,
     "room": "treatment",
     "sessions": 80,
     "price": 725,
     "gross": 58000,
     "cogs": 17400.000000000004,
     "net": 40600
    },
    {
     "id": "laser",
     "name": "Laser Platform",
     "cat": "Aesthetics",
     "margin": 0.7,
     "lo": 500,
     "hi": 1200,
     "room": "treatment",
     "sessions": 30,
     "price": 850,
     "gross": 25500,
     "cogs": 7650.000000000001,
     "net": 17850
    },
    {
     "id": "biometric",
     "name": "Advanced Biometrics",
     "cat": "Diagnostics",
     "margin": 0.7,
     "lo": 150,
     "hi": 300,
     "room": "diagnostic",
     "sessions": 20,
     "price": 225,
     "gross": 4500,
     "cogs": 1350.0000000000002,
     "net": 3150
    },
    {
     "id": "morpheus",
     "name": "Morpheus8 RF Microneedling",
     "cat": "Aesthetics",
     "margin": 0.68,
     "lo": 835,
     "hi": 1500,
     "room": "treatment",
     "sessions": 30,
     "price": 1168,
     "gross": 35040,
     "cogs": 11212.799999999997,
     "net": 23827.2
    },
    {
     "id": "dna",
     "name": "DNA Analysis",
     "cat": "Diagnostics",
     "margin": 0.67,
     "lo": 300,
     "hi": 500,
     "room": "diagnostic",
     "sessions": 15,
     "price": 400,
     "gross": 6000,
     "cogs": 1979.9999999999998,
     "net": 4020.0000000000005
    },
    {
     "id": "emsculpt",
     "name": "Emsculpt",
     "cat": "Aesthetics",
     "margin": 0.67,
     "lo": 750,
     "hi": 1200,
     "room": "treatment",
     "sessions": 30,
     "price": 975,
     "gross": 29250,
     "cogs": 9652.499999999998,
     "net": 19597.5
    },
    {
     "id": "dutch",
     "name": "DUTCH Testing",
     "cat": "Diagnostics",
     "margin": 0.65,
     "lo": 400,
     "hi": 650,
     "room": "diagnostic",
     "sessions": 20,
     "price": 525,
     "gross": 10500,
     "cogs": 3674.9999999999995,
     "net": 6825
    },
    {
     "id": "coolsculpt",
     "name": "CoolSculpting",
     "cat": "Aesthetics",
     "margin": 0.65,
     "lo": 700,
     "hi": 1200,
     "room": "treatment",
     "sessions": 20,
     "price": 950,
     "gross": 19000,
     "cogs": 6650,
     "net": 12350
    },
    {
     "id": "dexa",
     "name": "DEXA Scan",
     "cat": "Diagnostics",
     "margin": 0.62,
     "lo": 200,
     "hi": 350,
     "room": "diagnostic",
     "sessions": 20,
     "price": 275,
     "gross": 5500,
     "cogs": 2090,
     "net": 3410
    },
    {
     "id": "bleph",
     "name": "Blepharoplasty (facility fee)",
     "cat": "Surgery",
     "margin": 0.8,
     "lo": 2200,
     "hi": 3400,
     "room": "or",
     "facilityFee": true,
     "sessions": 7,
     "price": 2800,
     "gross": 19600,
     "cogs": 3919.999999999999,
     "net": 15680
    },
    {
     "id": "facialcon",
     "name": "Facial Contouring Surgery (facility fee)",
     "cat": "Surgery",
     "margin": 0.8,
     "lo": 2200,
     "hi": 3400,
     "room": "or",
     "facilityFee": true,
     "sessions": 5,
     "price": 2800,
     "gross": 14000,
     "cogs": 2799.9999999999995,
     "net": 11200
    },
    {
     "id": "awakelipo",
     "name": "Awake Liposuction & Body Contouring (facility fee)",
     "cat": "Surgery",
     "margin": 0.78,
     "lo": 3000,
     "hi": 4600,
     "room": "or",
     "facilityFee": true,
     "sessions": 6,
     "price": 3800,
     "gross": 22800,
     "cogs": 5015.999999999999,
     "net": 17784
    },
    {
     "id": "fatgraft",
     "name": "Fat Grafting & Transfer (facility fee)",
     "cat": "Surgery",
     "margin": 0.8,
     "lo": 2200,
     "hi": 3400,
     "room": "or",
     "facilityFee": true,
     "sessions": 4,
     "price": 2800,
     "gross": 11200,
     "cogs": 2239.9999999999995,
     "net": 8960
    },
    {
     "id": "hairrest",
     "name": "Hair Restoration Surgery",
     "cat": "Surgery",
     "margin": 0.74,
     "lo": 6000,
     "hi": 14000,
     "room": "treatment",
     "sessions": 3,
     "price": 10000,
     "gross": 30000,
     "cogs": 7800,
     "net": 22200
    },
    {
     "id": "officesurg",
     "name": "Office Surgical Procedures",
     "cat": "Surgery",
     "margin": 0.76,
     "lo": 900,
     "hi": 3500,
     "room": "treatment",
     "sessions": 12,
     "price": 2200,
     "gross": 26400,
     "cogs": 6336,
     "net": 20064
    },
    {
     "id": "ablative",
     "name": "Ablative Laser & Skin Tightening",
     "cat": "Surgery",
     "margin": 0.73,
     "lo": 2500,
     "hi": 6000,
     "room": "treatment",
     "sessions": 5,
     "price": 4250,
     "gross": 21250,
     "cogs": 5737.5,
     "net": 15512.5
    }
   ],
   "rackValue": 564480,
   "serviceCogs": 149020.6,
   "redeemed": 129500,
   "alaCarteGross": 434980,
   "memberDiscount": 34798.4,
   "alaCarteNet": 400181.6,
   "membershipLines": [
    {
     "id": "friends",
     "name": "Friends of L&K",
     "count": 900,
     "monthly": 22500
    },
    {
     "id": "resident",
     "name": "Resident",
     "count": 350,
     "monthly": 157500
    },
    {
     "id": "longevity",
     "name": "Longevity",
     "count": 40,
     "monthly": 50000
    }
   ],
   "membershipRevenue": 230000,
   "accessRevenue": 20625,
   "totalRevenue": 650806.6,
   "circuitCogs": 18760,
   "totalCogs": 167780.6,
   "netAfterCogs": 483026,
   "blendedMargin": 0.742195915038354,
   "serviceMargin": 0.7360037556689343,
   "redemptionRatio": 0.6240963855421687,
   "opexTotal": 355650,
   "operatingIncome": 127376,
   "operatingIncomeAnnual": 1528512,
   "operatingMargin": 0.19572020320629815,
   "revenueAnnual": 7809679.199999999,
   "injectionFloor": 555000,
   "injectionPlanning": 1110000,
   "loanFloor": 4995000,
   "loanPlanning": 4440000,
   "isPrivate": false,
   "injectionPct": 0.1,
   "monthlyDebt": 71558,
   "annualDebt": 858701,
   "interestOnlyPayment": 39544,
   "dscr": 1.7800288029319935,
   "rateBand": [
    {
     "rate": 0.095,
     "monthly": 71558,
     "annual": 858701,
     "dscr": 1.7800288029319935
    },
    {
     "rate": 0.105,
     "monthly": 74232,
     "annual": 890788,
     "dscr": 1.7159095225451935
    },
    {
     "rate": 0.115,
     "monthly": 76960,
     "annual": 923521,
     "dscr": 1.6550910327518402
    }
   ],
   "founding": {
    "count": 150,
    "prepay": 3600,
    "discount": 0.33333333333333337,
    "proceeds": 540000
   },
   "capacity": {
    "operatingRoom": {
     "cases": 22,
     "theoretical": 90,
     "practical": 63,
     "demand": 38.5,
     "utilization": 0.6111111111111112,
     "headroom": 24.5
    },
    "circuit": {
     "theoretical": 6384,
     "practical": 3192,
     "demand": 2345,
     "utilization": 0.7346491228070177,
     "headroom": 847
    },
    "treatmentRooms": {
     "theoretical": 780,
     "practical": 507,
     "demand": 300,
     "utilization": 0.591715976331361,
     "headroom": 207
    }
   },
   "ramp": [
    {
     "month": 1,
     "maturity": 0,
     "open": false,
     "revenue": 0,
     "cogs": 0,
     "opex": 124477,
     "operating": -124477,
     "debtService": 19772,
     "foundingProceeds": 90000,
     "netCash": -54249,
     "cumulativeCash": -54249
    },
    {
     "month": 2,
     "maturity": 0,
     "open": false,
     "revenue": 0,
     "cogs": 0,
     "opex": 124477,
     "operating": -124477,
     "debtService": 19772,
     "foundingProceeds": 90000,
     "netCash": -54249,
     "cumulativeCash": -108499
    },
    {
     "month": 3,
     "maturity": 0,
     "open": false,
     "revenue": 0,
     "cogs": 0,
     "opex": 124477,
     "operating": -124477,
     "debtService": 19772,
     "foundingProceeds": 90000,
     "netCash": -54249,
     "cumulativeCash": -162748
    },
    {
     "month": 4,
     "maturity": 0,
     "open": false,
     "revenue": 0,
     "cogs": 0,
     "opex": 124477,
     "operating": -124477,
     "debtService": 19772,
     "foundingProceeds": 90000,
     "netCash": -54249,
     "cumulativeCash": -216997
    },
    {
     "month": 5,
     "maturity": 0,
     "open": false,
     "revenue": 0,
     "cogs": 0,
     "opex": 124477,
     "operating": -124477,
     "debtService": 19772,
     "foundingProceeds": 90000,
     "netCash": -54249,
     "cumulativeCash": -271247
    },
    {
     "month": 6,
     "maturity": 0,
     "open": false,
     "revenue": 0,
     "cogs": 0,
     "opex": 124477,
     "operating": -124477,
     "debtService": 19772,
     "foundingProceeds": 90000,
     "netCash": -54249,
     "cumulativeCash": -325496
    },
    {
     "month": 7,
     "maturity": 0.15,
     "open": true,
     "revenue": 97621,
     "cogs": 25167,
     "opex": 248955,
     "operating": -176501,
     "debtService": 39544,
     "foundingProceeds": 0,
     "netCash": -216045,
     "cumulativeCash": -541541
    },
    {
     "month": 8,
     "maturity": 0.22,
     "open": true,
     "revenue": 143177,
     "cogs": 36912,
     "opex": 248955,
     "operating": -142689,
     "debtService": 39544,
     "foundingProceeds": 0,
     "netCash": -182233,
     "cumulativeCash": -723774
    },
    {
     "month": 9,
     "maturity": 0.3,
     "open": true,
     "revenue": 195242,
     "cogs": 50334,
     "opex": 248955,
     "operating": -104047,
     "debtService": 39544,
     "foundingProceeds": 0,
     "netCash": -143591,
     "cumulativeCash": -867365
    },
    {
     "month": 10,
     "maturity": 0.36,
     "open": true,
     "revenue": 234290,
     "cogs": 60401,
     "opex": 248955,
     "operating": -75066,
     "debtService": 39544,
     "foundingProceeds": 0,
     "netCash": -114609,
     "cumulativeCash": -981974
    },
    {
     "month": 11,
     "maturity": 0.42,
     "open": true,
     "revenue": 273339,
     "cogs": 70468,
     "opex": 248955,
     "operating": -46084,
     "debtService": 39544,
     "foundingProceeds": 0,
     "netCash": -85628,
     "cumulativeCash": -1067602
    },
    {
     "month": 12,
     "maturity": 0.48,
     "open": true,
     "revenue": 312387,
     "cogs": 80535,
     "opex": 248955,
     "operating": -17103,
     "debtService": 39544,
     "foundingProceeds": 0,
     "netCash": -56646,
     "cumulativeCash": -1124249
    },
    {
     "month": 13,
     "maturity": 0.54,
     "open": true,
     "revenue": 351436,
     "cogs": 90602,
     "opex": 248955,
     "operating": 11879,
     "debtService": 39544,
     "foundingProceeds": 0,
     "netCash": -27665,
     "cumulativeCash": -1151913
    },
    {
     "month": 14,
     "maturity": 0.58,
     "open": true,
     "revenue": 377468,
     "cogs": 97313,
     "opex": 248955,
     "operating": 31200,
     "debtService": 39544,
     "foundingProceeds": 0,
     "netCash": -8344,
     "cumulativeCash": -1160257
    },
    {
     "month": 15,
     "maturity": 0.62,
     "open": true,
     "revenue": 403500,
     "cogs": 104024,
     "opex": 248955,
     "operating": 50521,
     "debtService": 39544,
     "foundingProceeds": 0,
     "netCash": 10977,
     "cumulativeCash": -1149280
    },
    {
     "month": 16,
     "maturity": 0.66,
     "open": true,
     "revenue": 429532,
     "cogs": 110735,
     "opex": 248955,
     "operating": 69842,
     "debtService": 39544,
     "foundingProceeds": 0,
     "netCash": 30298,
     "cumulativeCash": -1118981
    },
    {
     "month": 17,
     "maturity": 0.7,
     "open": true,
     "revenue": 455565,
     "cogs": 117446,
     "opex": 248955,
     "operating": 89163,
     "debtService": 39544,
     "foundingProceeds": 0,
     "netCash": 49619,
     "cumulativeCash": -1069362
    },
    {
     "month": 18,
     "maturity": 0.73,
     "open": true,
     "revenue": 475089,
     "cogs": 122480,
     "opex": 259625,
     "operating": 92984,
     "debtService": 39544,
     "foundingProceeds": 0,
     "netCash": 53441,
     "cumulativeCash": -1015921
    },
    {
     "month": 19,
     "maturity": 0.76,
     "open": true,
     "revenue": 494613,
     "cogs": 127513,
     "opex": 270294,
     "operating": 96806,
     "debtService": 71558,
     "foundingProceeds": 0,
     "netCash": 25247,
     "cumulativeCash": -990674
    },
    {
     "month": 20,
     "maturity": 0.79,
     "open": true,
     "revenue": 514137,
     "cogs": 132547,
     "opex": 280964,
     "operating": 100627,
     "debtService": 71558,
     "foundingProceeds": 0,
     "netCash": 29069,
     "cumulativeCash": -961605
    },
    {
     "month": 21,
     "maturity": 0.82,
     "open": true,
     "revenue": 533661,
     "cogs": 137580,
     "opex": 291633,
     "operating": 104448,
     "debtService": 71558,
     "foundingProceeds": 0,
     "netCash": 32890,
     "cumulativeCash": -928715
    },
    {
     "month": 22,
     "maturity": 0.85,
     "open": true,
     "revenue": 553186,
     "cogs": 142614,
     "opex": 302303,
     "operating": 108270,
     "debtService": 71558,
     "foundingProceeds": 0,
     "netCash": 36711,
     "cumulativeCash": -892004
    },
    {
     "month": 23,
     "maturity": 0.87,
     "open": true,
     "revenue": 566202,
     "cogs": 145969,
     "opex": 309416,
     "operating": 110817,
     "debtService": 71558,
     "foundingProceeds": 0,
     "netCash": 39259,
     "cumulativeCash": -852745
    },
    {
     "month": 24,
     "maturity": 0.89,
     "open": true,
     "revenue": 579218,
     "cogs": 149325,
     "opex": 316529,
     "operating": 113365,
     "debtService": 71558,
     "foundingProceeds": 0,
     "netCash": 41806,
     "cumulativeCash": -810939
    },
    {
     "month": 25,
     "maturity": 0.91,
     "open": true,
     "revenue": 592234,
     "cogs": 152680,
     "opex": 323642,
     "operating": 115912,
     "debtService": 71558,
     "foundingProceeds": 0,
     "netCash": 44354,
     "cumulativeCash": -766585
    },
    {
     "month": 26,
     "maturity": 0.93,
     "open": true,
     "revenue": 605250,
     "cogs": 156036,
     "opex": 330755,
     "operating": 118460,
     "debtService": 71558,
     "foundingProceeds": 0,
     "netCash": 46901,
     "cumulativeCash": -719684
    },
    {
     "month": 27,
     "maturity": 0.94,
     "open": true,
     "revenue": 611758,
     "cogs": 157714,
     "opex": 334311,
     "operating": 119733,
     "debtService": 71558,
     "foundingProceeds": 0,
     "netCash": 48175,
     "cumulativeCash": -671509
    },
    {
     "month": 28,
     "maturity": 0.96,
     "open": true,
     "revenue": 624774,
     "cogs": 161069,
     "opex": 341424,
     "operating": 122281,
     "debtService": 71558,
     "foundingProceeds": 0,
     "netCash": 50723,
     "cumulativeCash": -620786
    },
    {
     "month": 29,
     "maturity": 0.97,
     "open": true,
     "revenue": 631282,
     "cogs": 162747,
     "opex": 344981,
     "operating": 123555,
     "debtService": 71558,
     "foundingProceeds": 0,
     "netCash": 51996,
     "cumulativeCash": -568790
    },
    {
     "month": 30,
     "maturity": 0.98,
     "open": true,
     "revenue": 637790,
     "cogs": 164425,
     "opex": 348537,
     "operating": 124828,
     "debtService": 71558,
     "foundingProceeds": 0,
     "netCash": 53270,
     "cumulativeCash": -515520
    },
    {
     "month": 31,
     "maturity": 0.99,
     "open": true,
     "revenue": 644299,
     "cogs": 166103,
     "opex": 352094,
     "operating": 126102,
     "debtService": 71558,
     "foundingProceeds": 0,
     "netCash": 54544,
     "cumulativeCash": -460976
    },
    {
     "month": 32,
     "maturity": 1,
     "open": true,
     "revenue": 650807,
     "cogs": 167781,
     "opex": 355650,
     "operating": 127376,
     "debtService": 71558,
     "foundingProceeds": 0,
     "netCash": 55818,
     "cumulativeCash": -405158
    },
    {
     "month": 33,
     "maturity": 1,
     "open": true,
     "revenue": 650807,
     "cogs": 167781,
     "opex": 355650,
     "operating": 127376,
     "debtService": 71558,
     "foundingProceeds": 0,
     "netCash": 55818,
     "cumulativeCash": -349341
    },
    {
     "month": 34,
     "maturity": 1,
     "open": true,
     "revenue": 650807,
     "cogs": 167781,
     "opex": 355650,
     "operating": 127376,
     "debtService": 71558,
     "foundingProceeds": 0,
     "netCash": 55818,
     "cumulativeCash": -293523
    },
    {
     "month": 35,
     "maturity": 1,
     "open": true,
     "revenue": 650807,
     "cogs": 167781,
     "opex": 355650,
     "operating": 127376,
     "debtService": 71558,
     "foundingProceeds": 0,
     "netCash": 55818,
     "cumulativeCash": -237706
    },
    {
     "month": 36,
     "maturity": 1,
     "open": true,
     "revenue": 650807,
     "cogs": 167781,
     "opex": 355650,
     "operating": 127376,
     "debtService": 71558,
     "foundingProceeds": 0,
     "netCash": 55818,
     "cumulativeCash": -181888
    }
   ],
   "breakeven": 13,
   "dscrByYear": [
    {
     "year": 1,
     "operating": -1308352,
     "debt": 355896,
     "dscr": -3.67622001933149,
     "passes": false
    },
    {
     "year": 2,
     "operating": 979922,
     "debt": 666612,
     "dscr": 1.4700035402903038,
     "passes": true
    },
    {
     "year": 3,
     "operating": 1487751,
     "debt": 858696,
     "dscr": 1.7325700830095867,
     "passes": true
    }
   ],
   "band": [
    {
     "label": "Low",
     "tag": "Slow member ramp, 72% of base volume",
     "revenue": 468581,
     "netAfterCogs": 347779,
     "operating": -7871,
     "annual": -94455,
     "dscr": -0.10999796203800896
    },
    {
     "label": "Base",
     "tag": "Stated assumptions at stabilization",
     "revenue": 650807,
     "netAfterCogs": 483026,
     "operating": 127376,
     "annual": 1528512,
     "dscr": 1.7800282053939613
    },
    {
     "label": "Upside",
     "tag": "Waitlist demand, 128% of base volume",
     "revenue": 833032,
     "netAfterCogs": 618273,
     "operating": 262623,
     "annual": 3151479,
     "dscr": 3.670054372825932
    }
   ],
   "trough": {
    "month": 14,
    "amount": -1160257
   },
   "reserve": 1395000,
   "rateStressPasses": true,
   "rateStress": {
    "rate": 0.115,
    "monthly": 76960,
    "annual": 923521,
    "dscr": 1.6550910327518402
   }
  }
 }
};
